const ADJECTIVE_CATEGORY_DEFS = {
  color: [
    { key: "blue", en: "Blue", es: { m: "Azules", f: "Azules" }, ko: "파란" },
    { key: "red", en: "Red", es: { m: "Rojos", f: "Rojas" }, ko: "빨간" },
    { key: "green", en: "Green", es: { m: "Verdes", f: "Verdes" }, ko: "초록" },
    { key: "black", en: "Black", es: { m: "Negros", f: "Negras" }, ko: "검은" },
    { key: "white", en: "White", es: { m: "Blancos", f: "Blancas" }, ko: "하얀" },
    { key: "yellow", en: "Yellow", es: { m: "Amarillos", f: "Amarillas" }, ko: "노란" },
    { key: "orange", en: "Orange", es: { m: "Naranjas", f: "Naranjas" }, ko: "주황" },
    { key: "purple", en: "Purple", es: { m: "Morados", f: "Moradas" }, ko: "보라" },
    { key: "pink", en: "Pink", es: { m: "Rosas", f: "Rosas" }, ko: "분홍" },
    { key: "brown", en: "Brown", es: { m: "Marrones", f: "Marrones" }, ko: "갈색" },
    { key: "gray", en: "Gray", es: { m: "Grises", f: "Grises" }, ko: "회색" },
    { key: "gold", en: "Gold", es: { m: "Dorados", f: "Doradas" }, ko: "금빛" },
    { key: "silver", en: "Silver", es: { m: "Plateados", f: "Plateadas" }, ko: "은빛" },
    { key: "teal", en: "Teal", es: { m: "Aguamarinas", f: "Aguamarinas" }, ko: "청록" },
    { key: "navy", en: "Navy", es: { m: "Marinos", f: "Marinas" }, ko: "남색" },
    { key: "indigo", en: "Indigo", es: { m: "Índigos", f: "Índigos" }, ko: "인디고" },
    { key: "violet", en: "Violet", es: { m: "Violetas", f: "Violetas" }, ko: "바이올렛" },
    { key: "turquoise", en: "Turquoise", es: { m: "Turquesas", f: "Turquesas" }, ko: "터키석" },
    { key: "magenta", en: "Magenta", es: { m: "Magentas", f: "Magentas" }, ko: "마젠타" },
    { key: "cyan", en: "Cyan", es: { m: "Cianes", f: "Cianes" }, ko: "시안" },
    { key: "maroon", en: "Maroon", es: { m: "Granates", f: "Granates" }, ko: "자주" },
    { key: "beige", en: "Beige", es: { m: "Beiges", f: "Beiges" }, ko: "베이지" },
    { key: "cream", en: "Cream", es: { m: "Cremas", f: "Cremas" }, ko: "크림" },
    { key: "olive", en: "Olive", es: { m: "Olivas", f: "Olivas" }, ko: "올리브" },
    { key: "amber", en: "Amber", es: { m: "Ámbares", f: "Ámbares" }, ko: "호박빛" },
  ],
  light: [
    { key: "bright", en: "Bright", es: { m: "Brillantes", f: "Brillantes" }, ko: "밝은" },
    { key: "glowing", en: "Glowing", es: { m: "Resplandecientes", f: "Resplandecientes" }, ko: "빛나는" },
    { key: "radiant", en: "Radiant", es: { m: "Radiantes", f: "Radiantes" }, ko: "찬란한" },
    { key: "luminous", en: "Luminous", es: { m: "Luminosos", f: "Luminosas" }, ko: "광채나는" },
    { key: "luminescent", en: "Luminescent", es: { m: "Luminiscentes", f: "Luminiscentes" }, ko: "발광하는" },
    { key: "shining", en: "Shining", es: { m: "Relucientes", f: "Relucientes" }, ko: "반짝이는" },
    { key: "gleaming", en: "Gleaming", es: { m: "Centelleantes", f: "Centelleantes" }, ko: "번쩍이는" },
    { key: "sparkling", en: "Sparkling", es: { m: "Chispeantes", f: "Chispeantes" }, ko: "반짝반짝한" },
    { key: "shimmering", en: "Shimmering", es: { m: "Destellantes", f: "Destellantes" }, ko: "아른거리는" },
    { key: "glittering", en: "Glittering", es: { m: "Brillosos", f: "Brillosas" }, ko: "번쩍거리는" },
    { key: "dazzling", en: "Dazzling", es: { m: "Deslumbrantes", f: "Deslumbrantes" }, ko: "눈부신" },
    { key: "neon", en: "Neon", es: { m: "Neones", f: "Neones" }, ko: "네온" },
    { key: "vivid", en: "Vivid", es: { m: "Vívidos", f: "Vívidas" }, ko: "선명한" },
    { key: "brilliant", en: "Brilliant", es: { m: "Espléndidos", f: "Espléndidas" }, ko: "영롱한" },
    { key: "illuminated", en: "Illuminated", es: { m: "Iluminados", f: "Iluminadas" }, ko: "조명된" },
    { key: "flashing", en: "Flashing", es: { m: "Intermitentes", f: "Intermitentes" }, ko: "번쩍이는" },
    { key: "flickering", en: "Flickering", es: { m: "Parpadeantes", f: "Parpadeantes" }, ko: "깜박이는" },
    { key: "glimmering", en: "Glimmering", es: { m: "Rutilantes", f: "Rutilantes" }, ko: "희미하게빛나는" },
    { key: "twinkling", en: "Twinkling", es: { m: "Titilantes", f: "Titilantes" }, ko: "반짝이는" },
    { key: "beaming", en: "Beaming", es: { m: "Radiosos", f: "Radiosas" }, ko: "환한" },
    { key: "sunlit", en: "Sunlit", es: { m: "Soleados", f: "Soleadas" }, ko: "햇빛받은" },
    { key: "moonlit", en: "Moonlit", es: { m: "Lunares", f: "Lunares" }, ko: "달빛받은" },
    { key: "fluorescent", en: "Fluorescent", es: { m: "Fluorescentes", f: "Fluorescentes" }, ko: "형광의" },
    { key: "incandescent", en: "Incandescent", es: { m: "Incandescentes", f: "Incandescentes" }, ko: "백열의" },
    { key: "lit", en: "Lit", es: { m: "Encendidos", f: "Encendidas" }, ko: "불밝힌" },
  ],
  temperature: [
    { key: "hot", en: "Hot", es: { m: "Calientes", f: "Calientes" }, ko: "뜨거운" },
    { key: "cold", en: "Cold", es: { m: "Fríos", f: "Frías" }, ko: "차가운" },
    { key: "warm", en: "Warm", es: { m: "Cálidos", f: "Cálidas" }, ko: "따뜻한" },
    { key: "cool", en: "Cool", es: { m: "Frescos", f: "Frescas" }, ko: "시원한" },
    { key: "icy", en: "Icy", es: { m: "Helados", f: "Heladas" }, ko: "얼음같은" },
    { key: "frozen", en: "Frozen", es: { m: "Congelados", f: "Congeladas" }, ko: "얼어붙은" },
    { key: "chilly", en: "Chilly", es: { m: "Gélidos", f: "Gélidas" }, ko: "쌀쌀한" },
    { key: "frosty", en: "Frosty", es: { m: "Escarchados", f: "Escarchadas" }, ko: "서리낀" },
    { key: "fiery", en: "Fiery", es: { m: "Ardientes", f: "Ardientes" }, ko: "불같은" },
    { key: "burning", en: "Burning", es: { m: "Quemantes", f: "Quemantes" }, ko: "타오르는" },
    { key: "blazing", en: "Blazing", es: { m: "Llameantes", f: "Llameantes" }, ko: "타는" },
    { key: "boiling", en: "Boiling", es: { m: "Hirvientes", f: "Hirvientes" }, ko: "끓는" },
    { key: "scorching", en: "Scorching", es: { m: "Sofocantes", f: "Sofocantes" }, ko: "작열하는" },
    { key: "searing", en: "Searing", es: { m: "Tórridos", f: "Tórridas" }, ko: "달아오른" },
    { key: "steaming", en: "Steaming", es: { m: "Humeantes", f: "Humeantes" }, ko: "김이오르는" },
    { key: "heated", en: "Heated", es: { m: "Caldeados", f: "Caldeadas" }, ko: "가열된" },
    { key: "toasty", en: "Toasty", es: { m: "Tostados", f: "Tostadas" }, ko: "포근한" },
    { key: "sweltering", en: "Sweltering", es: { m: "Asfixiantes", f: "Asfixiantes" }, ko: "숨막히는" },
    { key: "freezing", en: "Freezing", es: { m: "Congelantes", f: "Congelantes" }, ko: "얼어붙는" },
    { key: "chilled", en: "Chilled", es: { m: "Enfriados", f: "Enfriadas" }, ko: "차갑게식은" },
    { key: "mild", en: "Mild", es: { m: "Templados", f: "Templadas" }, ko: "온화한" },
    { key: "tepid", en: "Tepid", es: { m: "Tibios", f: "Tibias" }, ko: "미지근한" },
    { key: "sultry", en: "Sultry", es: { m: "Bochornosos", f: "Bochornosas" }, ko: "후덥지근한" },
    { key: "arctic", en: "Arctic", es: { m: "Árticos", f: "Árticas" }, ko: "극지의" },
    { key: "tropical", en: "Tropical", es: { m: "Tropicales", f: "Tropicales" }, ko: "열대의" },
  ],
  texture: [
    { key: "soft", en: "Soft", es: { m: "Suaves", f: "Suaves" }, ko: "부드러운" },
    { key: "rough", en: "Rough", es: { m: "Ásperos", f: "Ásperas" }, ko: "거친" },
    { key: "smooth", en: "Smooth", es: { m: "Lisos", f: "Lisas" }, ko: "매끄러운" },
    { key: "silky", en: "Silky", es: { m: "Sedosos", f: "Sedosas" }, ko: "비단결같은" },
    { key: "velvety", en: "Velvety", es: { m: "Aterciopelados", f: "Aterciopeladas" }, ko: "벨벳같은" },
    { key: "fuzzy", en: "Fuzzy", es: { m: "Peludos", f: "Peludas" }, ko: "보송보송한" },
    { key: "fluffy", en: "Fluffy", es: { m: "Esponjosos", f: "Esponjosas" }, ko: "폭신한" },
    { key: "grainy", en: "Grainy", es: { m: "Granulosos", f: "Granulosas" }, ko: "까슬까슬한" },
    { key: "gritty", en: "Gritty", es: { m: "Arenosos", f: "Arenosas" }, ko: "모래같은" },
    { key: "slick", en: "Slick", es: { m: "Resbaladizos", f: "Resbaladizas" }, ko: "미끄러운" },
    { key: "slippery", en: "Slippery", es: { m: "Deslizantes", f: "Deslizantes" }, ko: "미끄덩한" },
    { key: "sticky", en: "Sticky", es: { m: "Pegajosos", f: "Pegajosas" }, ko: "끈적한" },
    { key: "tacky", en: "Tacky", es: { m: "Chiclosos", f: "Chiclosas" }, ko: "끈끈한" },
    { key: "bumpy", en: "Bumpy", es: { m: "Abultados", f: "Abultadas" }, ko: "울퉁불퉁한" },
    { key: "pebbled", en: "Pebbled", es: { m: "Pedregosos", f: "Pedregosas" }, ko: "자갈같은" },
    { key: "glossy", en: "Glossy", es: { m: "Lustrosos", f: "Lustrosas" }, ko: "윤기나는" },
    { key: "matte", en: "Matte", es: { m: "Mates", f: "Mates" }, ko: "무광의" },
    { key: "sleek", en: "Sleek", es: { m: "Pulidos", f: "Pulidas" }, ko: "매끈한" },
    { key: "woolly", en: "Woolly", es: { m: "Lanudos", f: "Lanudas" }, ko: "털북숭이의" },
    { key: "plush", en: "Plush", es: { m: "Mullidos", f: "Mullidas" }, ko: "포근한" },
    { key: "ragged", en: "Ragged", es: { m: "Desgastados", f: "Desgastadas" }, ko: "해진" },
    { key: "crinkled", en: "Crinkled", es: { m: "Plisados", f: "Plisadas" }, ko: "구겨진" },
    { key: "wrinkled", en: "Wrinkled", es: { m: "Arrugados", f: "Arrugadas" }, ko: "주름진" },
    { key: "brittle", en: "Brittle", es: { m: "Quebradizos", f: "Quebradizas" }, ko: "부서지기쉬운" },
    { key: "spongy", en: "Spongy", es: { m: "Porosos", f: "Porosas" }, ko: "스펀지같은" },
  ],
  material: [
    { key: "wooden", en: "Wooden", es: { m: "Maderados", f: "Maderadas" }, ko: "나무의" },
    { key: "metallic", en: "Metallic", es: { m: "Metálicos", f: "Metálicas" }, ko: "금속의" },
    { key: "glassy", en: "Glassy", es: { m: "Vidriosos", f: "Vidriosas" }, ko: "유리같은" },
    { key: "stone", en: "Stone", es: { m: "Pétreos", f: "Pétreas" }, ko: "돌의" },
    { key: "marble", en: "Marble", es: { m: "Marmóreos", f: "Marmóreas" }, ko: "대리석의" },
    { key: "granite", en: "Granite", es: { m: "Graníticos", f: "Graníticas" }, ko: "화강암의" },
    { key: "steel", en: "Steel", es: { m: "Acerados", f: "Aceradas" }, ko: "강철의" },
    { key: "iron", en: "Iron", es: { m: "Ferrosos", f: "Ferrosas" }, ko: "철의" },
    { key: "copper", en: "Copper", es: { m: "Cobrizos", f: "Cobrizas" }, ko: "구리의" },
    { key: "bronze", en: "Bronze", es: { m: "Bronceados", f: "Bronceadas" }, ko: "청동의" },
    { key: "brass", en: "Brass", es: { m: "Latonados", f: "Latonadas" }, ko: "황동의" },
    { key: "plastic", en: "Plastic", es: { m: "Plásticos", f: "Plásticas" }, ko: "플라스틱" },
    { key: "paper", en: "Paper", es: { m: "Papel", f: "Papel" }, ko: "종이의" },
    { key: "leather", en: "Leather", es: { m: "Cueros", f: "Cueros" }, ko: "가죽의" },
    { key: "rubber", en: "Rubber", es: { m: "Gomosos", f: "Gomosas" }, ko: "고무의" },
    { key: "cotton", en: "Cotton", es: { m: "Algodonados", f: "Algodonadas" }, ko: "면의" },
    { key: "silken", en: "Silken", es: { m: "Sedosos", f: "Sedosas" }, ko: "비단의" },
    { key: "woolen", en: "Woolen", es: { m: "Lanudos", f: "Lanudas" }, ko: "양모의" },
    { key: "linen", en: "Linen", es: { m: "Linos", f: "Linas" }, ko: "린넨의" },
    { key: "ceramic", en: "Ceramic", es: { m: "Cerámicos", f: "Cerámicas" }, ko: "세라믹" },
    { key: "porcelain", en: "Porcelain", es: { m: "Porcelana", f: "Porcelana" }, ko: "도자기의" },
    { key: "concrete", en: "Concrete", es: { m: "Concretos", f: "Concretas" }, ko: "콘크리트" },
    { key: "carbon", en: "Carbon", es: { m: "Carbónicos", f: "Carbónicas" }, ko: "탄소의" },
    { key: "crystal", en: "Crystal", es: { m: "Cristalinos", f: "Cristalinas" }, ko: "크리스탈" },
    { key: "clay", en: "Clay", es: { m: "Arcillosos", f: "Arcillosas" }, ko: "점토의" },
  ],
  size: [
    { key: "big", en: "Big", es: { m: "Grandes", f: "Grandes" }, ko: "큰" },
    { key: "small", en: "Small", es: { m: "Pequeños", f: "Pequeñas" }, ko: "작은" },
    { key: "large", en: "Large", es: { m: "Amplios", f: "Amplias" }, ko: "커다란" },
    { key: "tiny", en: "Tiny", es: { m: "Minúsculos", f: "Minúsculas" }, ko: "아주작은" },
    { key: "huge", en: "Huge", es: { m: "Enormes", f: "Enormes" }, ko: "거대한" },
    { key: "massive", en: "Massive", es: { m: "Masivos", f: "Masivas" }, ko: "육중한" },
    { key: "giant", en: "Giant", es: { m: "Gigantes", f: "Gigantes" }, ko: "거인같은" },
    { key: "mini", en: "Mini", es: { m: "Minis", f: "Minis" }, ko: "미니" },
    { key: "little", en: "Little", es: { m: "Pequeñitos", f: "Pequeñitas" }, ko: "아담한" },
    { key: "compact", en: "Compact", es: { m: "Compactos", f: "Compactas" }, ko: "컴팩트한" },
    { key: "petite", en: "Petite", es: { m: "Menudos", f: "Menudas" }, ko: "자그마한" },
    { key: "vast", en: "Vast", es: { m: "Vastos", f: "Vastas" }, ko: "광대한" },
    { key: "wide", en: "Wide", es: { m: "Anchos", f: "Anchas" }, ko: "넓은" },
    { key: "narrow", en: "Narrow", es: { m: "Estrechos", f: "Estrechas" }, ko: "좁은" },
    { key: "broad", en: "Broad", es: { m: "Extensos", f: "Extensas" }, ko: "너른" },
    { key: "bulky", en: "Bulky", es: { m: "Voluminosos", f: "Voluminosas" }, ko: "덩치큰" },
    { key: "chunky", en: "Chunky", es: { m: "Gruesos", f: "Gruesas" }, ko: "투박한" },
    { key: "slim", en: "Slim", es: { m: "Esbeltos", f: "Esbeltas" }, ko: "날씬한" },
    { key: "thick", en: "Thick", es: { m: "Espesos", f: "Espesas" }, ko: "두꺼운" },
    { key: "thin", en: "Thin", es: { m: "Delgados", f: "Delgadas" }, ko: "얇은" },
    { key: "great", en: "Great", es: { m: "Magnos", f: "Magnas" }, ko: "위대한" },
    { key: "oversized", en: "Oversized", es: { m: "Sobredimensionados", f: "Sobredimensionadas" }, ko: "과대한" },
    { key: "miniature", en: "Miniature", es: { m: "Miniaturas", f: "Miniaturas" }, ko: "미니어처" },
    { key: "jumbo", en: "Jumbo", es: { m: "Jumbo", f: "Jumbo" }, ko: "점보" },
    { key: "micro", en: "Micro", es: { m: "Micro", f: "Micro" }, ko: "마이크로" },
  ],
  height: [
    { key: "tall", en: "Tall", es: { m: "Altos", f: "Altas" }, ko: "키큰" },
    { key: "short", en: "Short", es: { m: "Cortos", f: "Cortas" }, ko: "짧은" },
    { key: "long", en: "Long", es: { m: "Largos", f: "Largas" }, ko: "긴" },
    { key: "high", en: "High", es: { m: "Elevados", f: "Elevadas" }, ko: "높은" },
    { key: "low", en: "Low", es: { m: "Bajos", f: "Bajas" }, ko: "낮은" },
    { key: "lofty", en: "Lofty", es: { m: "Altivos", f: "Altivas" }, ko: "우뚝한" },
    { key: "towering", en: "Towering", es: { m: "Imponentes", f: "Imponentes" }, ko: "우뚝솟은" },
    { key: "elongated", en: "Elongated", es: { m: "Alargados", f: "Alargadas" }, ko: "길쭉한" },
    { key: "stretched", en: "Stretched", es: { m: "Estirados", f: "Estiradas" }, ko: "늘어진" },
    { key: "extended", en: "Extended", es: { m: "Extendidos", f: "Extendidas" }, ko: "확장된" },
    { key: "lengthy", en: "Lengthy", es: { m: "Prolongados", f: "Prolongadas" }, ko: "장대한" },
    { key: "shortened", en: "Shortened", es: { m: "Acortados", f: "Acortadas" }, ko: "짧아진" },
    { key: "squat", en: "Squat", es: { m: "Achaparrados", f: "Achaparradas" }, ko: "작달막한" },
    { key: "upright", en: "Upright", es: { m: "Erguidos", f: "Erguidas" }, ko: "곧은" },
    { key: "elevated", en: "Elevated", es: { m: "Alzados", f: "Alzadas" }, ko: "높아진" },
    { key: "deep", en: "Deep", es: { m: "Profundos", f: "Profundas" }, ko: "깊은" },
    { key: "shallow", en: "Shallow", es: { m: "Superficiales", f: "Superficiales" }, ko: "얕은" },
    { key: "lanky", en: "Lanky", es: { m: "Desgarbados", f: "Desgarbadas" }, ko: "홀쭉한" },
    { key: "stubby", en: "Stubby", es: { m: "Rechonchos", f: "Rechonchas" }, ko: "짧뚱한" },
    { key: "raised", en: "Raised", es: { m: "Levantados", f: "Levantadas" }, ko: "들어올린" },
    { key: "sunken", en: "Sunken", es: { m: "Hundidos", f: "Hundidas" }, ko: "가라앉은" },
    { key: "vertical", en: "Vertical", es: { m: "Verticales", f: "Verticales" }, ko: "수직의" },
    { key: "horizontal", en: "Horizontal", es: { m: "Horizontales", f: "Horizontales" }, ko: "수평의" },
    { key: "overhead", en: "Overhead", es: { m: "Aéreos", f: "Aéreas" }, ko: "머리위의" },
    { key: "grounded", en: "Grounded", es: { m: "Terrestres", f: "Terrestres" }, ko: "지면의" },
  ],
  shape: [
    { key: "round", en: "Round", es: { m: "Redondos", f: "Redondas" }, ko: "둥근" },
    { key: "square", en: "Square", es: { m: "Cuadrados", f: "Cuadradas" }, ko: "네모난" },
    { key: "triangular", en: "Triangular", es: { m: "Triangulares", f: "Triangulares" }, ko: "삼각형의" },
    { key: "rectangular", en: "Rectangular", es: { m: "Rectangulares", f: "Rectangulares" }, ko: "직사각형의" },
    { key: "oval", en: "Oval", es: { m: "Ovalados", f: "Ovaladas" }, ko: "타원형의" },
    { key: "circular", en: "Circular", es: { m: "Circulares", f: "Circulares" }, ko: "원형의" },
    { key: "curved", en: "Curved", es: { m: "Curvos", f: "Curvas" }, ko: "굽은" },
    { key: "bent", en: "Bent", es: { m: "Doblados", f: "Dobladas" }, ko: "휜" },
    { key: "crooked", en: "Crooked", es: { m: "Torcidos", f: "Torcidas" }, ko: "비뚤어진" },
    { key: "twisted", en: "Twisted", es: { m: "Retorcidos", f: "Retorcidas" }, ko: "뒤틀린" },
    { key: "spiral", en: "Spiral", es: { m: "Espirales", f: "Espirales" }, ko: "나선형의" },
    { key: "flat", en: "Flat", es: { m: "Planos", f: "Planas" }, ko: "평평한" },
    { key: "hollow", en: "Hollow", es: { m: "Huecos", f: "Huecas" }, ko: "속빈" },
    { key: "pointed", en: "Pointed", es: { m: "Puntiagudos", f: "Puntiagudas" }, ko: "뾰족한" },
    { key: "sharp", en: "Sharp", es: { m: "Afilados", f: "Afiladas" }, ko: "날카로운" },
    { key: "angular", en: "Angular", es: { m: "Angulares", f: "Angulares" }, ko: "각진" },
    { key: "faceted", en: "Faceted", es: { m: "Facetados", f: "Facetadas" }, ko: "면이많은" },
    { key: "jagged", en: "Jagged", es: { m: "Dentados", f: "Dentadas" }, ko: "들쭉날쭉한" },
    { key: "spiky", en: "Spiky", es: { m: "Espinosos", f: "Espinosas" }, ko: "가시돋친" },
    { key: "wavy", en: "Wavy", es: { m: "Ondulados", f: "Onduladas" }, ko: "물결치는" },
    { key: "cubic", en: "Cubic", es: { m: "Cúbicos", f: "Cúbicas" }, ko: "정육면체의" },
    { key: "spherical", en: "Spherical", es: { m: "Esféricos", f: "Esféricas" }, ko: "구형의" },
    { key: "symmetric", en: "Symmetric", es: { m: "Simétricos", f: "Simétricas" }, ko: "대칭의" },
    { key: "asymmetric", en: "Asymmetric", es: { m: "Asimétricos", f: "Asimétricas" }, ko: "비대칭의" },
    { key: "tapered", en: "Tapered", es: { m: "Ahusados", f: "Ahusadas" }, ko: "점점좁아진" },
  ],
  speed: [
    { key: "fast", en: "Fast", es: { m: "Rápidos", f: "Rápidas" }, ko: "빠른" },
    { key: "slow", en: "Slow", es: { m: "Lentos", f: "Lentas" }, ko: "느린" },
    { key: "quick", en: "Quick", es: { m: "Veloces", f: "Veloces" }, ko: "재빠른" },
    { key: "rapid", en: "Rapid", es: { m: "Acelerados", f: "Aceleradas" }, ko: "급속한" },
    { key: "swift", en: "Swift", es: { m: "Ligeros", f: "Ligeras" }, ko: "날렵한" },
    { key: "speedy", en: "Speedy", es: { m: "Precipitados", f: "Precipitadas" }, ko: "신속한" },
    { key: "hasty", en: "Hasty", es: { m: "Apresurados", f: "Apresuradas" }, ko: "서두르는" },
    { key: "rushing", en: "Rushing", es: { m: "Atropellados", f: "Atropelladas" }, ko: "달려드는" },
    { key: "racing", en: "Racing", es: { m: "Corredores", f: "Corredoras" }, ko: "질주하는" },
    { key: "flying", en: "Flying", es: { m: "Voladores", f: "Voladoras" }, ko: "날아가는" },
    { key: "turbo", en: "Turbo", es: { m: "Turbo", f: "Turbo" }, ko: "터보" },
    { key: "steady", en: "Steady", es: { m: "Constantes", f: "Constantes" }, ko: "꾸준한" },
    { key: "rolling", en: "Rolling", es: { m: "Rodantes", f: "Rodantes" }, ko: "구르는" },
    { key: "drifting", en: "Drifting", es: { m: "Derivantes", f: "Derivantes" }, ko: "표류하는" },
    { key: "sliding", en: "Sliding", es: { m: "Deslizantes", f: "Deslizantes" }, ko: "미끄러지는" },
    { key: "moving", en: "Moving", es: { m: "Móviles", f: "Móviles" }, ko: "움직이는" },
    { key: "flowing", en: "Flowing", es: { m: "Fluidos", f: "Fluidas" }, ko: "흐르는" },
    { key: "running", en: "Running", es: { m: "Corredores", f: "Corredoras" }, ko: "달리는" },
    { key: "spinning", en: "Spinning", es: { m: "Giratorios", f: "Giratorias" }, ko: "회전하는" },
    { key: "darting", en: "Darting", es: { m: "Fugaces", f: "Fugaces" }, ko: "재빨리움직이는" },
    { key: "soaring", en: "Soaring", es: { m: "Elevados", f: "Elevadas" }, ko: "솟구치는" },
    { key: "gliding", en: "Gliding", es: { m: "Planeadores", f: "Planeadoras" }, ko: "활공하는" },
    { key: "skimming", en: "Skimming", es: { m: "Rozantes", f: "Rozantes" }, ko: "스치는" },
    { key: "charging", en: "Charging", es: { m: "Arremetidos", f: "Arremetidas" }, ko: "돌진하는" },
    { key: "cruising", en: "Cruising", es: { m: "Navegantes", f: "Navegantes" }, ko: "순항하는" },
  ],
  strength: [
    { key: "strong", en: "Strong", es: { m: "Fuertes", f: "Fuertes" }, ko: "강한" },
    { key: "powerful", en: "Powerful", es: { m: "Poderosos", f: "Poderosas" }, ko: "강력한" },
    { key: "mighty", en: "Mighty", es: { m: "Imponentes", f: "Imponentes" }, ko: "위력적인" },
    { key: "solid", en: "Solid", es: { m: "Sólidos", f: "Sólidas" }, ko: "단단한" },
    { key: "sturdy", en: "Sturdy", es: { m: "Resistentes", f: "Resistentes" }, ko: "튼튼한" },
    { key: "tough", en: "Tough", es: { m: "Duros", f: "Duras" }, ko: "질긴" },
    { key: "rugged", en: "Rugged", es: { m: "Rudos", f: "Rudas" }, ko: "거친" },
    { key: "durable", en: "Durable", es: { m: "Duraderos", f: "Duraderas" }, ko: "내구성있는" },
    { key: "forceful", en: "Forceful", es: { m: "Enérgicos", f: "Enérgicas" }, ko: "힘찬" },
    { key: "firm", en: "Firm", es: { m: "Firmes", f: "Firmes" }, ko: "단단한" },
    { key: "hardy", en: "Hardy", es: { m: "Robustos", f: "Robustas" }, ko: "강인한" },
    { key: "robust", en: "Robust", es: { m: "Robustos", f: "Robustas" }, ko: "견고한" },
    { key: "resilient", en: "Resilient", es: { m: "Resilientes", f: "Resilientes" }, ko: "회복력있는" },
    { key: "steadfast", en: "Steadfast", es: { m: "Tenaces", f: "Tenaces" }, ko: "굳건한" },
    { key: "vigorous", en: "Vigorous", es: { m: "Vigorosos", f: "Vigorosas" }, ko: "활기찬" },
    { key: "bold", en: "Bold", es: { m: "Audaces", f: "Audaces" }, ko: "대담한" },
    { key: "dominant", en: "Dominant", es: { m: "Dominantes", f: "Dominantes" }, ko: "지배적인" },
    { key: "potent", en: "Potent", es: { m: "Potentes", f: "Potentes" }, ko: "강력한" },
    { key: "muscular", en: "Muscular", es: { m: "Musculosos", f: "Musculosas" }, ko: "근육질의" },
    { key: "energetic", en: "Energetic", es: { m: "Energéticos", f: "Energéticas" }, ko: "에너지넘치는" },
    { key: "dynamic", en: "Dynamic", es: { m: "Dinámicos", f: "Dinámicas" }, ko: "역동적인" },
    { key: "reinforced", en: "Reinforced", es: { m: "Reforzados", f: "Reforzadas" }, ko: "강화된" },
    { key: "stout", en: "Stout", es: { m: "Fornidos", f: "Fornidas" }, ko: "건장한" },
    { key: "unyielding", en: "Unyielding", es: { m: "Inflexibles", f: "Inflexibles" }, ko: "완강한" },
    { key: "ironclad", en: "Ironclad", es: { m: "Inquebrantables", f: "Inquebrantables" }, ko: "철통같은" },
  ],
  calm: [
    { key: "calm", en: "Calm", es: { m: "Calmos", f: "Calmas" }, ko: "차분한" },
    { key: "quiet", en: "Quiet", es: { m: "Silenciosos", f: "Silenciosas" }, ko: "조용한" },
    { key: "serene", en: "Serene", es: { m: "Serenos", f: "Serenas" }, ko: "고요한" },
    { key: "peaceful", en: "Peaceful", es: { m: "Pacíficos", f: "Pacíficas" }, ko: "평화로운" },
    { key: "gentle", en: "Gentle", es: { m: "Suaves", f: "Suaves" }, ko: "온화한" },
    { key: "still", en: "Still", es: { m: "Quietos", f: "Quietas" }, ko: "잔잔한" },
    { key: "tranquil", en: "Tranquil", es: { m: "Tranquilos", f: "Tranquilas" }, ko: "평온한" },
    { key: "soothing", en: "Soothing", es: { m: "Calmantes", f: "Calmantes" }, ko: "진정시키는" },
    { key: "relaxed", en: "Relaxed", es: { m: "Relajados", f: "Relajadas" }, ko: "느긋한" },
    { key: "easygoing", en: "Easygoing", es: { m: "Desenfadados", f: "Desenfadadas" }, ko: "태평한" },
    { key: "patient", en: "Patient", es: { m: "Pacientes", f: "Pacientes" }, ko: "인내심있는" },
    { key: "tender", en: "Tender", es: { m: "Tiernos", f: "Tiernas" }, ko: "다정한" },
    { key: "composed", en: "Composed", es: { m: "Compuestos", f: "Compuestas" }, ko: "침착한" },
    { key: "balanced", en: "Balanced", es: { m: "Equilibrados", f: "Equilibradas" }, ko: "균형잡힌" },
    { key: "hushed", en: "Hushed", es: { m: "Amortiguados", f: "Amortiguadas" }, ko: "잠잠한" },
    { key: "restful", en: "Restful", es: { m: "Reparadores", f: "Reparadoras" }, ko: "편안한" },
    { key: "fierce", en: "Fierce", es: { m: "Feroces", f: "Feroces" }, ko: "사나운" },
    { key: "intense", en: "Intense", es: { m: "Intensos", f: "Intensas" }, ko: "강렬한" },
    { key: "furious", en: "Furious", es: { m: "Furiosos", f: "Furiosas" }, ko: "분노한" },
    { key: "raging", en: "Raging", es: { m: "Enfurecidos", f: "Enfurecidas" }, ko: "격렬한" },
    { key: "savage", en: "Savage", es: { m: "Salvajes", f: "Salvajes" }, ko: "야성적인" },
    { key: "ferocious", en: "Ferocious", es: { m: "Feroces", f: "Feroces" }, ko: "맹렬한" },
    { key: "aggressive", en: "Aggressive", es: { m: "Agresivos", f: "Agresivas" }, ko: "공격적인" },
    { key: "harsh", en: "Harsh", es: { m: "Duros", f: "Duras" }, ko: "거친" },
    { key: "relentless", en: "Relentless", es: { m: "Implacables", f: "Implacables" }, ko: "집요한" },
  ],
  weather: [
    { key: "stormy", en: "Stormy", es: { m: "Tormentosos", f: "Tormentosas" }, ko: "폭풍의" },
    { key: "sunny", en: "Sunny", es: { m: "Soleados", f: "Soleadas" }, ko: "맑은" },
    { key: "rainy", en: "Rainy", es: { m: "Lluviosos", f: "Lluviosas" }, ko: "비오는" },
    { key: "windy", en: "Windy", es: { m: "Ventosos", f: "Ventosas" }, ko: "바람부는" },
    { key: "cloudy", en: "Cloudy", es: { m: "Nublados", f: "Nubladas" }, ko: "흐린" },
    { key: "foggy", en: "Foggy", es: { m: "Nebulosos", f: "Nebulosas" }, ko: "안개낀" },
    { key: "misty", en: "Misty", es: { m: "Brumosos", f: "Brumosas" }, ko: "옅은안개" },
    { key: "hazy", en: "Hazy", es: { m: "Neblinosos", f: "Neblinosas" }, ko: "흐릿한" },
    { key: "snowy", en: "Snowy", es: { m: "Nevados", f: "Nevadas" }, ko: "눈오는" },
    { key: "breezy", en: "Breezy", es: { m: "Brisosos", f: "Brisosas" }, ko: "산들바람의" },
    { key: "drizzly", en: "Drizzly", es: { m: "Lloviznosos", f: "Lloviznosas" }, ko: "이슬비의" },
    { key: "thunderous", en: "Thunderous", es: { m: "Tronadores", f: "Tronadoras" }, ko: "천둥치는" },
    { key: "gusty", en: "Gusty", es: { m: "Racheados", f: "Racheadas" }, ko: "돌풍의" },
    { key: "overcast", en: "Overcast", es: { m: "Cubiertos", f: "Cubiertas" }, ko: "잿빛의" },
    { key: "cloudless", en: "Cloudless", es: { m: "Despejados", f: "Despejadas" }, ko: "구름없는" },
    { key: "blustery", en: "Blustery", es: { m: "Borrascosos", f: "Borrascosas" }, ko: "거센바람의" },
    { key: "turbulent", en: "Turbulent", es: { m: "Turbulentos", f: "Turbulentas" }, ko: "난류의" },
    { key: "monsoon", en: "Monsoon", es: { m: "Monzónicos", f: "Monzónicas" }, ko: "몬순의" },
    { key: "showery", en: "Showery", es: { m: "Chubascosos", f: "Chubascosas" }, ko: "소나기같은" },
    { key: "wintry", en: "Wintry", es: { m: "Invernales", f: "Invernales" }, ko: "겨울같은" },
    { key: "summery", en: "Summery", es: { m: "Veraniegos", f: "Veraniegas" }, ko: "여름같은" },
    { key: "autumnal", en: "Autumnal", es: { m: "Otoñales", f: "Otoñales" }, ko: "가을같은" },
    { key: "springlike", en: "Springlike", es: { m: "Primaverales", f: "Primaverales" }, ko: "봄같은" },
    { key: "humid", en: "Humid", es: { m: "Húmedos", f: "Húmedas" }, ko: "습한" },
    { key: "dry", en: "Dry", es: { m: "Secos", f: "Secas" }, ko: "건조한" },
  ],
  time: [
    { key: "new", en: "New", es: { m: "Nuevos", f: "Nuevas" }, ko: "새로운" },
    { key: "old", en: "Old", es: { m: "Viejos", f: "Viejas" }, ko: "오래된" },
    { key: "ancient", en: "Ancient", es: { m: "Antiguos", f: "Antiguas" }, ko: "고대의" },
    { key: "modern", en: "Modern", es: { m: "Modernos", f: "Modernas" }, ko: "현대적인" },
    { key: "young", en: "Young", es: { m: "Jóvenes", f: "Jóvenes" }, ko: "젊은" },
    { key: "fresh", en: "Fresh", es: { m: "Frescos", f: "Frescas" }, ko: "신선한" },
    { key: "early", en: "Early", es: { m: "Tempranos", f: "Tempranas" }, ko: "이른" },
    { key: "late", en: "Late", es: { m: "Tardíos", f: "Tardías" }, ko: "늦은" },
    { key: "future", en: "Future", es: { m: "Futuros", f: "Futuras" }, ko: "미래의" },
    { key: "past", en: "Past", es: { m: "Pasados", f: "Pasadas" }, ko: "과거의" },
    { key: "timeless", en: "Timeless", es: { m: "Atemporales", f: "Atemporales" }, ko: "시대를초월한" },
    { key: "eternal", en: "Eternal", es: { m: "Eternos", f: "Eternas" }, ko: "영원한" },
    { key: "recent", en: "Recent", es: { m: "Recientes", f: "Recientes" }, ko: "최근의" },
    { key: "current", en: "Current", es: { m: "Actuales", f: "Actuales" }, ko: "현재의" },
    { key: "classic", en: "Classic", es: { m: "Clásicos", f: "Clásicas" }, ko: "클래식한" },
    { key: "vintage", en: "Vintage", es: { m: "Vintage", f: "Vintage" }, ko: "빈티지한" },
    { key: "prime", en: "Prime", es: { m: "Óptimos", f: "Óptimas" }, ko: "최상의" },
    { key: "original", en: "Original", es: { m: "Originales", f: "Originales" }, ko: "독창적인" },
    { key: "latest", en: "Latest", es: { m: "Últimos", f: "Últimas" }, ko: "최신의" },
    { key: "aged", en: "Aged", es: { m: "Envejecidos", f: "Envejecidas" }, ko: "숙성된" },
    { key: "emerging", en: "Emerging", es: { m: "Emergentes", f: "Emergentes" }, ko: "떠오르는" },
    { key: "fading", en: "Fading", es: { m: "Desvanecidos", f: "Desvanecidas" }, ko: "사라지는" },
    { key: "retro", en: "Retro", es: { m: "Retro", f: "Retro" }, ko: "레트로" },
    { key: "everlasting", en: "Everlasting", es: { m: "Imperecederos", f: "Imperecederas" }, ko: "영속적인" },
    { key: "seasonal", en: "Seasonal", es: { m: "Estacionales", f: "Estacionales" }, ko: "계절의" },
  ],
  nature: [
    { key: "wild", en: "Wild", es: { m: "Salvajes", f: "Salvajes" }, ko: "야생의" },
    { key: "natural", en: "Natural", es: { m: "Naturales", f: "Naturales" }, ko: "자연의" },
    { key: "organic", en: "Organic", es: { m: "Orgánicos", f: "Orgánicas" }, ko: "유기적인" },
    { key: "earthy", en: "Earthy", es: { m: "Terrosos", f: "Terrosas" }, ko: "흙내나는" },
    { key: "leafy", en: "Leafy", es: { m: "Frondosos", f: "Frondosas" }, ko: "잎이무성한" },
    { key: "floral", en: "Floral", es: { m: "Florales", f: "Florales" }, ko: "꽃의" },
    { key: "wooded", en: "Wooded", es: { m: "Boscosos", f: "Boscosas" }, ko: "숲의" },
    { key: "forested", en: "Forested", es: { m: "Forestales", f: "Forestales" }, ko: "삼림의" },
    { key: "rustic", en: "Rustic", es: { m: "Rústicos", f: "Rústicas" }, ko: "소박한" },
    { key: "blooming", en: "Blooming", es: { m: "Florecientes", f: "Florecientes" }, ko: "피어나는" },
    { key: "fertile", en: "Fertile", es: { m: "Fértiles", f: "Fértiles" }, ko: "비옥한" },
    { key: "lush", en: "Lush", es: { m: "Exuberantes", f: "Exuberantes" }, ko: "울창한" },
    { key: "mossy", en: "Mossy", es: { m: "Musgosos", f: "Musgosas" }, ko: "이끼낀" },
    { key: "grassy", en: "Grassy", es: { m: "Herbosos", f: "Herbosas" }, ko: "풀무성한" },
    { key: "rocky", en: "Rocky", es: { m: "Rocosos", f: "Rocosas" }, ko: "바위투성이의" },
    { key: "sandy", en: "Sandy", es: { m: "Arenosos", f: "Arenosas" }, ko: "모래의" },
    { key: "meadow", en: "Meadow", es: { m: "Praderosos", f: "Praderosas" }, ko: "초원의" },
    { key: "prairie", en: "Prairie", es: { m: "Campestres", f: "Campestres" }, ko: "들판의" },
    { key: "mountain", en: "Mountain", es: { m: "Montañosos", f: "Montañosas" }, ko: "산의" },
    { key: "river", en: "River", es: { m: "Fluviales", f: "Fluviales" }, ko: "강의" },
    { key: "lake", en: "Lake", es: { m: "Lacustres", f: "Lacustres" }, ko: "호수의" },
    { key: "valley", en: "Valley", es: { m: "Valleños", f: "Valleñas" }, ko: "계곡의" },
    { key: "canyon", en: "Canyon", es: { m: "Cañoneros", f: "Cañoneras" }, ko: "협곡의" },
    { key: "jungle", en: "Jungle", es: { m: "Selváticos", f: "Selváticas" }, ko: "밀림의" },
    { key: "desert", en: "Desert", es: { m: "Desérticos", f: "Desérticas" }, ko: "사막의" },
  ],
  luxury: [
    { key: "royal", en: "Royal", es: { m: "Reales", f: "Reales" }, ko: "왕실의" },
    { key: "regal", en: "Regal", es: { m: "Regios", f: "Regias" }, ko: "위엄있는" },
    { key: "elegant", en: "Elegant", es: { m: "Elegantes", f: "Elegantes" }, ko: "우아한" },
    { key: "noble", en: "Noble", es: { m: "Nobles", f: "Nobles" }, ko: "고귀한" },
    { key: "majestic", en: "Majestic", es: { m: "Majestuosos", f: "Majestuosas" }, ko: "장엄한" },
    { key: "grand", en: "Grand", es: { m: "Grandiosos", f: "Grandiosas" }, ko: "웅장한" },
    { key: "opulent", en: "Opulent", es: { m: "Opulentos", f: "Opulentas" }, ko: "화려한" },
    { key: "luxurious", en: "Luxurious", es: { m: "Lujosos", f: "Lujosas" }, ko: "호화로운" },
    { key: "gilded", en: "Gilded", es: { m: "Dorados", f: "Doradas" }, ko: "금박의" },
    { key: "ornate", en: "Ornate", es: { m: "Ornamentados", f: "Ornamentadas" }, ko: "장식적인" },
    { key: "sumptuous", en: "Sumptuous", es: { m: "Suntuosos", f: "Suntuosas" }, ko: "호화로운" },
    { key: "aristocratic", en: "Aristocratic", es: { m: "Aristocráticos", f: "Aristocráticas" }, ko: "귀족적인" },
    { key: "imperial", en: "Imperial", es: { m: "Imperiales", f: "Imperiales" }, ko: "황제의" },
    { key: "sovereign", en: "Sovereign", es: { m: "Soberanos", f: "Soberanas" }, ko: "군주의" },
    { key: "lavish", en: "Lavish", es: { m: "Fastuosos", f: "Fastuosas" }, ko: "사치스러운" },
    { key: "exquisite", en: "Exquisite", es: { m: "Exquisitos", f: "Exquisitas" }, ko: "정교한" },
    { key: "refined", en: "Refined", es: { m: "Refinados", f: "Refinadas" }, ko: "세련된" },
    { key: "prestigious", en: "Prestigious", es: { m: "Prestigiosos", f: "Prestigiosas" }, ko: "명망있는" },
    { key: "highborn", en: "Highborn", es: { m: "Nobiliarios", f: "Nobiliarias" }, ko: "명문가의" },
    { key: "courtly", en: "Courtly", es: { m: "Cortesanos", f: "Cortesanas" }, ko: "궁정의" },
    { key: "palatial", en: "Palatial", es: { m: "Palaciegos", f: "Palaciegas" }, ko: "궁전같은" },
    { key: "stately", en: "Stately", es: { m: "Solemnes", f: "Solemnes" }, ko: "위풍당당한" },
    { key: "crowned", en: "Crowned", es: { m: "Coronados", f: "Coronadas" }, ko: "왕관의" },
    { key: "splendid", en: "Splendid", es: { m: "Espléndidos", f: "Espléndidas" }, ko: "찬란한" },
    { key: "princely", en: "Princely", es: { m: "Principescos", f: "Principescas" }, ko: "왕자다운" },
  ],
  tech: [
    { key: "digital", en: "Digital", es: { m: "Digitales", f: "Digitales" }, ko: "디지털" },
    { key: "virtual", en: "Virtual", es: { m: "Virtuales", f: "Virtuales" }, ko: "가상" },
    { key: "cyber", en: "Cyber", es: { m: "Cibernéticos", f: "Cibernéticas" }, ko: "사이버" },
    { key: "binary", en: "Binary", es: { m: "Binarios", f: "Binarias" }, ko: "이진의" },
    { key: "electric", en: "Electric", es: { m: "Eléctricos", f: "Eléctricas" }, ko: "전기의" },
    { key: "electronic", en: "Electronic", es: { m: "Electrónicos", f: "Electrónicas" }, ko: "전자식" },
    { key: "coded", en: "Coded", es: { m: "Codificados", f: "Codificadas" }, ko: "코딩된" },
    { key: "networked", en: "Networked", es: { m: "Conectados", f: "Conectadas" }, ko: "네트워크된" },
    { key: "automated", en: "Automated", es: { m: "Automatizados", f: "Automatizadas" }, ko: "자동화된" },
    { key: "robotic", en: "Robotic", es: { m: "Robóticos", f: "Robóticas" }, ko: "로봇의" },
    { key: "synthetic", en: "Synthetic", es: { m: "Sintéticos", f: "Sintéticas" }, ko: "인공의" },
    { key: "wired", en: "Wired", es: { m: "Cableados", f: "Cableadas" }, ko: "유선의" },
    { key: "wireless", en: "Wireless", es: { m: "Inalámbricos", f: "Inalámbricas" }, ko: "무선의" },
    { key: "pixelated", en: "Pixelated", es: { m: "Pixelados", f: "Pixeladas" }, ko: "픽셀화된" },
    { key: "holographic", en: "Holographic", es: { m: "Holográficos", f: "Holográficas" }, ko: "홀로그램의" },
    { key: "modular", en: "Modular", es: { m: "Modulares", f: "Modulares" }, ko: "모듈형의" },
    { key: "integrated", en: "Integrated", es: { m: "Integrados", f: "Integradas" }, ko: "통합된" },
    { key: "upgraded", en: "Upgraded", es: { m: "Mejorados", f: "Mejoradas" }, ko: "업그레이드된" },
    { key: "smart", en: "Smart", es: { m: "Inteligentes", f: "Inteligentes" }, ko: "스마트한" },
    { key: "nano", en: "Nano", es: { m: "Nano", f: "Nano" }, ko: "나노" },
    { key: "quantum", en: "Quantum", es: { m: "Cuánticos", f: "Cuánticas" }, ko: "양자의" },
    { key: "programmable", en: "Programmable", es: { m: "Programables", f: "Programables" }, ko: "프로그래밍가능한" },
    { key: "augmented", en: "Augmented", es: { m: "Aumentados", f: "Aumentadas" }, ko: "증강된" },
    { key: "encoded", en: "Encoded", es: { m: "Cifrados", f: "Cifradas" }, ko: "인코딩된" },
    { key: "algorithmic", en: "Algorithmic", es: { m: "Algorítmicos", f: "Algorítmicas" }, ko: "알고리즘의" },
  ],
  precision: [
    { key: "precise", en: "Precise", es: { m: "Precisos", f: "Precisas" }, ko: "정밀한" },
    { key: "accurate", en: "Accurate", es: { m: "Certeros", f: "Certeras" }, ko: "정확한" },
    { key: "exact", en: "Exact", es: { m: "Exactos", f: "Exactas" }, ko: "정확한" },
    { key: "clean", en: "Clean", es: { m: "Limpios", f: "Limpias" }, ko: "깨끗한" },
    { key: "clear", en: "Clear", es: { m: "Claros", f: "Claras" }, ko: "선명한" },
    { key: "crisp", en: "Crisp", es: { m: "Nítidos", f: "Nítidas" }, ko: "또렷한" },
    { key: "neat", en: "Neat", es: { m: "Ordenados", f: "Ordenadas" }, ko: "단정한" },
    { key: "polished", en: "Polished", es: { m: "Pulidos", f: "Pulidas" }, ko: "다듬어진" },
    { key: "pure", en: "Pure", es: { m: "Puros", f: "Puras" }, ko: "순수한" },
    { key: "perfect", en: "Perfect", es: { m: "Perfectos", f: "Perfectas" }, ko: "완벽한" },
    { key: "flawless", en: "Flawless", es: { m: "Impecables", f: "Impecables" }, ko: "흠없는" },
    { key: "pristine", en: "Pristine", es: { m: "Inmaculados", f: "Inmaculadas" }, ko: "흠결없는" },
    { key: "orderly", en: "Orderly", es: { m: "Metódicos", f: "Metódicas" }, ko: "정돈된" },
    { key: "detailed", en: "Detailed", es: { m: "Detallados", f: "Detalladas" }, ko: "상세한" },
    { key: "focused", en: "Focused", es: { m: "Enfocados", f: "Enfocadas" }, ko: "집중된" },
    { key: "reliable", en: "Reliable", es: { m: "Confiables", f: "Confiables" }, ko: "믿음직한" },
    { key: "consistent", en: "Consistent", es: { m: "Consistentes", f: "Consistentes" }, ko: "일관된" },
    { key: "calibrated", en: "Calibrated", es: { m: "Calibrados", f: "Calibradas" }, ko: "보정된" },
    { key: "measured", en: "Measured", es: { m: "Medidos", f: "Medidas" }, ko: "측정된" },
    { key: "tuned", en: "Tuned", es: { m: "Afinados", f: "Afinadas" }, ko: "조율된" },
    { key: "aligned", en: "Aligned", es: { m: "Alineados", f: "Alineadas" }, ko: "정렬된" },
    { key: "standard", en: "Standard", es: { m: "Estándar", f: "Estándar" }, ko: "표준의" },
    { key: "fine", en: "Fine", es: { m: "Finos", f: "Finas" }, ko: "섬세한" },
    { key: "meticulous", en: "Meticulous", es: { m: "Meticulosos", f: "Meticulosas" }, ko: "꼼꼼한" },
    { key: "systematic", en: "Systematic", es: { m: "Sistemáticos", f: "Sistemáticas" }, ko: "체계적인" },
  ],
  mystery: [
    { key: "mystic", en: "Mystic", es: { m: "Místicos", f: "Místicas" }, ko: "신비한" },
    { key: "mysterious", en: "Mysterious", es: { m: "Misteriosos", f: "Misteriosas" }, ko: "미스터리한" },
    { key: "secret", en: "Secret", es: { m: "Secretos", f: "Secretas" }, ko: "비밀의" },
    { key: "hidden", en: "Hidden", es: { m: "Ocultos", f: "Ocultas" }, ko: "숨겨진" },
    { key: "enchanted", en: "Enchanted", es: { m: "Encantados", f: "Encantadas" }, ko: "마법에걸린" },
    { key: "magical", en: "Magical", es: { m: "Mágicos", f: "Mágicas" }, ko: "마법의" },
    { key: "arcane", en: "Arcane", es: { m: "Arcanos", f: "Arcanas" }, ko: "비전의" },
    { key: "occult", en: "Occult", es: { m: "Esotéricos", f: "Esotéricas" }, ko: "오컬트의" },
    { key: "shadowy", en: "Shadowy", es: { m: "Sombríos", f: "Sombrías" }, ko: "어두운" },
    { key: "phantom", en: "Phantom", es: { m: "Fantasmales", f: "Fantasmales" }, ko: "유령같은" },
    { key: "ghostly", en: "Ghostly", es: { m: "Fantasmales", f: "Fantasmales" }, ko: "유령의" },
    { key: "spectral", en: "Spectral", es: { m: "Espectrales", f: "Espectrales" }, ko: "영적인" },
    { key: "enigmatic", en: "Enigmatic", es: { m: "Enigmáticos", f: "Enigmáticas" }, ko: "수수께끼같은" },
    { key: "cryptic", en: "Cryptic", es: { m: "Crípticos", f: "Crípticas" }, ko: "암호같은" },
    { key: "veiled", en: "Veiled", es: { m: "Velados", f: "Veladas" }, ko: "베일에가린" },
    { key: "forbidden", en: "Forbidden", es: { m: "Prohibidos", f: "Prohibidas" }, ko: "금단의" },
    { key: "sacred", en: "Sacred", es: { m: "Sagrados", f: "Sagradas" }, ko: "신성한" },
    { key: "cursed", en: "Cursed", es: { m: "Malditos", f: "Malditas" }, ko: "저주받은" },
    { key: "haunted", en: "Haunted", es: { m: "Embrujados", f: "Embrujadas" }, ko: "귀신들린" },
    { key: "spellbound", en: "Spellbound", es: { m: "Hechizados", f: "Hechizadas" }, ko: "매혹된" },
    { key: "fabled", en: "Fabled", es: { m: "Legendarios", f: "Legendarias" }, ko: "전설의" },
    { key: "mythic", en: "Mythic", es: { m: "Míticos", f: "Míticas" }, ko: "신화의" },
    { key: "rune", en: "Rune", es: { m: "Rúnicos", f: "Rúnicas" }, ko: "룬의" },
    { key: "dreamlike", en: "Dreamlike", es: { m: "Oníricos", f: "Oníricas" }, ko: "꿈같은" },
    { key: "otherworldly", en: "Otherworldly", es: { m: "Sobrenaturales", f: "Sobrenaturales" }, ko: "이세계의" },
  ],
  urban: [
    { key: "urban", en: "Urban", es: { m: "Urbanos", f: "Urbanas" }, ko: "도시의" },
    { key: "metropolitan", en: "Metropolitan", es: { m: "Metropolitanos", f: "Metropolitanas" }, ko: "대도시의" },
    { key: "industrial", en: "Industrial", es: { m: "Industriales", f: "Industriales" }, ko: "산업의" },
    { key: "suburban", en: "Suburban", es: { m: "Suburbanos", f: "Suburbanas" }, ko: "교외의" },
    { key: "coastal", en: "Coastal", es: { m: "Costeros", f: "Costeras" }, ko: "해안의" },
    { key: "harbor", en: "Harbor", es: { m: "Portuarios", f: "Portuarias" }, ko: "항구의" },
    { key: "riverside", en: "Riverside", es: { m: "Ribereños", f: "Ribereñas" }, ko: "강변의" },
    { key: "market", en: "Market", es: { m: "Mercantiles", f: "Mercantiles" }, ko: "시장의" },
    { key: "central", en: "Central", es: { m: "Centrales", f: "Centrales" }, ko: "중심의" },
    { key: "outer", en: "Outer", es: { m: "Externos", f: "Externas" }, ko: "외곽의" },
    { key: "inner", en: "Inner", es: { m: "Internos", f: "Internas" }, ko: "내부의" },
    { key: "downtown", en: "Downtown", es: { m: "Céntricos", f: "Céntricas" }, ko: "도심의" },
    { key: "uptown", en: "Uptown", es: { m: "Altos", f: "Altas" }, ko: "업타운" },
    { key: "underground", en: "Underground", es: { m: "Subterráneos", f: "Subterráneas" }, ko: "지하의" },
    { key: "street", en: "Street", es: { m: "Callejeros", f: "Callejeras" }, ko: "거리의" },
    { key: "district", en: "District", es: { m: "Distritales", f: "Distritales" }, ko: "구역의" },
    { key: "neighborhood", en: "Neighborhood", es: { m: "Vecinales", f: "Vecinales" }, ko: "동네의" },
    { key: "bridge", en: "Bridge", es: { m: "Puenteros", f: "Puenteras" }, ko: "다리의" },
    { key: "avenue", en: "Avenue", es: { m: "Avenidos", f: "Avenidas" }, ko: "대로의" },
    { key: "boulevard", en: "Boulevard", es: { m: "Boulevard", f: "Boulevard" }, ko: "대로의" },
    { key: "station", en: "Station", es: { m: "Terminales", f: "Terminales" }, ko: "역의" },
    { key: "alley", en: "Alley", es: { m: "Callejoneros", f: "Callejoneras" }, ko: "골목의" },
    { key: "rooftop", en: "Rooftop", es: { m: "Azoteas", f: "Azoteas" }, ko: "옥상의" },
    { key: "waterfront", en: "Waterfront", es: { m: "Costaneros", f: "Costaneras" }, ko: "수변의" },
    { key: "skyline", en: "Skyline", es: { m: "Horizontales", f: "Horizontales" }, ko: "스카이라인의" },
  ],
  rarity: [
    { key: "rare", en: "Rare", es: { m: "Raros", f: "Raras" }, ko: "희귀한" },
    { key: "common", en: "Common", es: { m: "Comunes", f: "Comunes" }, ko: "흔한" },
    { key: "precious", en: "Precious", es: { m: "Preciosos", f: "Preciosas" }, ko: "소중한" },
    { key: "valuable", en: "Valuable", es: { m: "Valiosos", f: "Valiosas" }, ko: "가치있는" },
    { key: "priceless", en: "Priceless", es: { m: "Invaluables", f: "Invaluables" }, ko: "값진" },
    { key: "cheap", en: "Cheap", es: { m: "Baratos", f: "Baratas" }, ko: "저렴한" },
    { key: "costly", en: "Costly", es: { m: "Costosos", f: "Costosas" }, ko: "값비싼" },
    { key: "worthy", en: "Worthy", es: { m: "Dignos", f: "Dignas" }, ko: "값어치있는" },
    { key: "exclusive", en: "Exclusive", es: { m: "Exclusivos", f: "Exclusivas" }, ko: "독점적인" },
    { key: "limited", en: "Limited", es: { m: "Limitados", f: "Limitadas" }, ko: "한정된" },
    { key: "scarce", en: "Scarce", es: { m: "Escasos", f: "Escasas" }, ko: "부족한" },
    { key: "abundant", en: "Abundant", es: { m: "Abundantes", f: "Abundantes" }, ko: "풍부한" },
    { key: "rich", en: "Rich", es: { m: "Ricos", f: "Ricas" }, ko: "풍성한" },
    { key: "deluxe", en: "Deluxe", es: { m: "De lujo", f: "De lujo" }, ko: "디럭스한" },
    { key: "premium", en: "Premium", es: { m: "Premium", f: "Premium" }, ko: "프리미엄" },
    { key: "select", en: "Select", es: { m: "Selectos", f: "Selectas" }, ko: "엄선된" },
    { key: "choice", en: "Choice", es: { m: "Elegidos", f: "Elegidas" }, ko: "선택된" },
    { key: "special", en: "Special", es: { m: "Especiales", f: "Especiales" }, ko: "특별한" },
    { key: "elite", en: "Elite", es: { m: "Elite", f: "Elite" }, ko: "엘리트" },
    { key: "regular", en: "Regular", es: { m: "Regulares", f: "Regulares" }, ko: "보통의" },
    { key: "ordinary", en: "Ordinary", es: { m: "Ordinarios", f: "Ordinarias" }, ko: "평범한" },
    { key: "modest", en: "Modest", es: { m: "Modestos", f: "Modestas" }, ko: "소박한" },
    { key: "basic", en: "Basic", es: { m: "Básicos", f: "Básicas" }, ko: "기본의" },
    { key: "budget", en: "Budget", es: { m: "Económicos", f: "Económicas" }, ko: "예산형" },
    { key: "everyday", en: "Everyday", es: { m: "Cotidianos", f: "Cotidianas" }, ko: "일상의" },
  ]
};

type NounToken = {
  key: string;
  en: string;
  es: { gender: string; plural: string };
  ko: string;
  collective?: string;
  needsDeul?: boolean;
};

type NounCategoryDef = {
  collective?: string;
  tokens: NounToken[];
};

const NOUN_CATEGORY_DEFS: Record<string, NounCategoryDef> = {
  animals: {
    collective: "무리",
    tokens: [
      { key: "wolves", en: "Wolves", es: { gender: "m", plural: "Lobos" }, ko: "늑대" },
      { key: "foxes", en: "Foxes", es: { gender: "m", plural: "Zorros" }, ko: "여우" },
      { key: "lions", en: "Lions", es: { gender: "m", plural: "Leones" }, ko: "사자" },
      { key: "tigers", en: "Tigers", es: { gender: "m", plural: "Tigres" }, ko: "호랑이" },
      { key: "bears", en: "Bears", es: { gender: "m", plural: "Osos" }, ko: "곰" },
      { key: "horses", en: "Horses", es: { gender: "m", plural: "Caballos" }, ko: "말" },
      { key: "dogs", en: "Dogs", es: { gender: "m", plural: "Perros" }, ko: "개" },
      { key: "cats", en: "Cats", es: { gender: "m", plural: "Gatos" }, ko: "고양이" },
      { key: "rabbits", en: "Rabbits", es: { gender: "m", plural: "Conejos" }, ko: "토끼" },
      { key: "deer", en: "Deer", es: { gender: "m", plural: "Ciervos" }, ko: "사슴" },
      { key: "goats", en: "Goats", es: { gender: "f", plural: "Cabras" }, ko: "염소" },
      { key: "sheep", en: "Sheep", es: { gender: "f", plural: "Ovejas" }, ko: "양" },
      { key: "cows", en: "Cows", es: { gender: "f", plural: "Vacas" }, ko: "소" },
      { key: "bulls", en: "Bulls", es: { gender: "m", plural: "Toros" }, ko: "황소" },
      { key: "pigs", en: "Pigs", es: { gender: "m", plural: "Cerdos" }, ko: "돼지" },
      { key: "monkeys", en: "Monkeys", es: { gender: "m", plural: "Monos" }, ko: "원숭이" },
      { key: "elephants", en: "Elephants", es: { gender: "m", plural: "Elefantes" }, ko: "코끼리" },
      { key: "giraffes", en: "Giraffes", es: { gender: "f", plural: "Jirafas" }, ko: "기린" },
      { key: "zebras", en: "Zebras", es: { gender: "f", plural: "Cebras" }, ko: "얼룩말" },
      { key: "panthers", en: "Panthers", es: { gender: "f", plural: "Panteras" }, ko: "팬서" },
      { key: "leopards", en: "Leopards", es: { gender: "m", plural: "Leopardos" }, ko: "표범" },
      { key: "jaguars", en: "Jaguars", es: { gender: "m", plural: "Jaguares" }, ko: "재규어" },
      { key: "rhinos", en: "Rhinos", es: { gender: "m", plural: "Rinocerontes" }, ko: "코뿔소" },
      { key: "hippos", en: "Hippos", es: { gender: "m", plural: "Hipopótamos" }, ko: "하마" },
      { key: "camels", en: "Camels", es: { gender: "m", plural: "Camellos" }, ko: "낙타" },
      { key: "pandas", en: "Pandas", es: { gender: "m", plural: "Pandas" }, ko: "판다" },
      { key: "otters", en: "Otters", es: { gender: "f", plural: "Nutrias" }, ko: "수달" },
      { key: "badgers", en: "Badgers", es: { gender: "m", plural: "Tejones" }, ko: "오소리" },
      { key: "gazelles", en: "Gazelles", es: { gender: "f", plural: "Gacelas" }, ko: "가젤" },
      { key: "lemurs", en: "Lemurs", es: { gender: "m", plural: "Lémures" }, ko: "여우원숭이" }
    ]
  },
  birds: {
    collective: "떼",
    tokens: [
      { key: "eagles", en: "Eagles", es: { gender: "f", plural: "Águilas" }, ko: "독수리" },
      { key: "hawks", en: "Hawks", es: { gender: "m", plural: "Halcones" }, ko: "매" },
      { key: "condors", en: "Condors", es: { gender: "m", plural: "Cóndores" }, ko: "콘도르" },
      { key: "owls", en: "Owls", es: { gender: "m", plural: "Búhos" }, ko: "부엉이" },
      { key: "ravens", en: "Ravens", es: { gender: "m", plural: "Cuervos" }, ko: "큰까마귀" },
      { key: "crows", en: "Crows", es: { gender: "f", plural: "Cornejas" }, ko: "까마귀" },
      { key: "sparrows", en: "Sparrows", es: { gender: "m", plural: "Gorriones" }, ko: "참새" },
      { key: "swans", en: "Swans", es: { gender: "m", plural: "Cisnes" }, ko: "백조" },
      { key: "geese", en: "Geese", es: { gender: "m", plural: "Gansos" }, ko: "거위" },
      { key: "ducks", en: "Ducks", es: { gender: "m", plural: "Patos" }, ko: "오리" },
      { key: "pigeons", en: "Pigeons", es: { gender: "f", plural: "Palomas" }, ko: "비둘기" },
      { key: "doves", en: "Doves", es: { gender: "f", plural: "Tórtolas" }, ko: "멧비둘기" },
      { key: "robins", en: "Robins", es: { gender: "m", plural: "Petirrojos" }, ko: "울새" },
      { key: "larks", en: "Larks", es: { gender: "f", plural: "Alondras" }, ko: "종달새" },
      { key: "woodpeckers", en: "Woodpeckers", es: { gender: "m", plural: "Carpinteros" }, ko: "딱따구리" },
      { key: "hummingbirds", en: "Hummingbirds", es: { gender: "m", plural: "Colibríes" }, ko: "벌새" },
      { key: "peacocks", en: "Peacocks", es: { gender: "m", plural: "Pavos reales" }, ko: "공작" },
      { key: "parrots", en: "Parrots", es: { gender: "m", plural: "Loros" }, ko: "앵무새" },
      { key: "cranes", en: "Cranes", es: { gender: "f", plural: "Grullas" }, ko: "두루미" },
      { key: "herons", en: "Herons", es: { gender: "f", plural: "Garzas" }, ko: "왜가리" },
      { key: "storks", en: "Storks", es: { gender: "f", plural: "Cigüeñas" }, ko: "황새" },
      { key: "gulls", en: "Gulls", es: { gender: "f", plural: "Gaviotas" }, ko: "갈매기" },
      { key: "finches", en: "Finches", es: { gender: "m", plural: "Pinzones" }, ko: "되새" },
      { key: "thrushes", en: "Thrushes", es: { gender: "m", plural: "Zorzales" }, ko: "지빠귀" },
      { key: "cardinals", en: "Cardinals", es: { gender: "m", plural: "Cardenales" }, ko: "홍관조" }
    ]
  },
  sea: {
    collective: "떼",
    tokens: [
      { key: "sharks", en: "Sharks", es: { gender: "m", plural: "Tiburones" }, ko: "상어" },
      { key: "whales", en: "Whales", es: { gender: "f", plural: "Ballenas" }, ko: "고래" },
      { key: "dolphins", en: "Dolphins", es: { gender: "m", plural: "Delfines" }, ko: "돌고래" },
      { key: "octopuses", en: "Octopuses", es: { gender: "m", plural: "Pulpos" }, ko: "문어" },
      { key: "squids", en: "Squids", es: { gender: "m", plural: "Calamares" }, ko: "오징어" },
      { key: "crabs", en: "Crabs", es: { gender: "m", plural: "Cangrejos" }, ko: "게" },
      { key: "lobsters", en: "Lobsters", es: { gender: "f", plural: "Langostas" }, ko: "바닷가재" },
      { key: "shrimp", en: "Shrimp", es: { gender: "m", plural: "Camarones" }, ko: "새우" },
      { key: "jellyfish", en: "Jellyfish", es: { gender: "f", plural: "Medusas" }, ko: "해파리" },
      { key: "starfish", en: "Starfish", es: { gender: "f", plural: "Estrellas de mar" }, ko: "불가사리" },
      { key: "seahorses", en: "Seahorses", es: { gender: "m", plural: "Caballitos de mar" }, ko: "해마" },
      { key: "seals", en: "Seals", es: { gender: "f", plural: "Focas" }, ko: "물개" },
      { key: "walruses", en: "Walruses", es: { gender: "f", plural: "Morsas" }, ko: "바다코끼리" },
      { key: "sea_turtles", en: "Sea Turtles", es: { gender: "f", plural: "Tortugas marinas" }, ko: "바다거북" },
      { key: "rays", en: "Rays", es: { gender: "f", plural: "Rayas" }, ko: "가오리" },
      { key: "eels", en: "Eels", es: { gender: "f", plural: "Anguilas" }, ko: "장어" },
      { key: "clams", en: "Clams", es: { gender: "f", plural: "Almejas" }, ko: "조개" },
      { key: "oysters", en: "Oysters", es: { gender: "f", plural: "Ostras" }, ko: "굴" },
      { key: "mussels", en: "Mussels", es: { gender: "m", plural: "Mejillones" }, ko: "홍합" },
      { key: "scallops", en: "Scallops", es: { gender: "f", plural: "Vieiras" }, ko: "가리비" },
      { key: "mantas", en: "Mantas", es: { gender: "f", plural: "Mantas" }, ko: "만타가오리" },
      { key: "orcas", en: "Orcas", es: { gender: "f", plural: "Orcas" }, ko: "범고래" },
      { key: "anglerfish", en: "Anglerfish", es: { gender: "m", plural: "Peces rape" }, ko: "아귀" },
      { key: "swordfish", en: "Swordfish", es: { gender: "m", plural: "Peces espada" }, ko: "황새치" },
      { key: "corals", en: "Corals", es: { gender: "m", plural: "Corales" }, ko: "산호" }
    ]
  },
  insects: {
    collective: "떼",
    tokens: [
      { key: "ants", en: "Ants", es: { gender: "f", plural: "Hormigas" }, ko: "개미" },
      { key: "bees", en: "Bees", es: { gender: "f", plural: "Abejas" }, ko: "벌" },
      { key: "wasps", en: "Wasps", es: { gender: "f", plural: "Avispas" }, ko: "쌍살벌" },
      { key: "hornets", en: "Hornets", es: { gender: "m", plural: "Avispones" }, ko: "왕말벌" },
      { key: "butterflies", en: "Butterflies", es: { gender: "f", plural: "Mariposas" }, ko: "나비" },
      { key: "moths", en: "Moths", es: { gender: "f", plural: "Polillas" }, ko: "나방" },
      { key: "beetles", en: "Beetles", es: { gender: "m", plural: "Escarabajos" }, ko: "딱정벌레" },
      { key: "ladybugs", en: "Ladybugs", es: { gender: "f", plural: "Mariquitas" }, ko: "무당벌레" },
      { key: "spiders", en: "Spiders", es: { gender: "f", plural: "Arañas" }, ko: "거미" },
      { key: "flies", en: "Flies", es: { gender: "f", plural: "Moscas" }, ko: "파리" },
      { key: "mosquitoes", en: "Mosquitoes", es: { gender: "m", plural: "Mosquitos" }, ko: "모기" },
      { key: "dragonflies", en: "Dragonflies", es: { gender: "f", plural: "Libélulas" }, ko: "잠자리" },
      { key: "fireflies", en: "Fireflies", es: { gender: "f", plural: "Luciérnagas" }, ko: "반딧불이" },
      { key: "crickets", en: "Crickets", es: { gender: "m", plural: "Grillos" }, ko: "귀뚜라미" },
      { key: "grasshoppers", en: "Grasshoppers", es: { gender: "m", plural: "Saltamontes" }, ko: "메뚜기" },
      { key: "caterpillars", en: "Caterpillars", es: { gender: "f", plural: "Orugas" }, ko: "애벌레" },
      { key: "snails", en: "Snails", es: { gender: "m", plural: "Caracoles" }, ko: "달팽이" },
      { key: "slugs", en: "Slugs", es: { gender: "f", plural: "Babosas" }, ko: "민달팽이" },
      { key: "worms", en: "Worms", es: { gender: "m", plural: "Gusanos" }, ko: "지렁이" },
      { key: "centipedes", en: "Centipedes", es: { gender: "m", plural: "Ciempiés" }, ko: "지네" },
      { key: "millipedes", en: "Millipedes", es: { gender: "m", plural: "Milpiés" }, ko: "노래기" },
      { key: "fleas", en: "Fleas", es: { gender: "f", plural: "Pulgas" }, ko: "벼룩" },
      { key: "ticks", en: "Ticks", es: { gender: "f", plural: "Garrapatas" }, ko: "진드기" },
      { key: "roaches", en: "Roaches", es: { gender: "f", plural: "Cucarachas" }, ko: "바퀴벌레" },
      { key: "scorpions", en: "Scorpions", es: { gender: "m", plural: "Escorpiones" }, ko: "전갈" }
    ]
  },
  flowers: {
    collective: "다발",
    tokens: [
      { key: "roses", en: "Roses", es: { gender: "f", plural: "Rosas" }, ko: "장미" },
      { key: "lilies", en: "Lilies", es: { gender: "m", plural: "Lirios" }, ko: "백합" },
      { key: "tulips", en: "Tulips", es: { gender: "m", plural: "Tulipanes" }, ko: "튤립" },
      { key: "daisies", en: "Daisies", es: { gender: "f", plural: "Margaritas" }, ko: "데이지" },
      { key: "sunflowers", en: "Sunflowers", es: { gender: "m", plural: "Girasoles" }, ko: "해바라기" },
      { key: "orchids", en: "Orchids", es: { gender: "f", plural: "Orquídeas" }, ko: "난초" },
      { key: "peonies", en: "Peonies", es: { gender: "f", plural: "Peonías" }, ko: "작약" },
      { key: "irises", en: "Irises", es: { gender: "m", plural: "Iris" }, ko: "붓꽃" },
      { key: "daffodils", en: "Daffodils", es: { gender: "m", plural: "Narcisos" }, ko: "수선화" },
      { key: "poppies", en: "Poppies", es: { gender: "f", plural: "Amapolas" }, ko: "양귀비" },
      { key: "violets", en: "Violets", es: { gender: "f", plural: "Violetas" }, ko: "제비꽃" },
      { key: "marigolds", en: "Marigolds", es: { gender: "f", plural: "Caléndulas" }, ko: "금잔화" },
      { key: "chrysanthemums", en: "Chrysanthemums", es: { gender: "m", plural: "Crisantemos" }, ko: "국화" },
      { key: "carnations", en: "Carnations", es: { gender: "m", plural: "Claveles" }, ko: "카네이션" },
      { key: "hydrangeas", en: "Hydrangeas", es: { gender: "f", plural: "Hortensias" }, ko: "수국" },
      { key: "magnolias", en: "Magnolias", es: { gender: "f", plural: "Magnolias" }, ko: "목련" },
      { key: "camellias", en: "Camellias", es: { gender: "f", plural: "Camelias" }, ko: "동백꽃" },
      { key: "jasmines", en: "Jasmines", es: { gender: "m", plural: "Jazmines" }, ko: "자스민" },
      { key: "gardenias", en: "Gardenias", es: { gender: "f", plural: "Gardenias" }, ko: "치자꽃" },
      { key: "lotuses", en: "Lotuses", es: { gender: "m", plural: "Lotos" }, ko: "연꽃" },
      { key: "hibiscus", en: "Hibiscus", es: { gender: "m", plural: "Hibiscos" }, ko: "히비스커스" },
      { key: "azaleas", en: "Azaleas", es: { gender: "f", plural: "Azaleas" }, ko: "진달래" },
      { key: "begonias", en: "Begonias", es: { gender: "f", plural: "Begonias" }, ko: "베고니아" },
      { key: "primroses", en: "Primroses", es: { gender: "f", plural: "Prímulas" }, ko: "앵초" },
      { key: "lilacs", en: "Lilacs", es: { gender: "f", plural: "Lilas" }, ko: "라일락" }
    ]
  },
  plants: {
    collective: "덤불",
    tokens: [
      { key: "mints", en: "Mints", es: { gender: "f", plural: "Mentas" }, ko: "민트" },
      { key: "basils", en: "Basils", es: { gender: "f", plural: "Albahacas" }, ko: "바질" },
      { key: "sages", en: "Sages", es: { gender: "f", plural: "Salvias" }, ko: "세이지" },
      { key: "thymes", en: "Thymes", es: { gender: "m", plural: "Tomillos" }, ko: "타임" },
      { key: "rosemaries", en: "Rosemaries", es: { gender: "m", plural: "Romeros" }, ko: "로즈마리" },
      { key: "parsleys", en: "Parsleys", es: { gender: "m", plural: "Perejiles" }, ko: "파슬리" },
      { key: "cilantros", en: "Cilantros", es: { gender: "m", plural: "Cilantros" }, ko: "고수" },
      { key: "oreganos", en: "Oreganos", es: { gender: "m", plural: "Oréganos" }, ko: "오레가노" },
      { key: "dills", en: "Dills", es: { gender: "m", plural: "Eneldos" }, ko: "딜" },
      { key: "chives", en: "Chives", es: { gender: "m", plural: "Cebollinos" }, ko: "부추" },
      { key: "fennels", en: "Fennels", es: { gender: "m", plural: "Hinojos" }, ko: "회향" },
      { key: "lavenders", en: "Lavenders", es: { gender: "f", plural: "Lavandas" }, ko: "라벤더" },
      { key: "aloes", en: "Aloes", es: { gender: "m", plural: "Áloes" }, ko: "알로에" },
      { key: "ivies", en: "Ivies", es: { gender: "f", plural: "Hiedras" }, ko: "담쟁이덩굴" },
      { key: "ferns", en: "Ferns", es: { gender: "m", plural: "Helechos" }, ko: "고사리" },
      { key: "mosses", en: "Mosses", es: { gender: "m", plural: "Musgos" }, ko: "이끼" },
      { key: "grasses", en: "Grasses", es: { gender: "m", plural: "Pastos" }, ko: "풀" },
      { key: "reeds", en: "Reeds", es: { gender: "m", plural: "Juncos" }, ko: "갈대" },
      { key: "vines", en: "Vines", es: { gender: "f", plural: "Enredaderas" }, ko: "덩굴" },
      { key: "bamboos", en: "Bamboos", es: { gender: "m", plural: "Bambúes" }, ko: "대나무" },
      { key: "cacti", en: "Cacti", es: { gender: "m", plural: "Cactus" }, ko: "선인장" },
      { key: "succulents", en: "Succulents", es: { gender: "f", plural: "Suculentas" }, ko: "다육이" },
      { key: "sprouts", en: "Sprouts", es: { gender: "m", plural: "Brotes" }, ko: "새싹" },
      { key: "seedlings", en: "Seedlings", es: { gender: "f", plural: "Plántulas" }, ko: "묘목" },
      { key: "leaves", en: "Leaves", es: { gender: "f", plural: "Hojas" }, ko: "잎" }
    ]
  },
  trees: {
    collective: "숲",
    tokens: [
      { key: "oaks", en: "Oaks", es: { gender: "m", plural: "Robles" }, ko: "참나무" },
      { key: "pines", en: "Pines", es: { gender: "m", plural: "Pinos" }, ko: "소나무" },
      { key: "maples", en: "Maples", es: { gender: "m", plural: "Arces" }, ko: "단풍나무" },
      { key: "birches", en: "Birches", es: { gender: "m", plural: "Abedules" }, ko: "자작나무" },
      { key: "cedars", en: "Cedars", es: { gender: "m", plural: "Cedros" }, ko: "삼나무" },
      { key: "spruces", en: "Spruces", es: { gender: "f", plural: "Piceas" }, ko: "가문비나무" },
      { key: "firs", en: "Firs", es: { gender: "m", plural: "Abetos" }, ko: "전나무" },
      { key: "willows", en: "Willows", es: { gender: "m", plural: "Sauces" }, ko: "버드나무" },
      { key: "elms", en: "Elms", es: { gender: "m", plural: "Olmos" }, ko: "느릅나무" },
      { key: "ashes", en: "Ashes", es: { gender: "m", plural: "Fresnos" }, ko: "물푸레나무" },
      { key: "beeches", en: "Beeches", es: { gender: "f", plural: "Hayas" }, ko: "너도밤나무" },
      { key: "poplars", en: "Poplars", es: { gender: "m", plural: "Álamos" }, ko: "포플러" },
      { key: "cypresses", en: "Cypresses", es: { gender: "m", plural: "Cipreses" }, ko: "측백나무" },
      { key: "palms", en: "Palms", es: { gender: "f", plural: "Palmas" }, ko: "야자나무" },
      { key: "cherries", en: "Cherries", es: { gender: "m", plural: "Cerezos" }, ko: "벚나무" },
      { key: "apples", en: "Apples", es: { gender: "m", plural: "Manzanos" }, ko: "사과나무" },
      { key: "olives", en: "Olives", es: { gender: "m", plural: "Olivos" }, ko: "올리브나무" },
      { key: "lemons", en: "Lemons", es: { gender: "m", plural: "Limoneros" }, ko: "레몬나무" },
      { key: "pears", en: "Pears", es: { gender: "m", plural: "Perales" }, ko: "배나무" },
      { key: "plums", en: "Plums", es: { gender: "m", plural: "Ciruelos" }, ko: "자두나무" },
      { key: "walnuts", en: "Walnuts", es: { gender: "m", plural: "Nogales" }, ko: "호두나무" },
      { key: "chestnuts", en: "Chestnuts", es: { gender: "m", plural: "Castaños" }, ko: "밤나무" },
      { key: "acacias", en: "Acacias", es: { gender: "f", plural: "Acacias" }, ko: "아카시아" },
      { key: "sycamores", en: "Sycamores", es: { gender: "m", plural: "Sicómoros" }, ko: "플라타너스" },
      { key: "aspens", en: "Aspens", es: { gender: "f", plural: "Álamos temblones" }, ko: "사시나무" }
    ]
  },
  gemstones: {
    collective: "더미",
    tokens: [
      { key: "diamonds", en: "Diamonds", es: { gender: "m", plural: "Diamantes" }, ko: "다이아몬드" },
      { key: "rubies", en: "Rubies", es: { gender: "m", plural: "Rubíes" }, ko: "루비" },
      { key: "sapphires", en: "Sapphires", es: { gender: "m", plural: "Zafiros" }, ko: "사파이어" },
      { key: "emeralds", en: "Emeralds", es: { gender: "f", plural: "Esmeraldas" }, ko: "에메랄드" },
      { key: "opals", en: "Opals", es: { gender: "m", plural: "Ópalos" }, ko: "오팔" },
      { key: "topazes", en: "Topazes", es: { gender: "m", plural: "Topacios" }, ko: "토파즈" },
      { key: "amethysts", en: "Amethysts", es: { gender: "f", plural: "Amatistas" }, ko: "자수정" },
      { key: "garnets", en: "Garnets", es: { gender: "m", plural: "Granates" }, ko: "가넷" },
      { key: "pearls", en: "Pearls", es: { gender: "f", plural: "Perlas" }, ko: "진주" },
      { key: "jades", en: "Jades", es: { gender: "m", plural: "Jades" }, ko: "옥" },
      { key: "onyxes", en: "Onyxes", es: { gender: "m", plural: "Ónices" }, ko: "오닉스" },
      { key: "turquoises", en: "Turquoises", es: { gender: "f", plural: "Turquesas" }, ko: "터키석" },
      { key: "ambers", en: "Ambers", es: { gender: "m", plural: "Ámbares" }, ko: "호박" },
      { key: "aquamarines", en: "Aquamarines", es: { gender: "f", plural: "Aguamarinas" }, ko: "아쿠아마린" },
      { key: "citrines", en: "Citrines", es: { gender: "m", plural: "Citrinos" }, ko: "시트린" },
      { key: "peridots", en: "Peridots", es: { gender: "m", plural: "Peridotos" }, ko: "페리도트" },
      { key: "moonstones", en: "Moonstones", es: { gender: "f", plural: "Piedras lunares" }, ko: "문스톤" },
      { key: "sunstones", en: "Sunstones", es: { gender: "f", plural: "Piedras solares" }, ko: "선스톤" },
      { key: "spinels", en: "Spinels", es: { gender: "f", plural: "Espinelas" }, ko: "스피넬" },
      { key: "tanzanites", en: "Tanzanites", es: { gender: "f", plural: "Tanzanitas" }, ko: "탄자나이트" },
      { key: "tourmalines", en: "Tourmalines", es: { gender: "f", plural: "Turmalinas" }, ko: "투르말린" },
      { key: "zircons", en: "Zircons", es: { gender: "m", plural: "Circones" }, ko: "지르콘" },
      { key: "bloodstones", en: "Bloodstones", es: { gender: "f", plural: "Piedras de sangre" }, ko: "혈석" },
      { key: "malachites", en: "Malachites", es: { gender: "f", plural: "Malaquitas" }, ko: "말라카이트" },
      { key: "alexandrites", en: "Alexandrites", es: { gender: "f", plural: "Alexandritas" }, ko: "알렉산드라이트" }
    ]
  },
  crystals: {
    collective: "군집",
    tokens: [
      { key: "crystals", en: "Crystals", es: { gender: "m", plural: "Cristales" }, ko: "수정" },
      { key: "quartz", en: "Quartz", es: { gender: "m", plural: "Cuarzos" }, ko: "석영" },
      { key: "obsidian", en: "Obsidian", es: { gender: "f", plural: "Obsidianas" }, ko: "흑요석" },
      { key: "flint", en: "Flint", es: { gender: "m", plural: "Pedernales" }, ko: "부싯돌" },
      { key: "mica", en: "Mica", es: { gender: "f", plural: "Micas" }, ko: "운모" },
      { key: "feldspars", en: "Feldspars", es: { gender: "m", plural: "Feldespatos" }, ko: "장석" },
      { key: "calcites", en: "Calcites", es: { gender: "f", plural: "Calcitas" }, ko: "방해석" },
      { key: "gypsum", en: "Gypsum", es: { gender: "m", plural: "Yesos" }, ko: "석고" },
      { key: "pyrites", en: "Pyrites", es: { gender: "f", plural: "Piritas" }, ko: "황철석" },
      { key: "hematites", en: "Hematites", es: { gender: "f", plural: "Hematitas" }, ko: "적철석" },
      { key: "magnetites", en: "Magnetites", es: { gender: "f", plural: "Magnetitas" }, ko: "자철석" },
      { key: "limestones", en: "Limestones", es: { gender: "f", plural: "Calizas" }, ko: "석회암" },
      { key: "basalts", en: "Basalts", es: { gender: "m", plural: "Basaltos" }, ko: "현무암" },
      { key: "shales", en: "Shales", es: { gender: "f", plural: "Lutitas" }, ko: "셰일" },
      { key: "slates", en: "Slates", es: { gender: "f", plural: "Pizarras" }, ko: "점판암" },
      { key: "sandstones", en: "Sandstones", es: { gender: "f", plural: "Areniscas" }, ko: "사암" },
      { key: "jaspers", en: "Jaspers", es: { gender: "m", plural: "Jaspes" }, ko: "벽옥" },
      { key: "agates", en: "Agates", es: { gender: "f", plural: "Ágatas" }, ko: "마노" },
      { key: "bauxites", en: "Bauxites", es: { gender: "f", plural: "Bauxitas" }, ko: "보크사이트" },
      { key: "graphites", en: "Graphites", es: { gender: "m", plural: "Grafitos" }, ko: "흑연" },
      { key: "sulfurs", en: "Sulfurs", es: { gender: "m", plural: "Azufres" }, ko: "유황" },
      { key: "granites", en: "Granites", es: { gender: "m", plural: "Granitos" }, ko: "화강암" },
      { key: "pumices", en: "Pumices", es: { gender: "f", plural: "Pómez" }, ko: "부석" },
      { key: "dolomites", en: "Dolomites", es: { gender: "f", plural: "Dolomitas" }, ko: "백운석" },
      { key: "halites", en: "Halites", es: { gender: "f", plural: "Halitas" }, ko: "암염" }
    ]
  },
  metals: {
    collective: "괴",
    tokens: [
      { key: "irons", en: "Irons", es: { gender: "m", plural: "Hierros" }, ko: "철" },
      { key: "steels", en: "Steels", es: { gender: "m", plural: "Aceros" }, ko: "강철" },
      { key: "coppers", en: "Coppers", es: { gender: "m", plural: "Cobres" }, ko: "구리" },
      { key: "bronzes", en: "Bronzes", es: { gender: "m", plural: "Bronces" }, ko: "청동" },
      { key: "brasses", en: "Brasses", es: { gender: "m", plural: "Latones" }, ko: "황동" },
      { key: "silvers", en: "Silvers", es: { gender: "f", plural: "Platas" }, ko: "은" },
      { key: "golds", en: "Golds", es: { gender: "m", plural: "Oros" }, ko: "금" },
      { key: "nickels", en: "Nickels", es: { gender: "m", plural: "Níqueles" }, ko: "니켈" },
      { key: "tins", en: "Tins", es: { gender: "m", plural: "Estaños" }, ko: "주석" },
      { key: "leads", en: "Leads", es: { gender: "m", plural: "Plomos" }, ko: "납" },
      { key: "aluminums", en: "Aluminums", es: { gender: "m", plural: "Aluminios" }, ko: "알루미늄" },
      { key: "titaniums", en: "Titaniums", es: { gender: "m", plural: "Titanios" }, ko: "티타늄" },
      { key: "chromes", en: "Chromes", es: { gender: "m", plural: "Cromos" }, ko: "크롬" },
      { key: "cobalts", en: "Cobalts", es: { gender: "m", plural: "Cobaltos" }, ko: "코발트" },
      { key: "zincs", en: "Zincs", es: { gender: "m", plural: "Zincs" }, ko: "아연" },
      { key: "platinums", en: "Platinums", es: { gender: "m", plural: "Platinos" }, ko: "백금" },
      { key: "palladiums", en: "Palladiums", es: { gender: "m", plural: "Paladios" }, ko: "팔라듐" },
      { key: "mercurys", en: "Mercurys", es: { gender: "m", plural: "Mercurios" }, ko: "수은" },
      { key: "tungstens", en: "Tungstens", es: { gender: "m", plural: "Wolframios" }, ko: "텅스텐" },
      { key: "iridiums", en: "Iridiums", es: { gender: "m", plural: "Iridios" }, ko: "이리듐" },
      { key: "osmiums", en: "Osmiums", es: { gender: "m", plural: "Osmios" }, ko: "오스뮴" },
      { key: "lithiums", en: "Lithiums", es: { gender: "m", plural: "Litios" }, ko: "리튬" },
      { key: "magnesiums", en: "Magnesiums", es: { gender: "m", plural: "Magnesios" }, ko: "마그네슘" },
      { key: "sodiums", en: "Sodiums", es: { gender: "m", plural: "Sodios" }, ko: "나트륨" },
      { key: "silicons", en: "Silicons", es: { gender: "m", plural: "Silicios" }, ko: "실리콘" }
    ]
  },
  tools: {
    collective: "묶음",
    tokens: [
      { key: "pencils", en: "Pencils", es: { gender: "m", plural: "Lápices" }, ko: "연필" },
      { key: "pens", en: "Pens", es: { gender: "m", plural: "Bolígrafos" }, ko: "펜" },
      { key: "brushes", en: "Brushes", es: { gender: "m", plural: "Pinceles" }, ko: "붓" },
      { key: "markers", en: "Markers", es: { gender: "m", plural: "Marcadores" }, ko: "마커" },
      { key: "erasers", en: "Erasers", es: { gender: "m", plural: "Borradores" }, ko: "지우개" },
      { key: "rulers", en: "Rulers", es: { gender: "f", plural: "Reglas" }, ko: "자" },
      { key: "scissors", en: "Scissors", es: { gender: "f", plural: "Tijeras" }, ko: "가위" },
      { key: "hammers", en: "Hammers", es: { gender: "m", plural: "Martillos" }, ko: "망치" },
      { key: "wrenches", en: "Wrenches", es: { gender: "f", plural: "Llaves inglesas" }, ko: "렌치" },
      { key: "screwdrivers", en: "Screwdrivers", es: { gender: "m", plural: "Destornilladores" }, ko: "드라이버" },
      { key: "pliers", en: "Pliers", es: { gender: "m", plural: "Alicates" }, ko: "펜치" },
      { key: "knives", en: "Knives", es: { gender: "m", plural: "Cuchillos" }, ko: "칼" },
      { key: "chisels", en: "Chisels", es: { gender: "m", plural: "Cinceles" }, ko: "끌" },
      { key: "saws", en: "Saws", es: { gender: "f", plural: "Sierras" }, ko: "톱" },
      { key: "drills", en: "Drills", es: { gender: "m", plural: "Taladros" }, ko: "드릴" },
      { key: "files", en: "Files", es: { gender: "f", plural: "Limas" }, ko: "줄" },
      { key: "staplers", en: "Staplers", es: { gender: "f", plural: "Grapadoras" }, ko: "스테이플러" },
      { key: "paperclips", en: "Paperclips", es: { gender: "m", plural: "Clips" }, ko: "클립" },
      { key: "notebooks", en: "Notebooks", es: { gender: "m", plural: "Cuadernos" }, ko: "노트" },
      { key: "journals", en: "Journals", es: { gender: "m", plural: "Diarios" }, ko: "일기장" },
      { key: "tape_rolls", en: "Tape Rolls", es: { gender: "m", plural: "Rollos de cinta" }, ko: "테이프" },
      { key: "glue_sticks", en: "Glue Sticks", es: { gender: "f", plural: "Barras de pegamento" }, ko: "딱풀" },
      { key: "calculators", en: "Calculators", es: { gender: "f", plural: "Calculadoras" }, ko: "계산기" },
      { key: "compasses", en: "Compasses", es: { gender: "m", plural: "Compases" }, ko: "콤파스" },
      { key: "protractors", en: "Protractors", es: { gender: "m", plural: "Transportadores" }, ko: "각도기" }
    ]
  },
  household: {
    collective: "세트",
    tokens: [
      { key: "keys", en: "Keys", es: { gender: "f", plural: "Llaves" }, ko: "열쇠" },
      { key: "lamps", en: "Lamps", es: { gender: "f", plural: "Lámparas" }, ko: "램프" },
      { key: "candles", en: "Candles", es: { gender: "f", plural: "Velas" }, ko: "양초" },
      { key: "mirrors", en: "Mirrors", es: { gender: "m", plural: "Espejos" }, ko: "거울" },
      { key: "clocks", en: "Clocks", es: { gender: "m", plural: "Relojes" }, ko: "시계" },
      { key: "chairs", en: "Chairs", es: { gender: "f", plural: "Sillas" }, ko: "의자" },
      { key: "tables", en: "Tables", es: { gender: "f", plural: "Mesas" }, ko: "테이블" },
      { key: "shelves", en: "Shelves", es: { gender: "m", plural: "Estantes" }, ko: "선반" },
      { key: "bottles", en: "Bottles", es: { gender: "f", plural: "Botellas" }, ko: "병" },
      { key: "cups", en: "Cups", es: { gender: "f", plural: "Tazas" }, ko: "컵" },
      { key: "plates", en: "Plates", es: { gender: "m", plural: "Platos" }, ko: "접시" },
      { key: "bowls", en: "Bowls", es: { gender: "m", plural: "Cuencos" }, ko: "그릇" },
      { key: "mugs", en: "Mugs", es: { gender: "m", plural: "Jarros" }, ko: "머그잔" },
      { key: "vases", en: "Vases", es: { gender: "m", plural: "Jarrones" }, ko: "꽃병" },
      { key: "rugs", en: "Rugs", es: { gender: "f", plural: "Alfombras" }, ko: "양탄자" },
      { key: "curtains", en: "Curtains", es: { gender: "f", plural: "Cortinas" }, ko: "커튼" },
      { key: "pillows", en: "Pillows", es: { gender: "f", plural: "Almohadas" }, ko: "베개" },
      { key: "blankets", en: "Blankets", es: { gender: "f", plural: "Mantas" }, ko: "담요" },
      { key: "baskets", en: "Baskets", es: { gender: "f", plural: "Cestas" }, ko: "바구니" },
      { key: "buckets", en: "Buckets", es: { gender: "m", plural: "Cubos" }, ko: "양동이" },
      { key: "hangers", en: "Hangers", es: { gender: "f", plural: "Perchas" }, ko: "옷걸이" },
      { key: "towels", en: "Towels", es: { gender: "f", plural: "Toallas" }, ko: "수건" },
      { key: "fans", en: "Fans", es: { gender: "m", plural: "Ventiladores" }, ko: "선풍기" },
      { key: "locks", en: "Locks", es: { gender: "f", plural: "Cerraduras" }, ko: "자물쇠" },
      { key: "ladders", en: "Ladders", es: { gender: "f", plural: "Escaleras" }, ko: "사다리" }
    ]
  },
  tech: {
    collective: "묶음",
    tokens: [
      { key: "circuits", en: "Circuits", es: { gender: "m", plural: "Circuitos" }, ko: "회로" },
      { key: "chips", en: "Chips", es: { gender: "m", plural: "Chips" }, ko: "칩" },
      { key: "sensors", en: "Sensors", es: { gender: "m", plural: "Sensores" }, ko: "센서" },
      { key: "wires", en: "Wires", es: { gender: "m", plural: "Alambres" }, ko: "전선" },
      { key: "cables", en: "Cables", es: { gender: "m", plural: "Cables" }, ko: "케이블" },
      { key: "screens", en: "Screens", es: { gender: "f", plural: "Pantallas" }, ko: "화면" },
      { key: "pixels", en: "Pixels", es: { gender: "m", plural: "Píxeles" }, ko: "픽셀" },
      { key: "servers", en: "Servers", es: { gender: "m", plural: "Servidores" }, ko: "서버" },
      { key: "routers", en: "Routers", es: { gender: "m", plural: "Routers" }, ko: "라우터" },
      { key: "switches", en: "Switches", es: { gender: "m", plural: "Interruptores" }, ko: "스위치" },
      { key: "modules", en: "Modules", es: { gender: "m", plural: "Módulos" }, ko: "모듈" },
      { key: "boards", en: "Boards", es: { gender: "f", plural: "Placas" }, ko: "보드" },
      { key: "batteries", en: "Batteries", es: { gender: "f", plural: "Baterías" }, ko: "배터리" },
      { key: "antennas", en: "Antennas", es: { gender: "f", plural: "Antenas" }, ko: "안테나" },
      { key: "transistors", en: "Transistors", es: { gender: "m", plural: "Transistores" }, ko: "트랜지스터" },
      { key: "diodes", en: "Diodes", es: { gender: "m", plural: "Diodos" }, ko: "다이오드" },
      { key: "resistors", en: "Resistors", es: { gender: "f", plural: "Resistencias" }, ko: "저항" },
      { key: "capacitors", en: "Capacitors", es: { gender: "m", plural: "Condensadores" }, ko: "커패시터" },
      { key: "leds", en: "LEDs", es: { gender: "m", plural: "LEDs" }, ko: "LED" },
      { key: "connectors", en: "Connectors", es: { gender: "m", plural: "Conectores" }, ko: "커넥터" },
      { key: "slots", en: "Slots", es: { gender: "f", plural: "Ranuras" }, ko: "슬롯" },
      { key: "ports", en: "Ports", es: { gender: "m", plural: "Puertos" }, ko: "포트" },
      { key: "drivers", en: "Drivers", es: { gender: "m", plural: "Controladores" }, ko: "드라이버" },
      { key: "cores", en: "Cores", es: { gender: "m", plural: "Núcleos" }, ko: "코어" },
      { key: "nodes", en: "Nodes", es: { gender: "m", plural: "Nodos" }, ko: "노드" }
    ]
  },
  vehicles: {
    collective: "대",
    tokens: [
      { key: "cars", en: "Cars", es: { gender: "m", plural: "Coches" }, ko: "자동차" },
      { key: "trains", en: "Trains", es: { gender: "m", plural: "Trenes" }, ko: "기차" },
      { key: "ships", en: "Ships", es: { gender: "m", plural: "Barcos" }, ko: "배" },
      { key: "boats", en: "Boats", es: { gender: "m", plural: "Botes" }, ko: "보트" },
      { key: "buses", en: "Buses", es: { gender: "m", plural: "Autobuses" }, ko: "버스" },
      { key: "trucks", en: "Trucks", es: { gender: "m", plural: "Camiones" }, ko: "트럭" },
      { key: "vans", en: "Vans", es: { gender: "f", plural: "Furgonetas" }, ko: "밴" },
      { key: "bikes", en: "Bikes", es: { gender: "f", plural: "Bicicletas" }, ko: "자전거" },
      { key: "motorcycles", en: "Motorcycles", es: { gender: "f", plural: "Motocicletas" }, ko: "오토바이" },
      { key: "scooters", en: "Scooters", es: { gender: "m", plural: "Patinetes" }, ko: "스쿠터" },
      { key: "subways", en: "Subways", es: { gender: "m", plural: "Metros" }, ko: "지하철" },
      { key: "trams", en: "Trams", es: { gender: "m", plural: "Tranvías" }, ko: "트램" },
      { key: "taxis", en: "Taxis", es: { gender: "m", plural: "Taxis" }, ko: "택시" },
      { key: "ferries", en: "Ferries", es: { gender: "m", plural: "Transbordadores" }, ko: "페리" },
      { key: "airplanes", en: "Airplanes", es: { gender: "m", plural: "Aviones" }, ko: "비행기" },
      { key: "jets", en: "Jets", es: { gender: "m", plural: "Jets" }, ko: "제트기" },
      { key: "helicopters", en: "Helicopters", es: { gender: "m", plural: "Helicópteros" }, ko: "헬리콥터" },
      { key: "rockets", en: "Rockets", es: { gender: "m", plural: "Cohetes" }, ko: "로켓" },
      { key: "shuttles", en: "Shuttles", es: { gender: "f", plural: "Lanzaderas" }, ko: "셔틀" },
      { key: "submarines", en: "Submarines", es: { gender: "m", plural: "Submarinos" }, ko: "잠수함" },
      { key: "carriages", en: "Carriages", es: { gender: "m", plural: "Carruajes" }, ko: "마차" },
      { key: "wagons", en: "Wagons", es: { gender: "m", plural: "Vagones" }, ko: "객차" },
      { key: "yachts", en: "Yachts", es: { gender: "m", plural: "Yates" }, ko: "요트" },
      { key: "sailboats", en: "Sailboats", es: { gender: "m", plural: "Veleros" }, ko: "돛단배" },
      { key: "motorboats", en: "Motorboats", es: { gender: "f", plural: "Lanchas" }, ko: "모터보트" }
    ]
  },
  celestial: {
    collective: "무리",
    tokens: [
      { key: "stars", en: "Stars", es: { gender: "f", plural: "Estrellas" }, ko: "별" },
      { key: "moons", en: "Moons", es: { gender: "f", plural: "Lunas" }, ko: "달" },
      { key: "suns", en: "Suns", es: { gender: "m", plural: "Soles" }, ko: "태양" },
      { key: "planets", en: "Planets", es: { gender: "m", plural: "Planetas" }, ko: "행성" },
      { key: "comets", en: "Comets", es: { gender: "m", plural: "Cometas" }, ko: "혜성" },
      { key: "meteors", en: "Meteors", es: { gender: "m", plural: "Meteoros" }, ko: "유성" },
      { key: "asteroids", en: "Asteroids", es: { gender: "m", plural: "Asteroides" }, ko: "소행성" },
      { key: "galaxies", en: "Galaxies", es: { gender: "f", plural: "Galaxias" }, ko: "은하" },
      { key: "nebulas", en: "Nebulas", es: { gender: "f", plural: "Nebulosas" }, ko: "성운" },
      { key: "orbits", en: "Orbits", es: { gender: "f", plural: "Órbitas" }, ko: "궤도" },
      { key: "horizons", en: "Horizons", es: { gender: "m", plural: "Horizontes" }, ko: "지평선" },
      { key: "skies", en: "Skies", es: { gender: "m", plural: "Cielos" }, ko: "하늘" },
      { key: "constellations", en: "Constellations", es: { gender: "f", plural: "Constelaciones" }, ko: "별자리" },
      { key: "auroras", en: "Auroras", es: { gender: "f", plural: "Auroras" }, ko: "오로라" },
      { key: "eclipses", en: "Eclipses", es: { gender: "m", plural: "Eclipses" }, ko: "일식" },
      { key: "zeniths", en: "Zeniths", es: { gender: "m", plural: "Cenits" }, ko: "천정점" },
      { key: "halos", en: "Halos", es: { gender: "m", plural: "Halos" }, ko: "후광" },
      { key: "satellites", en: "Satellites", es: { gender: "m", plural: "Satélites" }, ko: "위성" },
      { key: "starfields", en: "Starfields", es: { gender: "m", plural: "Campos estelares" }, ko: "별무리" },
      { key: "novas", en: "Novas", es: { gender: "f", plural: "Novas" }, ko: "노바" },
      { key: "supernovas", en: "Supernovas", es: { gender: "f", plural: "Supernovas" }, ko: "초신성" },
      { key: "pulsars", en: "Pulsars", es: { gender: "m", plural: "Púlsares" }, ko: "펄서" },
      { key: "quasars", en: "Quasars", es: { gender: "m", plural: "Cuásares" }, ko: "퀘이사" },
      { key: "meteorites", en: "Meteorites", es: { gender: "m", plural: "Meteoritos" }, ko: "운석" },
      { key: "milky_ways", en: "Milky Ways", es: { gender: "f", plural: "Vías Lácteas" }, ko: "은하수" }
    ]
  },
  weather: {
    collective: "무리",
    tokens: [
      { key: "waves", en: "Waves", es: { gender: "f", plural: "Olas" }, ko: "파도" },
      { key: "tides", en: "Tides", es: { gender: "f", plural: "Mareas" }, ko: "조수" },
      { key: "rains", en: "Rains", es: { gender: "f", plural: "Lluvias" }, ko: "비" },
      { key: "storms", en: "Storms", es: { gender: "f", plural: "Tormentas" }, ko: "폭풍" },
      { key: "thunders", en: "Thunders", es: { gender: "m", plural: "Truenos" }, ko: "천둥" },
      { key: "lightnings", en: "Lightnings", es: { gender: "m", plural: "Relámpagos" }, ko: "번개" },
      { key: "breezes", en: "Breezes", es: { gender: "f", plural: "Brisas" }, ko: "산들바람" },
      { key: "gusts", en: "Gusts", es: { gender: "f", plural: "Ráfagas" }, ko: "돌풍" },
      { key: "mists", en: "Mists", es: { gender: "f", plural: "Nieblas" }, ko: "안개" },
      { key: "fogs", en: "Fogs", es: { gender: "f", plural: "Neblinas" }, ko: "짙은안개" },
      { key: "snows", en: "Snows", es: { gender: "f", plural: "Nieves" }, ko: "눈" },
      { key: "hails", en: "Hails", es: { gender: "m", plural: "Granizos" }, ko: "우박" },
      { key: "drizzles", en: "Drizzles", es: { gender: "f", plural: "Lloviznas" }, ko: "이슬비" },
      { key: "showers", en: "Showers", es: { gender: "m", plural: "Chubascos" }, ko: "소나기" },
      { key: "floods", en: "Floods", es: { gender: "f", plural: "Inundaciones" }, ko: "홍수" },
      { key: "currents", en: "Currents", es: { gender: "f", plural: "Corrientes" }, ko: "해류" },
      { key: "streams", en: "Streams", es: { gender: "m", plural: "Arroyos" }, ko: "시냇물" },
      { key: "rivulets", en: "Rivulets", es: { gender: "m", plural: "Riachos" }, ko: "개울" },
      { key: "rapids", en: "Rapids", es: { gender: "m", plural: "Rápidos" }, ko: "급류" },
      { key: "whirlpools", en: "Whirlpools", es: { gender: "m", plural: "Remolinos" }, ko: "소용돌이" },
      { key: "springs", en: "Springs", es: { gender: "m", plural: "Manantiales" }, ko: "샘물" },
      { key: "dews", en: "Dews", es: { gender: "m", plural: "Rocíos" }, ko: "이슬" },
      { key: "frosts", en: "Frosts", es: { gender: "f", plural: "Escarchas" }, ko: "서리" },
      { key: "icebergs", en: "Icebergs", es: { gender: "m", plural: "Icebergs" }, ko: "빙산" },
      { key: "avalanches", en: "Avalanches", es: { gender: "f", plural: "Avalanchas" }, ko: "눈사태" }
    ]
  },
  geography: {
    collective: "지대",
    tokens: [
      { key: "islands", en: "Islands", es: { gender: "f", plural: "Islas" }, ko: "섬" },
      { key: "mountains", en: "Mountains", es: { gender: "f", plural: "Montañas" }, ko: "산" },
      { key: "valleys", en: "Valleys", es: { gender: "m", plural: "Valles" }, ko: "계곡" },
      { key: "canyons", en: "Canyons", es: { gender: "m", plural: "Cañones" }, ko: "협곡" },
      { key: "deserts", en: "Deserts", es: { gender: "m", plural: "Desiertos" }, ko: "사막" },
      { key: "forests", en: "Forests", es: { gender: "m", plural: "Bosques" }, ko: "숲" },
      { key: "rivers", en: "Rivers", es: { gender: "m", plural: "Ríos" }, ko: "강" },
      { key: "lakes", en: "Lakes", es: { gender: "m", plural: "Lagos" }, ko: "호수" },
      { key: "oceans", en: "Oceans", es: { gender: "m", plural: "Océanos" }, ko: "대양" },
      { key: "seas", en: "Seas", es: { gender: "m", plural: "Mares" }, ko: "바다" },
      { key: "coasts", en: "Coasts", es: { gender: "f", plural: "Costas" }, ko: "해안" },
      { key: "harbors", en: "Harbors", es: { gender: "m", plural: "Puertos" }, ko: "항구" },
      { key: "bays", en: "Bays", es: { gender: "f", plural: "Bahías" }, ko: "만" },
      { key: "shores", en: "Shores", es: { gender: "f", plural: "Orillas" }, ko: "해변" },
      { key: "plains", en: "Plains", es: { gender: "f", plural: "Llanuras" }, ko: "평야" },
      { key: "cliffs", en: "Cliffs", es: { gender: "m", plural: "Acantilados" }, ko: "절벽" },
      { key: "hills", en: "Hills", es: { gender: "f", plural: "Colinas" }, ko: "언덕" },
      { key: "deltas", en: "Deltas", es: { gender: "m", plural: "Deltas" }, ko: "삼각주" },
      { key: "glaciers", en: "Glaciers", es: { gender: "m", plural: "Glaciares" }, ko: "빙하" },
      { key: "jungles", en: "Jungles", es: { gender: "f", plural: "Selvas" }, ko: "정글" },
      { key: "wastelands", en: "Wastelands", es: { gender: "f", plural: "Tierras baldías" }, ko: "황무지" },
      { key: "plateaus", en: "Plateaus", es: { gender: "f", plural: "Mesetas" }, ko: "고원" },
      { key: "volcanoes", en: "Volcanoes", es: { gender: "m", plural: "Volcanes" }, ko: "화산" },
      { key: "fjords", en: "Fjords", es: { gender: "m", plural: "Fiordos" }, ko: "피오르드" },
      { key: "reefs", en: "Reefs", es: { gender: "m", plural: "Arrecifes" }, ko: "산호초" }
    ]
  },
  music: {
    collective: "단",
    tokens: [
      { key: "drums", en: "Drums", es: { gender: "m", plural: "Tambores" }, ko: "드럼" },
      { key: "bells", en: "Bells", es: { gender: "f", plural: "Campanas" }, ko: "종" },
      { key: "guitars", en: "Guitars", es: { gender: "f", plural: "Guitarras" }, ko: "기타" },
      { key: "pianos", en: "Pianos", es: { gender: "m", plural: "Pianos" }, ko: "피아노" },
      { key: "violins", en: "Violins", es: { gender: "m", plural: "Violines" }, ko: "바이올린" },
      { key: "flutes", en: "Flutes", es: { gender: "f", plural: "Flautas" }, ko: "플루트" },
      { key: "trumpets", en: "Trumpets", es: { gender: "f", plural: "Trompetas" }, ko: "트럼펫" },
      { key: "saxophones", en: "Saxophones", es: { gender: "m", plural: "Saxofones" }, ko: "색소폰" },
      { key: "trombones", en: "Trombones", es: { gender: "m", plural: "Trombones" }, ko: "트롬본" },
      { key: "cellos", en: "Cellos", es: { gender: "m", plural: "Violonchelos" }, ko: "첼로" },
      { key: "harps", en: "Harps", es: { gender: "f", plural: "Arpas" }, ko: "하프" },
      { key: "synths", en: "Synths", es: { gender: "m", plural: "Sintetizadores" }, ko: "신시사이저" },
      { key: "beats", en: "Beats", es: { gender: "m", plural: "Pulsos" }, ko: "비트" },
      { key: "rhythms", en: "Rhythms", es: { gender: "m", plural: "Ritmos" }, ko: "리듬" },
      { key: "echoes", en: "Echoes", es: { gender: "m", plural: "Ecos" }, ko: "메아리" },
      { key: "chords", en: "Chords", es: { gender: "m", plural: "Acordes" }, ko: "코드" },
      { key: "notes", en: "Notes", es: { gender: "f", plural: "Notas" }, ko: "음표" },
      { key: "melodies", en: "Melodies", es: { gender: "f", plural: "Melodías" }, ko: "멜로디" },
      { key: "harmonies", en: "Harmonies", es: { gender: "f", plural: "Armonías" }, ko: "화음" },
      { key: "voices", en: "Voices", es: { gender: "f", plural: "Voces" }, ko: "목소리" },
      { key: "choirs", en: "Choirs", es: { gender: "m", plural: "Coros" }, ko: "합창단" },
      { key: "anthems", en: "Anthems", es: { gender: "m", plural: "Himnos" }, ko: "찬가" },
      { key: "riffs", en: "Riffs", es: { gender: "m", plural: "Riffs" }, ko: "리프" },
      { key: "basslines", en: "Basslines", es: { gender: "f", plural: "Líneas de bajo" }, ko: "베이스라인" },
      { key: "choruses", en: "Choruses", es: { gender: "m", plural: "Estribillos" }, ko: "후렴" }
    ]
  },
  regalia: {
    collective: "단",
    tokens: [
      { key: "crowns", en: "Crowns", es: { gender: "f", plural: "Coronas" }, ko: "왕관" },
      { key: "thrones", en: "Thrones", es: { gender: "m", plural: "Tronos" }, ko: "왕좌" },
      { key: "scepters", en: "Scepters", es: { gender: "m", plural: "Cetros" }, ko: "홀" },
      { key: "orbs", en: "Orbs", es: { gender: "m", plural: "Orbes" }, ko: "보주" },
      { key: "cloaks", en: "Cloaks", es: { gender: "f", plural: "Capas" }, ko: "망토" },
      { key: "rings", en: "Rings", es: { gender: "m", plural: "Anillos" }, ko: "반지" },
      { key: "masks", en: "Masks", es: { gender: "f", plural: "Máscaras" }, ko: "가면" },
      { key: "banners", en: "Banners", es: { gender: "m", plural: "Estandartes" }, ko: "깃발" },
      { key: "badges", en: "Badges", es: { gender: "m", plural: "Distintivos" }, ko: "배지" },
      { key: "relics", en: "Relics", es: { gender: "f", plural: "Reliquias" }, ko: "유물" },
      { key: "talismans", en: "Talismans", es: { gender: "m", plural: "Talismanes" }, ko: "탈리스만" },
      { key: "amulets", en: "Amulets", es: { gender: "m", plural: "Amuletos" }, ko: "부적" },
      { key: "altars", en: "Altars", es: { gender: "m", plural: "Altares" }, ko: "제단" },
      { key: "chalices", en: "Chalices", es: { gender: "m", plural: "Cálices" }, ko: "성배" },
      { key: "candlesticks", en: "Candlesticks", es: { gender: "m", plural: "Candelabros" }, ko: "촛대" },
      { key: "scrolls", en: "Scrolls", es: { gender: "m", plural: "Pergaminos" }, ko: "두루마리" },
      { key: "totems", en: "Totems", es: { gender: "m", plural: "Tótems" }, ko: "토템" },
      { key: "idols", en: "Idols", es: { gender: "m", plural: "Ídolos" }, ko: "우상" },
      { key: "robes", en: "Robes", es: { gender: "f", plural: "Túnicas" }, ko: "로브" },
      { key: "sigils", en: "Sigils", es: { gender: "m", plural: "Sigilos" }, ko: "문장" },
      { key: "staves", en: "Staves", es: { gender: "m", plural: "Bastones" }, ko: "지팡이" },
      { key: "emblems", en: "Emblems", es: { gender: "m", plural: "Emblemas" }, ko: "상징" },
      { key: "medals", en: "Medals", es: { gender: "f", plural: "Medallas" }, ko: "메달" },
      { key: "shields", en: "Shields", es: { gender: "m", plural: "Escudos" }, ko: "방패" },
      { key: "standards", en: "Standards", es: { gender: "f", plural: "Insignias" }, ko: "기치" }
    ]
  },
  groups: {
    collective: null,
    tokens: [
      { key: "crews", en: "Crews", es: { gender: "f", plural: "Tripulaciones" }, ko: "크루", collective: null },
      { key: "guilds", en: "Guilds", es: { gender: "m", plural: "Gremios" }, ko: "길드", collective: null },
      { key: "squads", en: "Squads", es: { gender: "m", plural: "Escuadrones" }, ko: "분대", collective: null },
      { key: "teams", en: "Teams", es: { gender: "m", plural: "Equipos" }, ko: "팀", collective: null },
      { key: "bands", en: "Bands", es: { gender: "f", plural: "Bandas" }, ko: "밴드", collective: null },
      { key: "legions", en: "Legions", es: { gender: "f", plural: "Legiones" }, ko: "군단", collective: null },
      { key: "clans", en: "Clans", es: { gender: "m", plural: "Clanes" }, ko: "클랜", collective: null },
      { key: "packs", en: "Packs", es: { gender: "f", plural: "Manadas" }, ko: "무리", collective: null },
      { key: "hordes", en: "Hordes", es: { gender: "f", plural: "Hordas" }, ko: "군중", collective: null },
      { key: "flocks", en: "Flocks", es: { gender: "f", plural: "Bandadas" }, ko: "떼", collective: null },
      { key: "swarms", en: "Swarms", es: { gender: "m", plural: "Enjambres" }, ko: "군집", collective: null },
      { key: "armies", en: "Armies", es: { gender: "m", plural: "Ejércitos" }, ko: "군대", collective: null },
      { key: "units", en: "Units", es: { gender: "f", plural: "Unidades" }, ko: "부대", collective: null },
      { key: "circles", en: "Circles", es: { gender: "m", plural: "Círculos" }, ko: "서클", collective: null },
      { key: "orders", en: "Orders", es: { gender: "f", plural: "Órdenes" }, ko: "기사단", collective: null },
      { key: "companies", en: "Companies", es: { gender: "f", plural: "Compañías" }, ko: "단체", collective: null },
      { key: "brigades", en: "Brigades", es: { gender: "f", plural: "Brigadas" }, ko: "여단", collective: null },
      { key: "platoons", en: "Platoons", es: { gender: "m", plural: "Pelotones" }, ko: "소대", collective: null },
      { key: "cells", en: "Cells", es: { gender: "f", plural: "Células" }, ko: "셀", collective: null },
      { key: "alliances", en: "Alliances", es: { gender: "f", plural: "Alianzas" }, ko: "동맹", collective: null },
      { key: "coalitions", en: "Coalitions", es: { gender: "f", plural: "Coaliciones" }, ko: "연합체", collective: null },
      { key: "councils", en: "Councils", es: { gender: "m", plural: "Consejos" }, ko: "의회", collective: null },
      { key: "federations", en: "Federations", es: { gender: "f", plural: "Federaciones" }, ko: "연방", collective: null },
      { key: "leagues", en: "Leagues", es: { gender: "f", plural: "Ligas" }, ko: "리그", collective: null },
      { key: "networks", en: "Networks", es: { gender: "f", plural: "Redes" }, ko: "네트워크", collective: null }
    ]
  }
};

const adjectives = {};
const adjectiveCategories = {};

Object.entries(ADJECTIVE_CATEGORY_DEFS).forEach(([categoryKey, tokens]) => {
  const categoryId = `adj.${categoryKey}`;
  adjectiveCategories[categoryId] = tokens.map((token) => {
    const id = `${categoryId}.${token.key}`;
    adjectives[id] = { en: token.en, es: token.es, ko: token.ko };
    return id;
  });
});

const nouns = {};
const nounCategories = {};

Object.entries(NOUN_CATEGORY_DEFS).forEach(([categoryKey, def]) => {
  const categoryId = `noun.${categoryKey}`;
  const tokens = def.tokens || [];
  nounCategories[categoryId] = tokens.map((token) => {
    const id = `${categoryId}.${token.key}`;
    const ko: { base: string; collective?: string; needsDeul?: boolean } = { base: token.ko };
    if (token.collective) {
      ko.collective = token.collective;
    } else if (!token.needsDeul && def.collective) {
      ko.collective = def.collective;
    }
    if (token.needsDeul) ko.needsDeul = true;
    nouns[id] = {
      enPlural: token.en,
      es: token.es,
      ko
    };
    return id;
  });
});

export const ACT_NAME_ADJECTIVES = adjectives;
export const ACT_NAME_NOUNS = nouns;
export const ACT_NAME_CATEGORIES = { adjectiveCategories, nounCategories };
export const ACT_NAME_ADJECTIVE_CATEGORY_IDS = Object.keys(adjectiveCategories);
export const ACT_NAME_NOUN_CATEGORY_IDS = Object.keys(nounCategories);
export const ACT_NAME_TOTALS = {
  adjectives: Object.keys(adjectives).length,
  nouns: Object.keys(nouns).length
};
