type KoText = {
   hangul: string;
   rr: string;
 };
type ActNameAdjective = {
   en: string;
   es_m_s: string;
   es_f_s: string;
   es_m_p: string;
   es_f_p: string;
   ko: KoText;
 };
type ActNameNoun = {
   en: { s: string; p: string };
   es: { gender: "m" | "f"; s: string; p: string };
   ko: { s: KoText; p: KoText };
 };
const INITIAL_ROMA = [
  "g",
  "kk",
  "n",
  "d",
  "tt",
  "r",
  "m",
  "b",
  "pp",
  "s",
  "ss",
  "",
  "j",
  "jj",
  "ch",
  "k",
  "t",
  "p",
  "h"
];

const VOWEL_ROMA = [
  "a",
  "ae",
  "ya",
  "yae",
  "eo",
  "e",
  "yeo",
  "ye",
  "o",
  "wa",
  "wae",
  "oe",
  "yo",
  "u",
  "wo",
  "we",
  "wi",
  "yu",
  "eu",
  "ui",
  "i"
];

const FINAL_ROMA = [
  "",
  "k",
  "k",
  "k",
  "n",
  "n",
  "n",
  "t",
  "l",
  "k",
  "m",
  "l",
  "l",
  "l",
  "l",
  "m",
  "p",
  "p",
  "t",
  "t",
  "ng",
  "t",
  "t",
  "k",
  "t",
  "p",
  "t"
];
export const romanizeHangul = (value: string) => {
  const raw = String(value || "");
  let out = "";
  for (let i = 0; i < raw.length; i += 1) {
    const code = raw.charCodeAt(i);
    if (code >= 0xac00 && code <= 0xd7a3) {
      const index = code - 0xac00;
      const initialIndex = Math.floor(index / 588);
      const vowelIndex = Math.floor((index % 588) / 28);
      const finalIndex = index % 28;
      out += `${INITIAL_ROMA[initialIndex]}${VOWEL_ROMA[vowelIndex]}${FINAL_ROMA[finalIndex]}`;
    } else {
      out += raw[i];
    }
  }
  return out;
};

const koAdj = (hangul: string): KoText => ({
  hangul,
  rr: romanizeHangul(hangul)
});

const koNoun = (singular: string, plural: string) => ({
  s: koAdj(singular),
  p: koAdj(plural)
});

const ADJECTIVE_CATEGORIES: Record<string, ActNameAdjective[]> = {
  colors_basic: [
    { en: "Blue", es_m_s: "azul", es_f_s: "azul", es_m_p: "azules", es_f_p: "azules", ko: koAdj("파란") },
    { en: "Red", es_m_s: "rojo", es_f_s: "roja", es_m_p: "rojos", es_f_p: "rojas", ko: koAdj("빨간") },
    { en: "Green", es_m_s: "verde", es_f_s: "verde", es_m_p: "verdes", es_f_p: "verdes", ko: koAdj("초록") },
    { en: "Yellow", es_m_s: "amarillo", es_f_s: "amarilla", es_m_p: "amarillos", es_f_p: "amarillas", ko: koAdj("노란") },
    { en: "Black", es_m_s: "negro", es_f_s: "negra", es_m_p: "negros", es_f_p: "negras", ko: koAdj("검은") },
    { en: "White", es_m_s: "blanco", es_f_s: "blanca", es_m_p: "blancos", es_f_p: "blancas", ko: koAdj("하얀") },
    { en: "Gray", es_m_s: "gris", es_f_s: "gris", es_m_p: "grises", es_f_p: "grises", ko: koAdj("회색") },
    { en: "Brown", es_m_s: "marrón", es_f_s: "marrón", es_m_p: "marrones", es_f_p: "marrones", ko: koAdj("갈색") },
    { en: "Pink", es_m_s: "rosado", es_f_s: "rosada", es_m_p: "rosados", es_f_p: "rosadas", ko: koAdj("분홍") },
    { en: "Purple", es_m_s: "morado", es_f_s: "morada", es_m_p: "morados", es_f_p: "moradas", ko: koAdj("보라") },
    { en: "Orange", es_m_s: "naranja", es_f_s: "naranja", es_m_p: "naranja", es_f_p: "naranja", ko: koAdj("주황") },
    { en: "Gold", es_m_s: "dorado", es_f_s: "dorada", es_m_p: "dorados", es_f_p: "doradas", ko: koAdj("금빛") },
    { en: "Silver", es_m_s: "plateado", es_f_s: "plateada", es_m_p: "plateados", es_f_p: "plateadas", ko: koAdj("은빛") },
    { en: "Indigo", es_m_s: "índigo", es_f_s: "índigo", es_m_p: "índigo", es_f_p: "índigo", ko: koAdj("남색") },
    { en: "Turquoise", es_m_s: "turquesa", es_f_s: "turquesa", es_m_p: "turquesa", es_f_p: "turquesa", ko: koAdj("청록") },
    { en: "Cyan", es_m_s: "cian", es_f_s: "cian", es_m_p: "cian", es_f_p: "cian", ko: koAdj("시안") },
    { en: "Beige", es_m_s: "beige", es_f_s: "beige", es_m_p: "beige", es_f_p: "beige", ko: koAdj("베이지") },
    { en: "Ivory", es_m_s: "marfil", es_f_s: "marfil", es_m_p: "marfil", es_f_p: "marfil", ko: koAdj("아이보리") },
    { en: "Crimson", es_m_s: "carmesí", es_f_s: "carmesí", es_m_p: "carmesí", es_f_p: "carmesí", ko: koAdj("진홍") },
    { en: "Emerald", es_m_s: "esmeralda", es_f_s: "esmeralda", es_m_p: "esmeralda", es_f_p: "esmeralda", ko: koAdj("에메랄드빛") }
  ],
  light_glow: [
    { en: "Bright", es_m_s: "brillante", es_f_s: "brillante", es_m_p: "brillantes", es_f_p: "brillantes", ko: koAdj("밝은") },
    { en: "Dark", es_m_s: "oscuro", es_f_s: "oscura", es_m_p: "oscuros", es_f_p: "oscuras", ko: koAdj("어두운") },
    { en: "Glowing", es_m_s: "resplandeciente", es_f_s: "resplandeciente", es_m_p: "resplandecientes", es_f_p: "resplandecientes", ko: koAdj("은은한") },
    { en: "Shining", es_m_s: "reluciente", es_f_s: "reluciente", es_m_p: "relucientes", es_f_p: "relucientes", ko: koAdj("빛나는") },
    { en: "Sparkling", es_m_s: "chispeante", es_f_s: "chispeante", es_m_p: "chispeantes", es_f_p: "chispeantes", ko: koAdj("반짝이는") },
    { en: "Radiant", es_m_s: "radiante", es_f_s: "radiante", es_m_p: "radiantes", es_f_p: "radiantes", ko: koAdj("찬란한") },
    { en: "Luminous", es_m_s: "luminoso", es_f_s: "luminosa", es_m_p: "luminosos", es_f_p: "luminosas", ko: koAdj("발광하는") },
    { en: "Glittering", es_m_s: "centelleante", es_f_s: "centelleante", es_m_p: "centelleantes", es_f_p: "centelleantes", ko: koAdj("번쩍이는") },
    { en: "Neon", es_m_s: "de neón", es_f_s: "de neón", es_m_p: "de neón", es_f_p: "de neón", ko: koAdj("네온") },
    { en: "Lit", es_m_s: "iluminado", es_f_s: "iluminada", es_m_p: "iluminados", es_f_p: "iluminadas", ko: koAdj("조명된") },
    { en: "Shadowy", es_m_s: "sombrío", es_f_s: "sombría", es_m_p: "sombríos", es_f_p: "sombrías", ko: koAdj("그늘진") },
    { en: "Dazzling", es_m_s: "deslumbrante", es_f_s: "deslumbrante", es_m_p: "deslumbrantes", es_f_p: "deslumbrantes", ko: koAdj("눈부신") },
    { en: "Gleaming", es_m_s: "fulgurante", es_f_s: "fulgurante", es_m_p: "fulgurantes", es_f_p: "fulgurantes", ko: koAdj("윤나는") },
    { en: "Twinkling", es_m_s: "titilante", es_f_s: "titilante", es_m_p: "titilantes", es_f_p: "titilantes", ko: koAdj("깜박이는") },
    { en: "Flashing", es_m_s: "parpadeante", es_f_s: "parpadeante", es_m_p: "parpadeantes", es_f_p: "parpadeantes", ko: koAdj("번쩍이는") },
    { en: "Flickering", es_m_s: "intermitente", es_f_s: "intermitente", es_m_p: "intermitentes", es_f_p: "intermitentes", ko: koAdj("일렁이는") },
    { en: "Soft-lit", es_m_s: "tenue", es_f_s: "tenue", es_m_p: "tenues", es_f_p: "tenues", ko: koAdj("은은한") },
    { en: "Blazing", es_m_s: "incandescente", es_f_s: "incandescente", es_m_p: "incandescentes", es_f_p: "incandescentes", ko: koAdj("타오르는") },
    { en: "Clear", es_m_s: "claro", es_f_s: "clara", es_m_p: "claros", es_f_p: "claras", ko: koAdj("맑은") },
    { en: "Vivid", es_m_s: "vivo", es_f_s: "viva", es_m_p: "vivos", es_f_p: "vivas", ko: koAdj("선명한") }
  ],
  temperature: [
    { en: "Hot", es_m_s: "caliente", es_f_s: "caliente", es_m_p: "calientes", es_f_p: "calientes", ko: koAdj("뜨거운") },
    { en: "Cold", es_m_s: "frío", es_f_s: "fría", es_m_p: "fríos", es_f_p: "frías", ko: koAdj("차가운") },
    { en: "Warm", es_m_s: "cálido", es_f_s: "cálida", es_m_p: "cálidos", es_f_p: "cálidas", ko: koAdj("따뜻한") },
    { en: "Cool", es_m_s: "fresco", es_f_s: "fresca", es_m_p: "frescos", es_f_p: "frescas", ko: koAdj("시원한") },
    { en: "Icy", es_m_s: "helado", es_f_s: "helada", es_m_p: "helados", es_f_p: "heladas", ko: koAdj("얼음 같은") },
    { en: "Frozen", es_m_s: "congelado", es_f_s: "congelada", es_m_p: "congelados", es_f_p: "congeladas", ko: koAdj("얼어붙은") },
    { en: "Chilly", es_m_s: "gélido", es_f_s: "gélida", es_m_p: "gélidos", es_f_p: "gélidas", ko: koAdj("쌀쌀한") },
    { en: "Frosty", es_m_s: "escarchado", es_f_s: "escarchada", es_m_p: "escarchados", es_f_p: "escarchadas", ko: koAdj("서리 낀") },
    { en: "Steamy", es_m_s: "humeante", es_f_s: "humeante", es_m_p: "humeantes", es_f_p: "humeantes", ko: koAdj("김이 나는") },
    { en: "Boiling", es_m_s: "hirviente", es_f_s: "hirviente", es_m_p: "hirvientes", es_f_p: "hirvientes", ko: koAdj("끓는") },
    { en: "Scorching", es_m_s: "abrasador", es_f_s: "abrasadora", es_m_p: "abrasadores", es_f_p: "abrasadoras", ko: koAdj("타는 듯한") },
    { en: "Fiery", es_m_s: "ardiente", es_f_s: "ardiente", es_m_p: "ardientes", es_f_p: "ardientes", ko: koAdj("불타는") },
    { en: "Burning", es_m_s: "quemante", es_f_s: "quemante", es_m_p: "quemantes", es_f_p: "quemantes", ko: koAdj("작열하는") },
    { en: "Sizzling", es_m_s: "chisporroteante", es_f_s: "chisporroteante", es_m_p: "chisporroteantes", es_f_p: "chisporroteantes", ko: koAdj("지글지글한") },
    { en: "Mild", es_m_s: "templado", es_f_s: "templada", es_m_p: "templados", es_f_p: "templadas", ko: koAdj("온화한") },
    { en: "Crisp", es_m_s: "cortante", es_f_s: "cortante", es_m_p: "cortantes", es_f_p: "cortantes", ko: koAdj("상쾌한") },
    { en: "Sweltering", es_m_s: "sofocante", es_f_s: "sofocante", es_m_p: "sofocantes", es_f_p: "sofocantes", ko: koAdj("무더운") },
    { en: "Arctic", es_m_s: "ártico", es_f_s: "ártica", es_m_p: "árticos", es_f_p: "árticas", ko: koAdj("북극의") },
    { en: "Tropical", es_m_s: "tropical", es_f_s: "tropical", es_m_p: "tropicales", es_f_p: "tropicales", ko: koAdj("열대의") },
    { en: "Heated", es_m_s: "recalentado", es_f_s: "recalentada", es_m_p: "recalentados", es_f_p: "recalentadas", ko: koAdj("달아오른") }
  ],
  texture: [
    { en: "Soft", es_m_s: "suave", es_f_s: "suave", es_m_p: "suaves", es_f_p: "suaves", ko: koAdj("부드러운") },
    { en: "Rough", es_m_s: "áspero", es_f_s: "áspera", es_m_p: "ásperos", es_f_p: "ásperas", ko: koAdj("거친") },
    { en: "Smooth", es_m_s: "liso", es_f_s: "lisa", es_m_p: "lisos", es_f_p: "lisas", ko: koAdj("매끈한") },
    { en: "Hard", es_m_s: "duro", es_f_s: "dura", es_m_p: "duros", es_f_p: "duras", ko: koAdj("단단한") },
    { en: "Fluffy", es_m_s: "esponjoso", es_f_s: "esponjosa", es_m_p: "esponjosos", es_f_p: "esponjosas", ko: koAdj("폭신한") },
    { en: "Fuzzy", es_m_s: "peludo", es_f_s: "peluda", es_m_p: "peludos", es_f_p: "peludas", ko: koAdj("보송보송한") },
    { en: "Silky", es_m_s: "sedoso", es_f_s: "sedosa", es_m_p: "sedosos", es_f_p: "sedosas", ko: koAdj("비단결 같은") },
    { en: "Velvety", es_m_s: "aterciopelado", es_f_s: "aterciopelada", es_m_p: "aterciopelados", es_f_p: "aterciopeladas", ko: koAdj("벨벳 같은") },
    { en: "Sticky", es_m_s: "pegajoso", es_f_s: "pegajosa", es_m_p: "pegajosos", es_f_p: "pegajosas", ko: koAdj("끈적한") },
    { en: "Slippery", es_m_s: "resbaladizo", es_f_s: "resbaladiza", es_m_p: "resbaladizos", es_f_p: "resbaladizas", ko: koAdj("미끄러운") },
    { en: "Slick", es_m_s: "deslizante", es_f_s: "deslizante", es_m_p: "deslizantes", es_f_p: "deslizantes", ko: koAdj("미끈한") },
    { en: "Gritty", es_m_s: "arenoso", es_f_s: "arenosa", es_m_p: "arenosos", es_f_p: "arenosas", ko: koAdj("까슬까슬한") },
    { en: "Glossy", es_m_s: "lustroso", es_f_s: "lustrosa", es_m_p: "lustrosos", es_f_p: "lustrosas", ko: koAdj("윤기 있는") },
    { en: "Matte", es_m_s: "mate", es_f_s: "mate", es_m_p: "mates", es_f_p: "mates", ko: koAdj("무광의") },
    { en: "Woven", es_m_s: "tejido", es_f_s: "tejida", es_m_p: "tejidos", es_f_p: "tejidas", ko: koAdj("짜인") },
    { en: "Knitted", es_m_s: "de punto", es_f_s: "de punto", es_m_p: "de punto", es_f_p: "de punto", ko: koAdj("뜨개질한") },
    { en: "Spiky", es_m_s: "con púas", es_f_s: "con púas", es_m_p: "con púas", es_f_p: "con púas", ko: koAdj("뾰족한") },
    { en: "Prickly", es_m_s: "espinoso", es_f_s: "espinosa", es_m_p: "espinosos", es_f_p: "espinosas", ko: koAdj("가시돋친") },
    { en: "Bumpy", es_m_s: "abultado", es_f_s: "abultada", es_m_p: "abultados", es_f_p: "abultadas", ko: koAdj("울퉁불퉁한") },
    { en: "Dusty", es_m_s: "polvoriento", es_f_s: "polvorienta", es_m_p: "polvorientos", es_f_p: "polvorientas", ko: koAdj("먼지 낀") }
  ],
  material_substance: [
    { en: "Wooden", es_m_s: "de madera", es_f_s: "de madera", es_m_p: "de madera", es_f_p: "de madera", ko: koAdj("나무") },
    { en: "Metallic", es_m_s: "metálico", es_f_s: "metálica", es_m_p: "metálicos", es_f_p: "metálicas", ko: koAdj("금속") },
    { en: "Glass", es_m_s: "de vidrio", es_f_s: "de vidrio", es_m_p: "de vidrio", es_f_p: "de vidrio", ko: koAdj("유리") },
    { en: "Stone", es_m_s: "de piedra", es_f_s: "de piedra", es_m_p: "de piedra", es_f_p: "de piedra", ko: koAdj("돌") },
    { en: "Paper", es_m_s: "de papel", es_f_s: "de papel", es_m_p: "de papel", es_f_p: "de papel", ko: koAdj("종이") },
    { en: "Plastic", es_m_s: "de plástico", es_f_s: "de plástico", es_m_p: "de plástico", es_f_p: "de plástico", ko: koAdj("플라스틱") },
    { en: "Leather", es_m_s: "de cuero", es_f_s: "de cuero", es_m_p: "de cuero", es_f_p: "de cuero", ko: koAdj("가죽") },
    { en: "Cotton", es_m_s: "de algodón", es_f_s: "de algodón", es_m_p: "de algodón", es_f_p: "de algodón", ko: koAdj("면") },
    { en: "Woolen", es_m_s: "de lana", es_f_s: "de lana", es_m_p: "de lana", es_f_p: "de lana", ko: koAdj("울") },
    { en: "Silken", es_m_s: "de seda", es_f_s: "de seda", es_m_p: "de seda", es_f_p: "de seda", ko: koAdj("비단") },
    { en: "Ceramic", es_m_s: "cerámico", es_f_s: "cerámica", es_m_p: "cerámicos", es_f_p: "cerámicas", ko: koAdj("도자기") },
    { en: "Rubber", es_m_s: "de goma", es_f_s: "de goma", es_m_p: "de goma", es_f_p: "de goma", ko: koAdj("고무") },
    { en: "Carbon", es_m_s: "de carbono", es_f_s: "de carbono", es_m_p: "de carbono", es_f_p: "de carbono", ko: koAdj("탄소") },
    { en: "Steel", es_m_s: "de acero", es_f_s: "de acero", es_m_p: "de acero", es_f_p: "de acero", ko: koAdj("강철") },
    { en: "Copper", es_m_s: "de cobre", es_f_s: "de cobre", es_m_p: "de cobre", es_f_p: "de cobre", ko: koAdj("구리") },
    { en: "Marble", es_m_s: "de mármol", es_f_s: "de mármol", es_m_p: "de mármol", es_f_p: "de mármol", ko: koAdj("대리석") },
    { en: "Clay", es_m_s: "de arcilla", es_f_s: "de arcilla", es_m_p: "de arcilla", es_f_p: "de arcilla", ko: koAdj("흙") },
    { en: "Inked", es_m_s: "entintado", es_f_s: "entintada", es_m_p: "entintados", es_f_p: "entintadas", ko: koAdj("잉크 묻은") },
    { en: "Painted", es_m_s: "pintado", es_f_s: "pintada", es_m_p: "pintados", es_f_p: "pintadas", ko: koAdj("칠한") },
    { en: "Waxy", es_m_s: "encerado", es_f_s: "encerada", es_m_p: "encerados", es_f_p: "enceradas", ko: koAdj("왁스 바른") }
  ],
  size_scale: [
    { en: "Big", es_m_s: "grande", es_f_s: "grande", es_m_p: "grandes", es_f_p: "grandes", ko: koAdj("큰") },
    { en: "Small", es_m_s: "pequeño", es_f_s: "pequeña", es_m_p: "pequeños", es_f_p: "pequeñas", ko: koAdj("작은") },
    { en: "Tiny", es_m_s: "diminuto", es_f_s: "diminuta", es_m_p: "diminutos", es_f_p: "diminutas", ko: koAdj("조그만") },
    { en: "Huge", es_m_s: "enorme", es_f_s: "enorme", es_m_p: "enormes", es_f_p: "enormes", ko: koAdj("거대한") },
    { en: "Giant", es_m_s: "gigante", es_f_s: "gigante", es_m_p: "gigantes", es_f_p: "gigantes", ko: koAdj("거인 같은") },
    { en: "Large", es_m_s: "amplio", es_f_s: "amplia", es_m_p: "amplios", es_f_p: "amplias", ko: koAdj("커다란") },
    { en: "Little", es_m_s: "chico", es_f_s: "chica", es_m_p: "chicos", es_f_p: "chicas", ko: koAdj("아담한") },
    { en: "Massive", es_m_s: "masivo", es_f_s: "masiva", es_m_p: "masivos", es_f_p: "masivas", ko: koAdj("막대한") },
    { en: "Mini", es_m_s: "mini", es_f_s: "mini", es_m_p: "mini", es_f_p: "mini", ko: koAdj("미니") },
    { en: "Micro", es_m_s: "micro", es_f_s: "micro", es_m_p: "micro", es_f_p: "micro", ko: koAdj("마이크로") },
    { en: "Wide", es_m_s: "ancho", es_f_s: "ancha", es_m_p: "anchos", es_f_p: "anchas", ko: koAdj("넓은") },
    { en: "Narrow", es_m_s: "estrecho", es_f_s: "estrecha", es_m_p: "estrechos", es_f_p: "estrechas", ko: koAdj("좁은") },
    { en: "Thick", es_m_s: "grueso", es_f_s: "gruesa", es_m_p: "gruesos", es_f_p: "gruesas", ko: koAdj("두꺼운") },
    { en: "Thin", es_m_s: "delgado", es_f_s: "delgada", es_m_p: "delgados", es_f_p: "delgadas", ko: koAdj("얇은") },
    { en: "Heavy", es_m_s: "pesado", es_f_s: "pesada", es_m_p: "pesados", es_f_p: "pesadas", ko: koAdj("무거운") },
    { en: "Light", es_m_s: "ligero", es_f_s: "ligera", es_m_p: "ligeros", es_f_p: "ligeras", ko: koAdj("가벼운") },
    { en: "Compact", es_m_s: "compacto", es_f_s: "compacta", es_m_p: "compactos", es_f_p: "compactas", ko: koAdj("컴팩트한") },
    { en: "Bulky", es_m_s: "voluminoso", es_f_s: "voluminosa", es_m_p: "voluminosos", es_f_p: "voluminosas", ko: koAdj("부피 큰") },
    { en: "Tall", es_m_s: "alto", es_f_s: "alta", es_m_p: "altos", es_f_p: "altas", ko: koAdj("높은") },
    { en: "Short", es_m_s: "bajo", es_f_s: "baja", es_m_p: "bajos", es_f_p: "bajas", ko: koAdj("낮은") }
  ],
  shape_geometry: [
    { en: "Round", es_m_s: "redondo", es_f_s: "redonda", es_m_p: "redondos", es_f_p: "redondas", ko: koAdj("둥근") },
    { en: "Square", es_m_s: "cuadrado", es_f_s: "cuadrada", es_m_p: "cuadrados", es_f_p: "cuadradas", ko: koAdj("네모난") },
    { en: "Triangular", es_m_s: "triangular", es_f_s: "triangular", es_m_p: "triangulares", es_f_p: "triangulares", ko: koAdj("삼각형의") },
    { en: "Oval", es_m_s: "oval", es_f_s: "oval", es_m_p: "ovales", es_f_p: "ovales", ko: koAdj("타원형의") },
    { en: "Flat", es_m_s: "plano", es_f_s: "plana", es_m_p: "planos", es_f_p: "planas", ko: koAdj("평평한") },
    { en: "Curved", es_m_s: "curvo", es_f_s: "curva", es_m_p: "curvos", es_f_p: "curvas", ko: koAdj("굽은") },
    { en: "Straight", es_m_s: "recto", es_f_s: "recta", es_m_p: "rectos", es_f_p: "rectas", ko: koAdj("곧은") },
    { en: "Angular", es_m_s: "angular", es_f_s: "angular", es_m_p: "angulares", es_f_p: "angulares", ko: koAdj("각진") },
    { en: "Pointed", es_m_s: "puntiagudo", es_f_s: "puntiaguda", es_m_p: "puntiagudos", es_f_p: "puntiagudas", ko: koAdj("뾰족한") },
    { en: "Sharp", es_m_s: "afilado", es_f_s: "afilada", es_m_p: "afilados", es_f_p: "afiladas", ko: koAdj("날카로운") },
    { en: "Spiral", es_m_s: "espiral", es_f_s: "espiral", es_m_p: "espirales", es_f_p: "espirales", ko: koAdj("나선형의") },
    { en: "Wavy", es_m_s: "ondulado", es_f_s: "ondulada", es_m_p: "ondulados", es_f_p: "onduladas", ko: koAdj("물결치는") },
    { en: "Zigzag", es_m_s: "en zigzag", es_f_s: "en zigzag", es_m_p: "en zigzag", es_f_p: "en zigzag", ko: koAdj("지그재그의") },
    { en: "Jagged", es_m_s: "dentado", es_f_s: "dentada", es_m_p: "dentados", es_f_p: "dentadas", ko: koAdj("들쭉날쭉한") },
    { en: "Hollow", es_m_s: "hueco", es_f_s: "hueca", es_m_p: "huecos", es_f_p: "huecas", ko: koAdj("속이 빈") },
    { en: "Solid", es_m_s: "macizo", es_f_s: "maciza", es_m_p: "macizos", es_f_p: "macizas", ko: koAdj("꽉 찬") },
    { en: "Bent", es_m_s: "doblado", es_f_s: "doblada", es_m_p: "doblados", es_f_p: "dobladas", ko: koAdj("휘어진") },
    { en: "Twisted", es_m_s: "retorcido", es_f_s: "retorcida", es_m_p: "retorcidos", es_f_p: "retorcidas", ko: koAdj("꼬인") },
    { en: "Faceted", es_m_s: "facetado", es_f_s: "facetada", es_m_p: "facetados", es_f_p: "facetadas", ko: koAdj("다각면의") },
    { en: "Layered", es_m_s: "en capas", es_f_s: "en capas", es_m_p: "en capas", es_f_p: "en capas", ko: koAdj("겹겹이 쌓인") }
  ],
  speed_motion: [
    { en: "Fast", es_m_s: "rápido", es_f_s: "rápida", es_m_p: "rápidos", es_f_p: "rápidas", ko: koAdj("빠른") },
    { en: "Slow", es_m_s: "lento", es_f_s: "lenta", es_m_p: "lentos", es_f_p: "lentas", ko: koAdj("느린") },
    { en: "Swift", es_m_s: "veloz", es_f_s: "veloz", es_m_p: "veloces", es_f_p: "veloces", ko: koAdj("날쌘") },
    { en: "Quick", es_m_s: "ágil", es_f_s: "ágil", es_m_p: "ágiles", es_f_p: "ágiles", ko: koAdj("민첩한") },
    { en: "Steady", es_m_s: "constante", es_f_s: "constante", es_m_p: "constantes", es_f_p: "constantes", ko: koAdj("꾸준한") },
    { en: "Racing", es_m_s: "acelerado", es_f_s: "acelerada", es_m_p: "acelerados", es_f_p: "aceleradas", ko: koAdj("질주하는") },
    { en: "Flying", es_m_s: "volador", es_f_s: "voladora", es_m_p: "voladores", es_f_p: "voladoras", ko: koAdj("나는") },
    { en: "Drifting", es_m_s: "a la deriva", es_f_s: "a la deriva", es_m_p: "a la deriva", es_f_p: "a la deriva", ko: koAdj("떠다니는") },
    { en: "Rolling", es_m_s: "rodante", es_f_s: "rodante", es_m_p: "rodantes", es_f_p: "rodantes", ko: koAdj("구르는") },
    { en: "Spinning", es_m_s: "giratorio", es_f_s: "giratoria", es_m_p: "giratorios", es_f_p: "giratorias", ko: koAdj("빙글도는") },
    { en: "Sliding", es_m_s: "deslizante", es_f_s: "deslizante", es_m_p: "deslizantes", es_f_p: "deslizantes", ko: koAdj("미끄러지는") },
    { en: "Gliding", es_m_s: "planeador", es_f_s: "planeadora", es_m_p: "planeadores", es_f_p: "planeadoras", ko: koAdj("활공하는") },
    { en: "Leaping", es_m_s: "saltador", es_f_s: "saltadora", es_m_p: "saltadores", es_f_p: "saltadoras", ko: koAdj("뛰어오르는") },
    { en: "Marching", es_m_s: "en marcha", es_f_s: "en marcha", es_m_p: "en marcha", es_f_p: "en marcha", ko: koAdj("행진하는") },
    { en: "Wandering", es_m_s: "errante", es_f_s: "errante", es_m_p: "errantes", es_f_p: "errantes", ko: koAdj("방황하는") },
    { en: "Roaming", es_m_s: "viajero", es_f_s: "viajera", es_m_p: "viajeros", es_f_p: "viajeras", ko: koAdj("돌아다니는") },
    { en: "Flowing", es_m_s: "fluido", es_f_s: "fluida", es_m_p: "fluidos", es_f_p: "fluidas", ko: koAdj("흐르는") },
    { en: "Shaking", es_m_s: "tembloroso", es_f_s: "temblorosa", es_m_p: "temblorosos", es_f_p: "temblorosas", ko: koAdj("흔들리는") },
    { en: "Floating", es_m_s: "flotante", es_f_s: "flotante", es_m_p: "flotantes", es_f_p: "flotantes", ko: koAdj("부유하는") },
    { en: "Surging", es_m_s: "impetuoso", es_f_s: "impetuosa", es_m_p: "impetuosos", es_f_p: "impetuosas", ko: koAdj("솟구치는") }
  ],
  strength_power: [
    { en: "Strong", es_m_s: "fuerte", es_f_s: "fuerte", es_m_p: "fuertes", es_f_p: "fuertes", ko: koAdj("강한") },
    { en: "Weak", es_m_s: "débil", es_f_s: "débil", es_m_p: "débiles", es_f_p: "débiles", ko: koAdj("약한") },
    { en: "Powerful", es_m_s: "poderoso", es_f_s: "poderosa", es_m_p: "poderosos", es_f_p: "poderosas", ko: koAdj("강력한") },
    { en: "Gentle", es_m_s: "gentil", es_f_s: "gentil", es_m_p: "gentiles", es_f_p: "gentiles", ko: koAdj("온화한") },
    { en: "Tough", es_m_s: "tenaz", es_f_s: "tenaz", es_m_p: "tenaces", es_f_p: "tenaces", ko: koAdj("질긴") },
    { en: "Brave", es_m_s: "valiente", es_f_s: "valiente", es_m_p: "valientes", es_f_p: "valientes", ko: koAdj("용감한") },
    { en: "Fierce", es_m_s: "feroz", es_f_s: "feroz", es_m_p: "feroces", es_f_p: "feroces", ko: koAdj("사나운") },
    { en: "Mighty", es_m_s: "formidable", es_f_s: "formidable", es_m_p: "formidables", es_f_p: "formidables", ko: koAdj("위대한") },
    { en: "Sturdy", es_m_s: "robusto", es_f_s: "robusta", es_m_p: "robustos", es_f_p: "robustas", ko: koAdj("튼튼한") },
    { en: "Resilient", es_m_s: "resistente", es_f_s: "resistente", es_m_p: "resistentes", es_f_p: "resistentes", ko: koAdj("탄력 있는") },
    { en: "Durable", es_m_s: "duradero", es_f_s: "duradera", es_m_p: "duraderos", es_f_p: "duraderas", ko: koAdj("내구성 있는") },
    { en: "Unbreakable", es_m_s: "irrompible", es_f_s: "irrompible", es_m_p: "irrompibles", es_f_p: "irrompibles", ko: koAdj("부서지지 않는") },
    { en: "Fragile", es_m_s: "frágil", es_f_s: "frágil", es_m_p: "frágiles", es_f_p: "frágiles", ko: koAdj("부서지기 쉬운") },
    { en: "Flexible", es_m_s: "flexible", es_f_s: "flexible", es_m_p: "flexibles", es_f_p: "flexibles", ko: koAdj("유연한") },
    { en: "Rigid", es_m_s: "rígido", es_f_s: "rígida", es_m_p: "rígidos", es_f_p: "rígidas", ko: koAdj("단단히 굳은") },
    { en: "Bold", es_m_s: "audaz", es_f_s: "audaz", es_m_p: "audaces", es_f_p: "audaces", ko: koAdj("대담한") },
    { en: "Fearless", es_m_s: "intrépido", es_f_s: "intrépida", es_m_p: "intrépidos", es_f_p: "intrépidas", ko: koAdj("두려움 없는") },
    { en: "Determined", es_m_s: "decidido", es_f_s: "decidida", es_m_p: "decididos", es_f_p: "decididas", ko: koAdj("결의에 찬") },
    { en: "Firm", es_m_s: "firme", es_f_s: "firme", es_m_p: "firmes", es_f_p: "firmes", ko: koAdj("단호한") },
    { en: "Solid", es_m_s: "macizo", es_f_s: "maciza", es_m_p: "macizos", es_f_p: "macizas", ko: koAdj("묵직한") }
  ],
  calm_intense: [
    { en: "Calm", es_m_s: "tranquilo", es_f_s: "tranquila", es_m_p: "tranquilos", es_f_p: "tranquilas", ko: koAdj("차분한") },
    { en: "Quiet", es_m_s: "silencioso", es_f_s: "silenciosa", es_m_p: "silenciosos", es_f_p: "silenciosas", ko: koAdj("조용한") },
    { en: "Peaceful", es_m_s: "pacífico", es_f_s: "pacífica", es_m_p: "pacíficos", es_f_p: "pacíficas", ko: koAdj("평화로운") },
    { en: "Serene", es_m_s: "sereno", es_f_s: "serena", es_m_p: "serenos", es_f_p: "serenas", ko: koAdj("고요한") },
    { en: "Relaxed", es_m_s: "relajado", es_f_s: "relajada", es_m_p: "relajados", es_f_p: "relajadas", ko: koAdj("느긋한") },
    { en: "Mellow", es_m_s: "apacible", es_f_s: "apacible", es_m_p: "apacibles", es_f_p: "apacibles", ko: koAdj("잔잔한") },
    { en: "Chill", es_m_s: "desenfadado", es_f_s: "desenfadada", es_m_p: "desenfadados", es_f_p: "desenfadadas", ko: koAdj("여유로운") },
    { en: "Wild", es_m_s: "salvaje", es_f_s: "salvaje", es_m_p: "salvajes", es_f_p: "salvajes", ko: koAdj("거친") },
    { en: "Loud", es_m_s: "ruidoso", es_f_s: "ruidosa", es_m_p: "ruidosos", es_f_p: "ruidosas", ko: koAdj("시끄러운") },
    { en: "Intense", es_m_s: "intenso", es_f_s: "intensa", es_m_p: "intensos", es_f_p: "intensas", ko: koAdj("강렬한") },
    { en: "Dramatic", es_m_s: "dramático", es_f_s: "dramática", es_m_p: "dramáticos", es_f_p: "dramáticas", ko: koAdj("극적인") },
    { en: "Energetic", es_m_s: "enérgico", es_f_s: "enérgica", es_m_p: "enérgicos", es_f_p: "enérgicas", ko: koAdj("활기찬") },
    { en: "Restless", es_m_s: "inquieto", es_f_s: "inquieta", es_m_p: "inquietos", es_f_p: "inquietas", ko: koAdj("안절부절못하는") },
    { en: "Moody", es_m_s: "cambiante", es_f_s: "cambiante", es_m_p: "cambiantes", es_f_p: "cambiantes", ko: koAdj("변덕스러운") },
    { en: "Frenzied", es_m_s: "frenético", es_f_s: "frenética", es_m_p: "frenéticos", es_f_p: "frenéticas", ko: koAdj("광란의") },
    { en: "Furious", es_m_s: "furioso", es_f_s: "furiosa", es_m_p: "furiosos", es_f_p: "furiosas", ko: koAdj("분노한") },
    { en: "Solemn", es_m_s: "solemne", es_f_s: "solemne", es_m_p: "solemnes", es_f_p: "solemnes", ko: koAdj("엄숙한") },
    { en: "Cheerful", es_m_s: "alegre", es_f_s: "alegre", es_m_p: "alegres", es_f_p: "alegres", ko: koAdj("명랑한") },
    { en: "Brooding", es_m_s: "taciturno", es_f_s: "taciturna", es_m_p: "taciturnos", es_f_p: "taciturnas", ko: koAdj("음울한") },
    { en: "Lively", es_m_s: "animado", es_f_s: "animada", es_m_p: "animados", es_f_p: "animadas", ko: koAdj("생기넘치는") }
  ],
  weather_sky: [
    { en: "Sunny", es_m_s: "soleado", es_f_s: "soleada", es_m_p: "soleados", es_f_p: "soleadas", ko: koAdj("화창한") },
    { en: "Cloudy", es_m_s: "nublado", es_f_s: "nublada", es_m_p: "nublados", es_f_p: "nubladas", ko: koAdj("흐린") },
    { en: "Stormy", es_m_s: "tormentoso", es_f_s: "tormentosa", es_m_p: "tormentosos", es_f_p: "tormentosas", ko: koAdj("폭풍우 치는") },
    { en: "Windy", es_m_s: "ventoso", es_f_s: "ventosa", es_m_p: "ventosos", es_f_p: "ventosas", ko: koAdj("바람 부는") },
    { en: "Rainy", es_m_s: "lluvioso", es_f_s: "lluviosa", es_m_p: "lluviosos", es_f_p: "lluviosas", ko: koAdj("비 오는") },
    { en: "Snowy", es_m_s: "nevado", es_f_s: "nevada", es_m_p: "nevados", es_f_p: "nevadas", ko: koAdj("눈 오는") },
    { en: "Foggy", es_m_s: "neblinoso", es_f_s: "neblinosa", es_m_p: "neblinosos", es_f_p: "neblinosas", ko: koAdj("안개 낀") },
    { en: "Misty", es_m_s: "brumoso", es_f_s: "brumosa", es_m_p: "brumosos", es_f_p: "brumosas", ko: koAdj("옅은 안개 낀") },
    { en: "Clear", es_m_s: "despejado", es_f_s: "despejada", es_m_p: "despejados", es_f_p: "despejadas", ko: koAdj("맑은") },
    { en: "Overcast", es_m_s: "encapotado", es_f_s: "encapotada", es_m_p: "encapotados", es_f_p: "encapotadas", ko: koAdj("구름 낀") },
    { en: "Breezy", es_m_s: "con brisa", es_f_s: "con brisa", es_m_p: "con brisa", es_f_p: "con brisa", ko: koAdj("산들바람 부는") },
    { en: "Thunderous", es_m_s: "atronador", es_f_s: "atronadora", es_m_p: "atronadores", es_f_p: "atronadoras", ko: koAdj("천둥치는") },
    { en: "Hazy", es_m_s: "borroso", es_f_s: "borrosa", es_m_p: "borrosos", es_f_p: "borrosas", ko: koAdj("희뿌연") },
    { en: "Gusty", es_m_s: "racheado", es_f_s: "racheada", es_m_p: "racheados", es_f_p: "racheadas", ko: koAdj("돌풍 부는") },
    { en: "Drizzly", es_m_s: "lloviznoso", es_f_s: "lloviznosa", es_m_p: "lloviznosos", es_f_p: "lloviznosas", ko: koAdj("이슬비 내리는") },
    { en: "Humid", es_m_s: "húmedo", es_f_s: "húmeda", es_m_p: "húmedos", es_f_p: "húmedas", ko: koAdj("습한") },
    { en: "Dry", es_m_s: "seco", es_f_s: "seca", es_m_p: "secos", es_f_p: "secas", ko: koAdj("건조한") },
    { en: "Dewy", es_m_s: "rociado", es_f_s: "rociada", es_m_p: "rociados", es_f_p: "rociadas", ko: koAdj("이슬 맺힌") },
    { en: "Starry", es_m_s: "estrellado", es_f_s: "estrellada", es_m_p: "estrellados", es_f_p: "estrelladas", ko: koAdj("별이 가득한") },
    { en: "Lunar", es_m_s: "lunar", es_f_s: "lunar", es_m_p: "lunares", es_f_p: "lunares", ko: koAdj("달빛의") }
  ],
  time_age: [
    { en: "New", es_m_s: "nuevo", es_f_s: "nueva", es_m_p: "nuevos", es_f_p: "nuevas", ko: koAdj("새로운") },
    { en: "Old", es_m_s: "viejo", es_f_s: "vieja", es_m_p: "viejos", es_f_p: "viejas", ko: koAdj("오래된") },
    { en: "Ancient", es_m_s: "antiguo", es_f_s: "antigua", es_m_p: "antiguos", es_f_p: "antiguas", ko: koAdj("고대의") },
    { en: "Modern", es_m_s: "moderno", es_f_s: "moderna", es_m_p: "modernos", es_f_p: "modernas", ko: koAdj("현대의") },
    { en: "Young", es_m_s: "joven", es_f_s: "joven", es_m_p: "jóvenes", es_f_p: "jóvenes", ko: koAdj("젊은") },
    { en: "Early", es_m_s: "temprano", es_f_s: "temprana", es_m_p: "tempranos", es_f_p: "tempranas", ko: koAdj("이른") },
    { en: "Late", es_m_s: "tardío", es_f_s: "tardía", es_m_p: "tardíos", es_f_p: "tardías", ko: koAdj("늦은") },
    { en: "Fresh", es_m_s: "reciente", es_f_s: "reciente", es_m_p: "recientes", es_f_p: "recientes", ko: koAdj("신선한") },
    { en: "Vintage", es_m_s: "vintage", es_f_s: "vintage", es_m_p: "vintage", es_f_p: "vintage", ko: koAdj("빈티지한") },
    { en: "Classic", es_m_s: "clásico", es_f_s: "clásica", es_m_p: "clásicos", es_f_p: "clásicas", ko: koAdj("클래식한") },
    { en: "Future", es_m_s: "futuro", es_f_s: "futura", es_m_p: "futuros", es_f_p: "futuras", ko: koAdj("미래의") },
    { en: "Timeless", es_m_s: "atemporal", es_f_s: "atemporal", es_m_p: "atemporales", es_f_p: "atemporales", ko: koAdj("영원한") },
    { en: "Seasonal", es_m_s: "estacional", es_f_s: "estacional", es_m_p: "estacionales", es_f_p: "estacionales", ko: koAdj("계절의") },
    { en: "Daily", es_m_s: "diario", es_f_s: "diaria", es_m_p: "diarios", es_f_p: "diarias", ko: koAdj("매일의") },
    { en: "Night", es_m_s: "nocturno", es_f_s: "nocturna", es_m_p: "nocturnos", es_f_p: "nocturnas", ko: koAdj("밤의") },
    { en: "Dawn", es_m_s: "auroral", es_f_s: "auroral", es_m_p: "aurorales", es_f_p: "aurorales", ko: koAdj("새벽의") },
    { en: "Dusk", es_m_s: "vespertino", es_f_s: "vespertina", es_m_p: "vespertinos", es_f_p: "vespertinas", ko: koAdj("황혼의") },
    { en: "First", es_m_s: "primero", es_f_s: "primera", es_m_p: "primeros", es_f_p: "primeras", ko: koAdj("첫") },
    { en: "Last", es_m_s: "último", es_f_s: "última", es_m_p: "últimos", es_f_p: "últimas", ko: koAdj("마지막") },
    { en: "Next", es_m_s: "próximo", es_f_s: "próxima", es_m_p: "próximos", es_f_p: "próximas", ko: koAdj("다음") }
  ],
  nature_ecology: [
    { en: "Wild", es_m_s: "salvaje", es_f_s: "salvaje", es_m_p: "salvajes", es_f_p: "salvajes", ko: koAdj("야생의") },
    { en: "Natural", es_m_s: "natural", es_f_s: "natural", es_m_p: "naturales", es_f_p: "naturales", ko: koAdj("자연의") },
    { en: "Organic", es_m_s: "orgánico", es_f_s: "orgánica", es_m_p: "orgánicos", es_f_p: "orgánicas", ko: koAdj("유기농의") },
    { en: "Leafy", es_m_s: "frondoso", es_f_s: "frondosa", es_m_p: "frondosos", es_f_p: "frondosas", ko: koAdj("잎이 무성한") },
    { en: "Floral", es_m_s: "floral", es_f_s: "floral", es_m_p: "florales", es_f_p: "florales", ko: koAdj("꽃의") },
    { en: "Forest", es_m_s: "forestal", es_f_s: "forestal", es_m_p: "forestales", es_f_p: "forestales", ko: koAdj("숲의") },
    { en: "Garden", es_m_s: "de jardín", es_f_s: "de jardín", es_m_p: "de jardín", es_f_p: "de jardín", ko: koAdj("정원의") },
    { en: "Mountain", es_m_s: "montañoso", es_f_s: "montañosa", es_m_p: "montañosos", es_f_p: "montañosas", ko: koAdj("산의") },
    { en: "River", es_m_s: "ribereño", es_f_s: "ribereña", es_m_p: "ribereños", es_f_p: "ribereñas", ko: koAdj("강의") },
    { en: "Ocean", es_m_s: "oceánico", es_f_s: "oceánica", es_m_p: "oceánicos", es_f_p: "oceánicas", ko: koAdj("바다의") },
    { en: "Sandy", es_m_s: "arenoso", es_f_s: "arenosa", es_m_p: "arenosos", es_f_p: "arenosas", ko: koAdj("모래의") },
    { en: "Rocky", es_m_s: "rocoso", es_f_s: "rocosa", es_m_p: "rocosos", es_f_p: "rocosas", ko: koAdj("바위의") },
    { en: "Mossy", es_m_s: "musgoso", es_f_s: "musgosa", es_m_p: "musgosos", es_f_p: "musgosas", ko: koAdj("이끼 낀") },
    { en: "Blooming", es_m_s: "floreciente", es_f_s: "floreciente", es_m_p: "florecientes", es_f_p: "florecientes", ko: koAdj("꽃피는") },
    { en: "Evergreen", es_m_s: "perenne", es_f_s: "perenne", es_m_p: "perennes", es_f_p: "perennes", ko: koAdj("상록의") },
    { en: "Desert", es_m_s: "desértico", es_f_s: "desértica", es_m_p: "desérticos", es_f_p: "desérticas", ko: koAdj("사막의") },
    { en: "Coastal", es_m_s: "costero", es_f_s: "costera", es_m_p: "costeros", es_f_p: "costeras", ko: koAdj("해안의") },
    { en: "Meadow", es_m_s: "campestre", es_f_s: "campestre", es_m_p: "campestres", es_f_p: "campestres", ko: koAdj("초원의") },
    { en: "Earthy", es_m_s: "terroso", es_f_s: "terrosa", es_m_p: "terrosos", es_f_p: "terrosas", ko: koAdj("흙내나는") },
    { en: "Tidal", es_m_s: "mareal", es_f_s: "mareal", es_m_p: "mareales", es_f_p: "mareales", ko: koAdj("조수의") }
  ],
  luxury_regality: [
    { en: "Royal", es_m_s: "real", es_f_s: "real", es_m_p: "reales", es_f_p: "reales", ko: koAdj("왕실의") },
    { en: "Regal", es_m_s: "regio", es_f_s: "regia", es_m_p: "regios", es_f_p: "regias", ko: koAdj("위엄있는") },
    { en: "Noble", es_m_s: "noble", es_f_s: "noble", es_m_p: "nobles", es_f_p: "nobles", ko: koAdj("고귀한") },
    { en: "Elegant", es_m_s: "elegante", es_f_s: "elegante", es_m_p: "elegantes", es_f_p: "elegantes", ko: koAdj("우아한") },
    { en: "Luxurious", es_m_s: "lujoso", es_f_s: "lujosa", es_m_p: "lujosos", es_f_p: "lujosas", ko: koAdj("호화로운") },
    { en: "Gilded", es_m_s: "chapado en oro", es_f_s: "chapado en oro", es_m_p: "chapado en oro", es_f_p: "chapado en oro", ko: koAdj("금박의") },
    { en: "Velvet", es_m_s: "de terciopelo", es_f_s: "de terciopelo", es_m_p: "de terciopelo", es_f_p: "de terciopelo", ko: koAdj("벨벳의") },
    { en: "Satin", es_m_s: "de satén", es_f_s: "de satén", es_m_p: "de satén", es_f_p: "de satén", ko: koAdj("새틴의") },
    { en: "Jeweled", es_m_s: "enjoyado", es_f_s: "enjoyada", es_m_p: "enjoyados", es_f_p: "enjoyadas", ko: koAdj("보석 장식의") },
    { en: "Precious", es_m_s: "precioso", es_f_s: "preciosa", es_m_p: "preciosos", es_f_p: "preciosas", ko: koAdj("소중한") },
    { en: "Grand", es_m_s: "grandioso", es_f_s: "grandiosa", es_m_p: "grandiosos", es_f_p: "grandiosas", ko: koAdj("웅장한") },
    { en: "Majestic", es_m_s: "majestuoso", es_f_s: "majestuosa", es_m_p: "majestuosos", es_f_p: "majestuosas", ko: koAdj("장엄한") },
    { en: "Opulent", es_m_s: "opulento", es_f_s: "opulenta", es_m_p: "opulentos", es_f_p: "opulentas", ko: koAdj("화려한") },
    { en: "Refined", es_m_s: "refinado", es_f_s: "refinada", es_m_p: "refinados", es_f_p: "refinadas", ko: koAdj("세련된") },
    { en: "Polished", es_m_s: "pulido", es_f_s: "pulida", es_m_p: "pulidos", es_f_p: "pulidas", ko: koAdj("광택 있는") },
    { en: "Ornate", es_m_s: "ornamentado", es_f_s: "ornamentada", es_m_p: "ornamentados", es_f_p: "ornamentadas", ko: koAdj("장식적인") },
    { en: "Premium", es_m_s: "premium", es_f_s: "premium", es_m_p: "premium", es_f_p: "premium", ko: koAdj("프리미엄의") },
    { en: "Imperial", es_m_s: "imperial", es_f_s: "imperial", es_m_p: "imperiales", es_f_p: "imperiales", ko: koAdj("제국의") },
    { en: "Glorious", es_m_s: "glorioso", es_f_s: "gloriosa", es_m_p: "gloriosos", es_f_p: "gloriosas", ko: koAdj("영광스러운") },
    { en: "Exquisite", es_m_s: "exquisito", es_f_s: "exquisita", es_m_p: "exquisitos", es_f_p: "exquisitas", ko: koAdj("정교한") }
  ],
  tech_digital: [
    { en: "Digital", es_m_s: "digital", es_f_s: "digital", es_m_p: "digitales", es_f_p: "digitales", ko: koAdj("디지털") },
    { en: "Analog", es_m_s: "analógico", es_f_s: "analógica", es_m_p: "analógicos", es_f_p: "analógicas", ko: koAdj("아날로그") },
    { en: "Electric", es_m_s: "eléctrico", es_f_s: "eléctrica", es_m_p: "eléctricos", es_f_p: "eléctricas", ko: koAdj("전기의") },
    { en: "Electronic", es_m_s: "electrónico", es_f_s: "electrónica", es_m_p: "electrónicos", es_f_p: "electrónicas", ko: koAdj("전자") },
    { en: "Cyber", es_m_s: "cibernético", es_f_s: "cibernética", es_m_p: "cibernéticos", es_f_p: "cibernéticas", ko: koAdj("사이버") },
    { en: "Virtual", es_m_s: "virtual", es_f_s: "virtual", es_m_p: "virtuales", es_f_p: "virtuales", ko: koAdj("가상의") },
    { en: "Automated", es_m_s: "automatizado", es_f_s: "automatizada", es_m_p: "automatizados", es_f_p: "automatizadas", ko: koAdj("자동화된") },
    { en: "Programmed", es_m_s: "programado", es_f_s: "programada", es_m_p: "programados", es_f_p: "programadas", ko: koAdj("프로그래밍된") },
    { en: "Coded", es_m_s: "codificado", es_f_s: "codificada", es_m_p: "codificados", es_f_p: "codificadas", ko: koAdj("코드화된") },
    { en: "Encrypted", es_m_s: "encriptado", es_f_s: "encriptada", es_m_p: "encriptados", es_f_p: "encriptadas", ko: koAdj("암호화된") },
    { en: "Networked", es_m_s: "conectado", es_f_s: "conectada", es_m_p: "conectados", es_f_p: "conectadas", ko: koAdj("연결된") },
    { en: "Wireless", es_m_s: "inalámbrico", es_f_s: "inalámbrica", es_m_p: "inalámbricos", es_f_p: "inalámbricas", ko: koAdj("무선의") },
    { en: "Modular", es_m_s: "modular", es_f_s: "modular", es_m_p: "modulares", es_f_p: "modulares", ko: koAdj("모듈형의") },
    { en: "Synthetic", es_m_s: "sintético", es_f_s: "sintética", es_m_p: "sintéticos", es_f_p: "sintéticas", ko: koAdj("합성의") },
    { en: "Robotic", es_m_s: "robótico", es_f_s: "robótica", es_m_p: "robóticos", es_f_p: "robóticas", ko: koAdj("로봇의") },
    { en: "Mechanical", es_m_s: "mecánico", es_f_s: "mecánica", es_m_p: "mecánicos", es_f_p: "mecánicas", ko: koAdj("기계의") },
    { en: "Smart", es_m_s: "inteligente", es_f_s: "inteligente", es_m_p: "inteligentes", es_f_p: "inteligentes", ko: koAdj("스마트한") },
    { en: "Data-driven", es_m_s: "basado en datos", es_f_s: "basado en datos", es_m_p: "basado en datos", es_f_p: "basado en datos", ko: koAdj("데이터 기반의") },
    { en: "Pixelated", es_m_s: "pixelado", es_f_s: "pixelada", es_m_p: "pixelados", es_f_p: "pixeladas", ko: koAdj("픽셀의") },
    { en: "Glitched", es_m_s: "con fallos", es_f_s: "con fallos", es_m_p: "con fallos", es_f_p: "con fallos", ko: koAdj("오류가 난") }
  ]
};

const NOUN_CATEGORIES: Record<string, ActNameNoun[]> = {
  animals_general: [
    { en: { s: "Wolf", p: "Wolves" }, es: { gender: "m", s: "lobo", p: "lobos" }, ko: koNoun("늑대", "늑대들") },
    { en: { s: "Fox", p: "Foxes" }, es: { gender: "m", s: "zorro", p: "zorros" }, ko: koNoun("여우", "여우들") },
    { en: { s: "Bear", p: "Bears" }, es: { gender: "m", s: "oso", p: "osos" }, ko: koNoun("곰", "곰들") },
    { en: { s: "Lion", p: "Lions" }, es: { gender: "m", s: "león", p: "leones" }, ko: koNoun("사자", "사자들") },
    { en: { s: "Tiger", p: "Tigers" }, es: { gender: "m", s: "tigre", p: "tigres" }, ko: koNoun("호랑이", "호랑이들") },
    { en: { s: "Horse", p: "Horses" }, es: { gender: "m", s: "caballo", p: "caballos" }, ko: koNoun("말", "말들") },
    { en: { s: "Dog", p: "Dogs" }, es: { gender: "m", s: "perro", p: "perros" }, ko: koNoun("개", "개들") },
    { en: { s: "Cat", p: "Cats" }, es: { gender: "m", s: "gato", p: "gatos" }, ko: koNoun("고양이", "고양이들") },
    { en: { s: "Rabbit", p: "Rabbits" }, es: { gender: "m", s: "conejo", p: "conejos" }, ko: koNoun("토끼", "토끼들") },
    { en: { s: "Squirrel", p: "Squirrels" }, es: { gender: "f", s: "ardilla", p: "ardillas" }, ko: koNoun("다람쥐", "다람쥐들") },
    { en: { s: "Elephant", p: "Elephants" }, es: { gender: "m", s: "elefante", p: "elefantes" }, ko: koNoun("코끼리", "코끼리들") },
    { en: { s: "Giraffe", p: "Giraffes" }, es: { gender: "f", s: "jirafa", p: "jirafas" }, ko: koNoun("기린", "기린들") },
    { en: { s: "Zebra", p: "Zebras" }, es: { gender: "f", s: "cebra", p: "cebras" }, ko: koNoun("얼룩말", "얼룩말들") },
    { en: { s: "Monkey", p: "Monkeys" }, es: { gender: "m", s: "mono", p: "monos" }, ko: koNoun("원숭이", "원숭이들") },
    { en: { s: "Panda", p: "Pandas" }, es: { gender: "m", s: "panda", p: "pandas" }, ko: koNoun("판다", "판다들") },
    { en: { s: "Koala", p: "Koalas" }, es: { gender: "m", s: "koala", p: "koalas" }, ko: koNoun("코알라", "코알라들") },
    { en: { s: "Kangaroo", p: "Kangaroos" }, es: { gender: "m", s: "canguro", p: "canguros" }, ko: koNoun("캥거루", "캥거루들") },
    { en: { s: "Camel", p: "Camels" }, es: { gender: "m", s: "camello", p: "camellos" }, ko: koNoun("낙타", "낙타들") },
    { en: { s: "Goat", p: "Goats" }, es: { gender: "f", s: "cabra", p: "cabras" }, ko: koNoun("염소", "염소들") },
    { en: { s: "Sheep", p: "Sheep" }, es: { gender: "f", s: "oveja", p: "ovejas" }, ko: koNoun("양", "양들") }
  ],
  birds: [
    { en: { s: "Eagle", p: "Eagles" }, es: { gender: "f", s: "águila", p: "águilas" }, ko: koNoun("독수리", "독수리들") },
    { en: { s: "Hawk", p: "Hawks" }, es: { gender: "m", s: "gavilán", p: "gavilanes" }, ko: koNoun("매", "매들") },
    { en: { s: "Owl", p: "Owls" }, es: { gender: "m", s: "búho", p: "búhos" }, ko: koNoun("부엉이", "부엉이들") },
    { en: { s: "Raven", p: "Ravens" }, es: { gender: "m", s: "cuervo", p: "cuervos" }, ko: koNoun("까마귀", "까마귀들") },
    { en: { s: "Swan", p: "Swans" }, es: { gender: "m", s: "cisne", p: "cisnes" }, ko: koNoun("백조", "백조들") },
    { en: { s: "Duck", p: "Ducks" }, es: { gender: "m", s: "pato", p: "patos" }, ko: koNoun("오리", "오리들") },
    { en: { s: "Goose", p: "Geese" }, es: { gender: "m", s: "ganso", p: "gansos" }, ko: koNoun("거위", "거위들") },
    { en: { s: "Pigeon", p: "Pigeons" }, es: { gender: "f", s: "paloma", p: "palomas" }, ko: koNoun("비둘기", "비둘기들") },
    { en: { s: "Sparrow", p: "Sparrows" }, es: { gender: "m", s: "gorrión", p: "gorriones" }, ko: koNoun("참새", "참새들") },
    { en: { s: "Parrot", p: "Parrots" }, es: { gender: "m", s: "loro", p: "loros" }, ko: koNoun("앵무새", "앵무새들") },
    { en: { s: "Penguin", p: "Penguins" }, es: { gender: "m", s: "pingüino", p: "pingüinos" }, ko: koNoun("펭귄", "펭귄들") },
    { en: { s: "Flamingo", p: "Flamingos" }, es: { gender: "m", s: "flamenco", p: "flamencos" }, ko: koNoun("플라밍고", "플라밍고들") },
    { en: { s: "Peacock", p: "Peacocks" }, es: { gender: "m", s: "pavo real", p: "pavos reales" }, ko: koNoun("공작새", "공작새들") },
    { en: { s: "Crane", p: "Cranes" }, es: { gender: "f", s: "grulla", p: "grullas" }, ko: koNoun("두루미", "두루미들") },
    { en: { s: "Heron", p: "Herons" }, es: { gender: "f", s: "garza", p: "garzas" }, ko: koNoun("왜가리", "왜가리들") },
    { en: { s: "Seagull", p: "Seagulls" }, es: { gender: "f", s: "gaviota", p: "gaviotas" }, ko: koNoun("갈매기", "갈매기들") },
    { en: { s: "Woodpecker", p: "Woodpeckers" }, es: { gender: "m", s: "pájaro carpintero", p: "pájaros carpinteros" }, ko: koNoun("딱따구리", "딱따구리들") },
    { en: { s: "Hummingbird", p: "Hummingbirds" }, es: { gender: "m", s: "colibrí", p: "colibríes" }, ko: koNoun("벌새", "벌새들") },
    { en: { s: "Falcon", p: "Falcons" }, es: { gender: "m", s: "halcón", p: "halcones" }, ko: koNoun("송골매", "송골매들") },
    { en: { s: "Dove", p: "Doves" }, es: { gender: "f", s: "tórtola", p: "tórtolas" }, ko: koNoun("산비둘기", "산비둘기들") }
  ],
  sea_creatures: [
    { en: { s: "Shark", p: "Sharks" }, es: { gender: "m", s: "tiburón", p: "tiburones" }, ko: koNoun("상어", "상어들") },
    { en: { s: "Whale", p: "Whales" }, es: { gender: "f", s: "ballena", p: "ballenas" }, ko: koNoun("고래", "고래들") },
    { en: { s: "Dolphin", p: "Dolphins" }, es: { gender: "m", s: "delfín", p: "delfines" }, ko: koNoun("돌고래", "돌고래들") },
    { en: { s: "Octopus", p: "Octopuses" }, es: { gender: "m", s: "pulpo", p: "pulpos" }, ko: koNoun("문어", "문어들") },
    { en: { s: "Squid", p: "Squids" }, es: { gender: "m", s: "calamar", p: "calamares" }, ko: koNoun("오징어", "오징어들") },
    { en: { s: "Seal", p: "Seals" }, es: { gender: "f", s: "foca", p: "focas" }, ko: koNoun("물개", "물개들") },
    { en: { s: "Turtle", p: "Turtles" }, es: { gender: "f", s: "tortuga", p: "tortugas" }, ko: koNoun("거북이", "거북이들") },
    { en: { s: "Crab", p: "Crabs" }, es: { gender: "m", s: "cangrejo", p: "cangrejos" }, ko: koNoun("게", "게들") },
    { en: { s: "Lobster", p: "Lobsters" }, es: { gender: "f", s: "langosta", p: "langostas" }, ko: koNoun("바닷가재", "바닷가재들") },
    { en: { s: "Shrimp", p: "Shrimps" }, es: { gender: "m", s: "camarón", p: "camarones" }, ko: koNoun("새우", "새우들") },
    { en: { s: "Jellyfish", p: "Jellyfish" }, es: { gender: "f", s: "medusa", p: "medusas" }, ko: koNoun("해파리", "해파리들") },
    { en: { s: "Starfish", p: "Starfish" }, es: { gender: "f", s: "estrella de mar", p: "estrellas de mar" }, ko: koNoun("불가사리", "불가사리들") },
    { en: { s: "Seahorse", p: "Seahorses" }, es: { gender: "m", s: "caballito de mar", p: "caballitos de mar" }, ko: koNoun("해마", "해마들") },
    { en: { s: "Ray", p: "Rays" }, es: { gender: "f", s: "raya", p: "rayas" }, ko: koNoun("가오리", "가오리들") },
    { en: { s: "Eel", p: "Eels" }, es: { gender: "f", s: "anguila", p: "anguilas" }, ko: koNoun("장어", "장어들") },
    { en: { s: "Clam", p: "Clams" }, es: { gender: "f", s: "almeja", p: "almejas" }, ko: koNoun("조개", "조개들") },
    { en: { s: "Oyster", p: "Oysters" }, es: { gender: "f", s: "ostra", p: "ostras" }, ko: koNoun("굴", "굴들") },
    { en: { s: "Coral", p: "Corals" }, es: { gender: "m", s: "coral", p: "corales" }, ko: koNoun("산호", "산호들") },
    { en: { s: "Salmon", p: "Salmon" }, es: { gender: "m", s: "salmón", p: "salmones" }, ko: koNoun("연어", "연어들") },
    { en: { s: "Tuna", p: "Tuna" }, es: { gender: "m", s: "atún", p: "atunes" }, ko: koNoun("참치", "참치들") }
  ],
  insects_small: [
    { en: { s: "Bee", p: "Bees" }, es: { gender: "f", s: "abeja", p: "abejas" }, ko: koNoun("벌", "벌들") },
    { en: { s: "Ant", p: "Ants" }, es: { gender: "f", s: "hormiga", p: "hormigas" }, ko: koNoun("개미", "개미들") },
    { en: { s: "Butterfly", p: "Butterflies" }, es: { gender: "f", s: "mariposa", p: "mariposas" }, ko: koNoun("나비", "나비들") },
    { en: { s: "Moth", p: "Moths" }, es: { gender: "f", s: "polilla", p: "polillas" }, ko: koNoun("나방", "나방들") },
    { en: { s: "Spider", p: "Spiders" }, es: { gender: "f", s: "araña", p: "arañas" }, ko: koNoun("거미", "거미들") },
    { en: { s: "Beetle", p: "Beetles" }, es: { gender: "m", s: "escarabajo", p: "escarabajos" }, ko: koNoun("딱정벌레", "딱정벌레들") },
    { en: { s: "Fly", p: "Flies" }, es: { gender: "f", s: "mosca", p: "moscas" }, ko: koNoun("파리", "파리들") },
    { en: { s: "Mosquito", p: "Mosquitoes" }, es: { gender: "m", s: "mosquito", p: "mosquitos" }, ko: koNoun("모기", "모기들") },
    { en: { s: "Dragonfly", p: "Dragonflies" }, es: { gender: "f", s: "libélula", p: "libélulas" }, ko: koNoun("잠자리", "잠자리들") },
    { en: { s: "Ladybug", p: "Ladybugs" }, es: { gender: "f", s: "vaquita de San Antonio", p: "vaquitas de San Antonio" }, ko: koNoun("무당벌레", "무당벌레들") },
    { en: { s: "Worm", p: "Worms" }, es: { gender: "m", s: "gusano", p: "gusanos" }, ko: koNoun("지렁이", "지렁이들") },
    { en: { s: "Snail", p: "Snails" }, es: { gender: "m", s: "caracol", p: "caracoles" }, ko: koNoun("달팽이", "달팽이들") },
    { en: { s: "Cricket", p: "Crickets" }, es: { gender: "m", s: "grillo", p: "grillos" }, ko: koNoun("귀뚜라미", "귀뚜라미들") },
    { en: { s: "Grasshopper", p: "Grasshoppers" }, es: { gender: "m", s: "saltamontes", p: "saltamontes" }, ko: koNoun("메뚜기", "메뚜기들") },
    { en: { s: "Wasp", p: "Wasps" }, es: { gender: "f", s: "avispa", p: "avispas" }, ko: koNoun("말벌", "말벌들") },
    { en: { s: "Caterpillar", p: "Caterpillars" }, es: { gender: "f", s: "oruga", p: "orugas" }, ko: koNoun("애벌레", "애벌레들") },
    { en: { s: "Termite", p: "Termites" }, es: { gender: "f", s: "termita", p: "termitas" }, ko: koNoun("흰개미", "흰개미들") },
    { en: { s: "Scorpion", p: "Scorpions" }, es: { gender: "m", s: "escorpión", p: "escorpiones" }, ko: koNoun("전갈", "전갈들") },
    { en: { s: "Frog", p: "Frogs" }, es: { gender: "f", s: "rana", p: "ranas" }, ko: koNoun("개구리", "개구리들") },
    { en: { s: "Lizard", p: "Lizards" }, es: { gender: "m", s: "lagarto", p: "lagartos" }, ko: koNoun("도마뱀", "도마뱀들") }
  ],
  flowers: [
    { en: { s: "Rose", p: "Roses" }, es: { gender: "f", s: "rosa", p: "rosas" }, ko: koNoun("장미", "장미들") },
    { en: { s: "Tulip", p: "Tulips" }, es: { gender: "m", s: "tulipán", p: "tulipanes" }, ko: koNoun("튤립", "튤립들") },
    { en: { s: "Daisy", p: "Daisies" }, es: { gender: "f", s: "margarita", p: "margaritas" }, ko: koNoun("데이지", "데이지들") },
    { en: { s: "Lily", p: "Lilies" }, es: { gender: "m", s: "lirio", p: "lirios" }, ko: koNoun("백합", "백합들") },
    { en: { s: "Orchid", p: "Orchids" }, es: { gender: "f", s: "orquídea", p: "orquídeas" }, ko: koNoun("난초", "난초들") },
    { en: { s: "Sunflower", p: "Sunflowers" }, es: { gender: "m", s: "girasol", p: "girasoles" }, ko: koNoun("해바라기", "해바라기들") },
    { en: { s: "Violet", p: "Violets" }, es: { gender: "f", s: "violeta", p: "violetas" }, ko: koNoun("제비꽃", "제비꽃들") },
    { en: { s: "Poppy", p: "Poppies" }, es: { gender: "f", s: "amapola", p: "amapolas" }, ko: koNoun("양귀비", "양귀비들") },
    { en: { s: "Peony", p: "Peonies" }, es: { gender: "f", s: "peonía", p: "peonías" }, ko: koNoun("모란", "모란들") },
    { en: { s: "Daffodil", p: "Daffodils" }, es: { gender: "m", s: "narciso", p: "narcisos" }, ko: koNoun("수선화", "수선화들") },
    { en: { s: "Lavender", p: "Lavenders" }, es: { gender: "f", s: "lavanda", p: "lavandas" }, ko: koNoun("라벤더", "라벤더들") },
    { en: { s: "Jasmine", p: "Jasmines" }, es: { gender: "m", s: "jazmín", p: "jazmines" }, ko: koNoun("자스민", "자스민들") },
    { en: { s: "Chrysanthemum", p: "Chrysanthemums" }, es: { gender: "m", s: "crisantemo", p: "crisantemos" }, ko: koNoun("국화", "국화들") },
    { en: { s: "Marigold", p: "Marigolds" }, es: { gender: "f", s: "caléndula", p: "caléndulas" }, ko: koNoun("메리골드", "메리골드들") },
    { en: { s: "Carnation", p: "Carnations" }, es: { gender: "m", s: "clavel", p: "claveles" }, ko: koNoun("카네이션", "카네이션들") },
    { en: { s: "Hydrangea", p: "Hydrangeas" }, es: { gender: "f", s: "hortensia", p: "hortensias" }, ko: koNoun("수국", "수국들") },
    { en: { s: "Magnolia", p: "Magnolias" }, es: { gender: "f", s: "magnolia", p: "magnolias" }, ko: koNoun("목련", "목련들") },
    { en: { s: "Camellia", p: "Camellias" }, es: { gender: "f", s: "camelia", p: "camelias" }, ko: koNoun("동백", "동백들") },
    { en: { s: "Hibiscus", p: "Hibiscuses" }, es: { gender: "m", s: "hibisco", p: "hibiscos" }, ko: koNoun("히비스커스", "히비스커스들") },
    { en: { s: "Lotus", p: "Lotuses" }, es: { gender: "m", s: "loto", p: "lotos" }, ko: koNoun("연꽃", "연꽃들") }
  ],
  trees_woods: [
    { en: { s: "Oak", p: "Oaks" }, es: { gender: "m", s: "roble", p: "robles" }, ko: koNoun("참나무", "참나무들") },
    { en: { s: "Pine", p: "Pines" }, es: { gender: "m", s: "pino", p: "pinos" }, ko: koNoun("소나무", "소나무들") },
    { en: { s: "Maple", p: "Maples" }, es: { gender: "m", s: "arce", p: "arces" }, ko: koNoun("단풍나무", "단풍나무들") },
    { en: { s: "Birch", p: "Birches" }, es: { gender: "m", s: "abedul", p: "abedules" }, ko: koNoun("자작나무", "자작나무들") },
    { en: { s: "Willow", p: "Willows" }, es: { gender: "m", s: "sauce", p: "sauces" }, ko: koNoun("버드나무", "버드나무들") },
    { en: { s: "Cedar", p: "Cedars" }, es: { gender: "m", s: "cedro", p: "cedros" }, ko: koNoun("삼나무", "삼나무들") },
    { en: { s: "Fir", p: "Firs" }, es: { gender: "m", s: "abeto", p: "abetos" }, ko: koNoun("전나무", "전나무들") },
    { en: { s: "Cypress", p: "Cypresses" }, es: { gender: "m", s: "ciprés", p: "cipreses" }, ko: koNoun("측백나무", "측백나무들") },
    { en: { s: "Palm", p: "Palms" }, es: { gender: "f", s: "palmera", p: "palmeras" }, ko: koNoun("야자나무", "야자나무들") },
    { en: { s: "Bamboo", p: "Bamboos" }, es: { gender: "m", s: "bambú", p: "bambúes" }, ko: koNoun("대나무", "대나무들") },
    { en: { s: "Elm", p: "Elms" }, es: { gender: "m", s: "olmo", p: "olmos" }, ko: koNoun("느릅나무", "느릅나무들") },
    { en: { s: "Ash Tree", p: "Ash Trees" }, es: { gender: "m", s: "fresno", p: "fresnos" }, ko: koNoun("물푸레나무", "물푸레나무들") },
    { en: { s: "Beech", p: "Beeches" }, es: { gender: "f", s: "haya", p: "hayas" }, ko: koNoun("너도밤나무", "너도밤나무들") },
    { en: { s: "Poplar", p: "Poplars" }, es: { gender: "m", s: "álamo", p: "álamos" }, ko: koNoun("포플러", "포플러들") },
    { en: { s: "Chestnut", p: "Chestnuts" }, es: { gender: "m", s: "castaño", p: "castaños" }, ko: koNoun("밤나무", "밤나무들") },
    { en: { s: "Apple Tree", p: "Apple Trees" }, es: { gender: "m", s: "manzano", p: "manzanos" }, ko: koNoun("사과나무", "사과나무들") },
    { en: { s: "Cherry Tree", p: "Cherry Trees" }, es: { gender: "m", s: "cerezo", p: "cerezos" }, ko: koNoun("벚나무", "벚나무들") },
    { en: { s: "Orange Tree", p: "Orange Trees" }, es: { gender: "m", s: "naranjo", p: "naranjos" }, ko: koNoun("오렌지나무", "오렌지나무들") },
    { en: { s: "Olive Tree", p: "Olive Trees" }, es: { gender: "m", s: "olivo", p: "olivos" }, ko: koNoun("올리브나무", "올리브나무들") },
    { en: { s: "Sequoia", p: "Sequoias" }, es: { gender: "f", s: "secuoya", p: "secuoyas" }, ko: koNoun("세쿼이아", "세쿼이아들") }
  ],
  gemstones_crystals: [
    { en: { s: "Diamond", p: "Diamonds" }, es: { gender: "m", s: "diamante", p: "diamantes" }, ko: koNoun("다이아몬드", "다이아몬드들") },
    { en: { s: "Ruby", p: "Rubies" }, es: { gender: "m", s: "rubí", p: "rubíes" }, ko: koNoun("루비", "루비들") },
    { en: { s: "Sapphire", p: "Sapphires" }, es: { gender: "m", s: "zafiro", p: "zafiros" }, ko: koNoun("사파이어", "사파이어들") },
    { en: { s: "Emerald", p: "Emeralds" }, es: { gender: "f", s: "esmeralda", p: "esmeraldas" }, ko: koNoun("에메랄드", "에메랄드들") },
    { en: { s: "Pearl", p: "Pearls" }, es: { gender: "f", s: "perla", p: "perlas" }, ko: koNoun("진주", "진주들") },
    { en: { s: "Opal", p: "Opals" }, es: { gender: "m", s: "ópalo", p: "ópalos" }, ko: koNoun("오팔", "오팔들") },
    { en: { s: "Amethyst", p: "Amethysts" }, es: { gender: "f", s: "amatista", p: "amatistas" }, ko: koNoun("아메시스트", "아메시스트들") },
    { en: { s: "Topaz", p: "Topazes" }, es: { gender: "m", s: "topacio", p: "topacios" }, ko: koNoun("토파즈", "토파즈들") },
    { en: { s: "Garnet", p: "Garnets" }, es: { gender: "m", s: "granate", p: "granates" }, ko: koNoun("가넷", "가넷들") },
    { en: { s: "Turquoise", p: "Turquoises" }, es: { gender: "f", s: "turquesa", p: "turquesas" }, ko: koNoun("터키석", "터키석들") },
    { en: { s: "Jade", p: "Jades" }, es: { gender: "m", s: "jade", p: "jades" }, ko: koNoun("비취", "비취들") },
    { en: { s: "Quartz", p: "Quartzes" }, es: { gender: "m", s: "cuarzo", p: "cuarzos" }, ko: koNoun("수정", "수정들") },
    { en: { s: "Agate", p: "Agates" }, es: { gender: "f", s: "ágata", p: "ágatas" }, ko: koNoun("마노", "마노들") },
    { en: { s: "Amber", p: "Ambers" }, es: { gender: "m", s: "ámbar", p: "ámbares" }, ko: koNoun("호박", "호박들") },
    { en: { s: "Onyx", p: "Onyxes" }, es: { gender: "m", s: "ónix", p: "ónices" }, ko: koNoun("오닉스", "오닉스들") },
    { en: { s: "Crystal", p: "Crystals" }, es: { gender: "m", s: "cristal", p: "cristales" }, ko: koNoun("크리스탈", "크리스탈들") },
    { en: { s: "Moonstone", p: "Moonstones" }, es: { gender: "f", s: "piedra lunar", p: "piedras lunares" }, ko: koNoun("월석", "월석들") },
    { en: { s: "Citrine", p: "Citrines" }, es: { gender: "m", s: "citrino", p: "citrinos" }, ko: koNoun("시트린", "시트린들") },
    { en: { s: "Aquamarine", p: "Aquamarines" }, es: { gender: "f", s: "aguamarina", p: "aguamarinas" }, ko: koNoun("아쿠아마린", "아쿠아마린들") },
    { en: { s: "Geode", p: "Geodes" }, es: { gender: "f", s: "geoda", p: "geodas" }, ko: koNoun("지오드", "지오드들") }
  ],
  metals_alloys: [
    { en: { s: "Iron", p: "Irons" }, es: { gender: "m", s: "hierro", p: "hierros" }, ko: koNoun("철", "철들") },
    { en: { s: "Steel", p: "Steels" }, es: { gender: "m", s: "acero", p: "aceros" }, ko: koNoun("강철", "강철들") },
    { en: { s: "Gold", p: "Golds" }, es: { gender: "m", s: "oro", p: "oros" }, ko: koNoun("금", "금들") },
    { en: { s: "Silver", p: "Silvers" }, es: { gender: "f", s: "plata", p: "platas" }, ko: koNoun("은", "은들") },
    { en: { s: "Copper", p: "Coppers" }, es: { gender: "m", s: "cobre", p: "cobres" }, ko: koNoun("구리", "구리들") },
    { en: { s: "Bronze", p: "Bronzes" }, es: { gender: "m", s: "bronce", p: "bronces" }, ko: koNoun("청동", "청동들") },
    { en: { s: "Brass", p: "Brasses" }, es: { gender: "m", s: "latón", p: "latones" }, ko: koNoun("황동", "황동들") },
    { en: { s: "Tin", p: "Tins" }, es: { gender: "m", s: "estaño", p: "estaños" }, ko: koNoun("주석", "주석들") },
    { en: { s: "Lead", p: "Leads" }, es: { gender: "m", s: "plomo", p: "plomos" }, ko: koNoun("납", "납들") },
    { en: { s: "Aluminum", p: "Aluminums" }, es: { gender: "m", s: "aluminio", p: "aluminios" }, ko: koNoun("알루미늄", "알루미늄들") },
    { en: { s: "Titanium", p: "Titaniums" }, es: { gender: "m", s: "titanio", p: "titanios" }, ko: koNoun("티타늄", "티타늄들") },
    { en: { s: "Nickel", p: "Nickels" }, es: { gender: "m", s: "níquel", p: "níqueles" }, ko: koNoun("니켈", "니켈들") },
    { en: { s: "Chrome", p: "Chromes" }, es: { gender: "m", s: "cromo", p: "cromos" }, ko: koNoun("크롬", "크롬들") },
    { en: { s: "Cobalt", p: "Cobalts" }, es: { gender: "m", s: "cobalto", p: "cobaltos" }, ko: koNoun("코발트", "코발트들") },
    { en: { s: "Tungsten", p: "Tungstens" }, es: { gender: "m", s: "tungsteno", p: "tungstenos" }, ko: koNoun("텅스텐", "텅스텐들") },
    { en: { s: "Platinum", p: "Platinums" }, es: { gender: "m", s: "platino", p: "platinos" }, ko: koNoun("백금", "백금들") },
    { en: { s: "Mercury", p: "Mercuries" }, es: { gender: "m", s: "mercurio", p: "mercurios" }, ko: koNoun("수은", "수은들") },
    { en: { s: "Magnesium", p: "Magnesiums" }, es: { gender: "m", s: "magnesio", p: "magnesios" }, ko: koNoun("마그네슘", "마그네슘들") },
    { en: { s: "Carbon", p: "Carbons" }, es: { gender: "m", s: "carbón", p: "carbones" }, ko: koNoun("탄소", "탄소들") },
    { en: { s: "Metal", p: "Metals" }, es: { gender: "m", s: "metal", p: "metales" }, ko: koNoun("금속", "금속들") }
  ],
  tools_stationery: [
    { en: { s: "Pencil", p: "Pencils" }, es: { gender: "m", s: "lápiz", p: "lápices" }, ko: koNoun("연필", "연필들") },
    { en: { s: "Pen", p: "Pens" }, es: { gender: "m", s: "bolígrafo", p: "bolígrafos" }, ko: koNoun("볼펜", "볼펜들") },
    { en: { s: "Marker", p: "Markers" }, es: { gender: "m", s: "marcador", p: "marcadores" }, ko: koNoun("마커", "마커들") },
    { en: { s: "Brush", p: "Brushes" }, es: { gender: "m", s: "pincel", p: "pinceles" }, ko: koNoun("붓", "붓들") },
    { en: { s: "Eraser", p: "Erasers" }, es: { gender: "m", s: "borrador", p: "borradores" }, ko: koNoun("지우개", "지우개들") },
    { en: { s: "Ruler", p: "Rulers" }, es: { gender: "f", s: "regla", p: "reglas" }, ko: koNoun("자", "자들") },
    { en: { s: "Stapler", p: "Staplers" }, es: { gender: "f", s: "grapadora", p: "grapadoras" }, ko: koNoun("스테이플러", "스테이플러들") },
    { en: { s: "Clip", p: "Clips" }, es: { gender: "m", s: "clip", p: "clips" }, ko: koNoun("클립", "클립들") },
    { en: { s: "Staple", p: "Staples" }, es: { gender: "f", s: "grapa", p: "grapas" }, ko: koNoun("스테이플", "스테이플들") },
    { en: { s: "Notebook", p: "Notebooks" }, es: { gender: "m", s: "cuaderno", p: "cuadernos" }, ko: koNoun("노트", "노트들") },
    { en: { s: "Page", p: "Pages" }, es: { gender: "f", s: "página", p: "páginas" }, ko: koNoun("페이지", "페이지들") },
    { en: { s: "Folder", p: "Folders" }, es: { gender: "f", s: "carpeta", p: "carpetas" }, ko: koNoun("폴더", "폴더들") },
    { en: { s: "Envelope", p: "Envelopes" }, es: { gender: "m", s: "sobre", p: "sobres" }, ko: koNoun("봉투", "봉투들") },
    { en: { s: "Stamp", p: "Stamps" }, es: { gender: "m", s: "sello", p: "sellos" }, ko: koNoun("우표", "우표들") },
    { en: { s: "Sticker", p: "Stickers" }, es: { gender: "f", s: "pegatina", p: "pegatinas" }, ko: koNoun("스티커", "스티커들") },
    { en: { s: "Chalk", p: "Chalks" }, es: { gender: "f", s: "tiza", p: "tizas" }, ko: koNoun("분필", "분필들") },
    { en: { s: "Crayon", p: "Crayons" }, es: { gender: "m", s: "crayón", p: "crayones" }, ko: koNoun("크레용", "크레용들") },
    { en: { s: "Highlighter", p: "Highlighters" }, es: { gender: "m", s: "resaltador", p: "resaltadores" }, ko: koNoun("형광펜", "형광펜들") },
    { en: { s: "Tape", p: "Tapes" }, es: { gender: "f", s: "cinta", p: "cintas" }, ko: koNoun("테이프", "테이프들") },
    { en: { s: "Pin", p: "Pins" }, es: { gender: "m", s: "alfiler", p: "alfileres" }, ko: koNoun("핀", "핀들") }
  ],
  household_objects: [
    { en: { s: "Key", p: "Keys" }, es: { gender: "f", s: "llave", p: "llaves" }, ko: koNoun("열쇠", "열쇠들") },
    { en: { s: "Lock", p: "Locks" }, es: { gender: "f", s: "cerradura", p: "cerraduras" }, ko: koNoun("자물쇠", "자물쇠들") },
    { en: { s: "Lamp", p: "Lamps" }, es: { gender: "f", s: "lámpara", p: "lámparas" }, ko: koNoun("램프", "램프들") },
    { en: { s: "Lantern", p: "Lanterns" }, es: { gender: "f", s: "linterna", p: "linternas" }, ko: koNoun("랜턴", "랜턴들") },
    { en: { s: "Candle", p: "Candles" }, es: { gender: "f", s: "vela", p: "velas" }, ko: koNoun("양초", "양초들") },
    { en: { s: "Mirror", p: "Mirrors" }, es: { gender: "m", s: "espejo", p: "espejos" }, ko: koNoun("거울", "거울들") },
    { en: { s: "Glass", p: "Glasses" }, es: { gender: "m", s: "vaso", p: "vasos" }, ko: koNoun("유리잔", "유리잔들") },
    { en: { s: "Bottle", p: "Bottles" }, es: { gender: "f", s: "botella", p: "botellas" }, ko: koNoun("병", "병들") },
    { en: { s: "Cup", p: "Cups" }, es: { gender: "f", s: "taza", p: "tazas" }, ko: koNoun("컵", "컵들") },
    { en: { s: "Plate", p: "Plates" }, es: { gender: "m", s: "plato", p: "platos" }, ko: koNoun("접시", "접시들") },
    { en: { s: "Bowl", p: "Bowls" }, es: { gender: "m", s: "cuenco", p: "cuencos" }, ko: koNoun("그릇", "그릇들") },
    { en: { s: "Spoon", p: "Spoons" }, es: { gender: "f", s: "cuchara", p: "cucharas" }, ko: koNoun("숟가락", "숟가락들") },
    { en: { s: "Fork", p: "Forks" }, es: { gender: "m", s: "tenedor", p: "tenedores" }, ko: koNoun("포크", "포크들") },
    { en: { s: "Knife", p: "Knives" }, es: { gender: "m", s: "cuchillo", p: "cuchillos" }, ko: koNoun("칼", "칼들") },
    { en: { s: "Pot", p: "Pots" }, es: { gender: "f", s: "olla", p: "ollas" }, ko: koNoun("냄비", "냄비들") },
    { en: { s: "Pan", p: "Pans" }, es: { gender: "f", s: "sartén", p: "sartenes" }, ko: koNoun("프라이팬", "프라이팬들") },
    { en: { s: "Chair", p: "Chairs" }, es: { gender: "f", s: "silla", p: "sillas" }, ko: koNoun("의자", "의자들") },
    { en: { s: "Table", p: "Tables" }, es: { gender: "f", s: "mesa", p: "mesas" }, ko: koNoun("테이블", "테이블들") },
    { en: { s: "Clock", p: "Clocks" }, es: { gender: "m", s: "reloj", p: "relojes" }, ko: koNoun("시계", "시계들") },
    { en: { s: "Bell", p: "Bells" }, es: { gender: "f", s: "campana", p: "campanas" }, ko: koNoun("종", "종들") }
  ],
  tech_components: [
    { en: { s: "Circuit", p: "Circuits" }, es: { gender: "m", s: "circuito", p: "circuitos" }, ko: koNoun("회로", "회로들") },
    { en: { s: "Chip", p: "Chips" }, es: { gender: "m", s: "chip", p: "chips" }, ko: koNoun("칩", "칩들") },
    { en: { s: "Cable", p: "Cables" }, es: { gender: "m", s: "cable", p: "cables" }, ko: koNoun("케이블", "케이블들") },
    { en: { s: "Wire", p: "Wires" }, es: { gender: "m", s: "alambre", p: "alambres" }, ko: koNoun("전선", "전선들") },
    { en: { s: "Sensor", p: "Sensors" }, es: { gender: "m", s: "sensor", p: "sensores" }, ko: koNoun("센서", "센서들") },
    { en: { s: "Motor", p: "Motors" }, es: { gender: "m", s: "motor", p: "motores" }, ko: koNoun("모터", "모터들") },
    { en: { s: "Gear", p: "Gears" }, es: { gender: "m", s: "engranaje", p: "engranajes" }, ko: koNoun("기어", "기어들") },
    { en: { s: "Battery", p: "Batteries" }, es: { gender: "f", s: "batería", p: "baterías" }, ko: koNoun("배터리", "배터리들") },
    { en: { s: "Screen", p: "Screens" }, es: { gender: "f", s: "pantalla", p: "pantallas" }, ko: koNoun("스크린", "스크린들") },
    { en: { s: "Lens", p: "Lenses" }, es: { gender: "f", s: "lente", p: "lentes" }, ko: koNoun("렌즈", "렌즈들") },
    { en: { s: "Camera", p: "Cameras" }, es: { gender: "f", s: "cámara", p: "cámaras" }, ko: koNoun("카메라", "카메라들") },
    { en: { s: "Robot", p: "Robots" }, es: { gender: "m", s: "robot", p: "robots" }, ko: koNoun("로봇", "로봇들") },
    { en: { s: "Drone", p: "Drones" }, es: { gender: "m", s: "dron", p: "drones" }, ko: koNoun("드론", "드론들") },
    { en: { s: "Server", p: "Servers" }, es: { gender: "m", s: "servidor", p: "servidores" }, ko: koNoun("서버", "서버들") },
    { en: { s: "Router", p: "Routers" }, es: { gender: "m", s: "router", p: "routers" }, ko: koNoun("라우터", "라우터들") },
    { en: { s: "Switch", p: "Switches" }, es: { gender: "m", s: "interruptor", p: "interruptores" }, ko: koNoun("스위치", "스위치들") },
    { en: { s: "Module", p: "Modules" }, es: { gender: "m", s: "módulo", p: "módulos" }, ko: koNoun("모듈", "모듈들") },
    { en: { s: "Node", p: "Nodes" }, es: { gender: "m", s: "nodo", p: "nodos" }, ko: koNoun("노드", "노드들") },
    { en: { s: "Signal", p: "Signals" }, es: { gender: "f", s: "señal", p: "señales" }, ko: koNoun("신호", "신호들") },
    { en: { s: "Pixel", p: "Pixels" }, es: { gender: "m", s: "píxel", p: "píxeles" }, ko: koNoun("픽셀", "픽셀들") }
  ],
  sky_celestial: [
    { en: { s: "Star", p: "Stars" }, es: { gender: "f", s: "estrella", p: "estrellas" }, ko: koNoun("별", "별들") },
    { en: { s: "Moon", p: "Moons" }, es: { gender: "f", s: "luna", p: "lunas" }, ko: koNoun("달", "달들") },
    { en: { s: "Sun", p: "Suns" }, es: { gender: "m", s: "sol", p: "soles" }, ko: koNoun("태양", "태양들") },
    { en: { s: "Planet", p: "Planets" }, es: { gender: "m", s: "planeta", p: "planetas" }, ko: koNoun("행성", "행성들") },
    { en: { s: "Comet", p: "Comets" }, es: { gender: "m", s: "cometa", p: "cometas" }, ko: koNoun("혜성", "혜성들") },
    { en: { s: "Meteor", p: "Meteors" }, es: { gender: "m", s: "meteoro", p: "meteoros" }, ko: koNoun("유성", "유성들") },
    { en: { s: "Galaxy", p: "Galaxies" }, es: { gender: "f", s: "galaxia", p: "galaxias" }, ko: koNoun("은하", "은하들") },
    { en: { s: "Nebula", p: "Nebulas" }, es: { gender: "f", s: "nebulosa", p: "nebulosas" }, ko: koNoun("성운", "성운들") },
    { en: { s: "Orbit", p: "Orbits" }, es: { gender: "f", s: "órbita", p: "órbitas" }, ko: koNoun("궤도", "궤도들") },
    { en: { s: "Ring", p: "Rings" }, es: { gender: "m", s: "anillo", p: "anillos" }, ko: koNoun("고리", "고리들") },
    { en: { s: "Halo", p: "Halos" }, es: { gender: "m", s: "halo", p: "halos" }, ko: koNoun("후광", "후광들") },
    { en: { s: "Aurora", p: "Auroras" }, es: { gender: "f", s: "aurora", p: "auroras" }, ko: koNoun("오로라", "오로라들") },
    { en: { s: "Solar Eclipse", p: "Solar Eclipses" }, es: { gender: "m", s: "eclipse solar", p: "eclipses solares" }, ko: koNoun("일식", "일식들") },
    { en: { s: "Lunar Eclipse", p: "Lunar Eclipses" }, es: { gender: "m", s: "eclipse lunar", p: "eclipses lunares" }, ko: koNoun("월식", "월식들") },
    { en: { s: "Constellation", p: "Constellations" }, es: { gender: "f", s: "constelación", p: "constelaciones" }, ko: koNoun("별자리", "별자리들") },
    { en: { s: "Horizon", p: "Horizons" }, es: { gender: "m", s: "horizonte", p: "horizontes" }, ko: koNoun("지평선", "지평선들") },
    { en: { s: "Sky", p: "Skies" }, es: { gender: "m", s: "cielo", p: "cielos" }, ko: koNoun("하늘", "하늘들") },
    { en: { s: "Satellite", p: "Satellites" }, es: { gender: "m", s: "satélite", p: "satélites" }, ko: koNoun("위성", "위성들") },
    { en: { s: "Telescope", p: "Telescopes" }, es: { gender: "m", s: "telescopio", p: "telescopios" }, ko: koNoun("망원경", "망원경들") },
    { en: { s: "Asteroid", p: "Asteroids" }, es: { gender: "m", s: "asteroide", p: "asteroides" }, ko: koNoun("소행성", "소행성들") }
  ],
  weather_water: [
    { en: { s: "Wave", p: "Waves" }, es: { gender: "f", s: "ola", p: "olas" }, ko: koNoun("파도", "파도들") },
    { en: { s: "Tide", p: "Tides" }, es: { gender: "f", s: "marea", p: "mareas" }, ko: koNoun("조수", "조수들") },
    { en: { s: "Storm", p: "Storms" }, es: { gender: "f", s: "tormenta", p: "tormentas" }, ko: koNoun("폭풍", "폭풍들") },
    { en: { s: "Raindrop", p: "Raindrops" }, es: { gender: "f", s: "gota de lluvia", p: "gotas de lluvia" }, ko: koNoun("빗방울", "빗방울들") },
    { en: { s: "Snowflake", p: "Snowflakes" }, es: { gender: "m", s: "copo de nieve", p: "copos de nieve" }, ko: koNoun("눈송이", "눈송이들") },
    { en: { s: "Wind", p: "Winds" }, es: { gender: "m", s: "viento", p: "vientos" }, ko: koNoun("바람", "바람들") },
    { en: { s: "Breeze", p: "Breezes" }, es: { gender: "f", s: "brisa", p: "brisas" }, ko: koNoun("산들바람", "산들바람들") },
    { en: { s: "Thunderclap", p: "Thunderclaps" }, es: { gender: "m", s: "trueno", p: "truenos" }, ko: koNoun("천둥", "천둥들") },
    { en: { s: "Lightning Bolt", p: "Lightning Bolts" }, es: { gender: "m", s: "rayo", p: "rayos" }, ko: koNoun("번개", "번개들") },
    { en: { s: "Cloud", p: "Clouds" }, es: { gender: "f", s: "nube", p: "nubes" }, ko: koNoun("구름", "구름들") },
    { en: { s: "Mist", p: "Mists" }, es: { gender: "f", s: "bruma", p: "brumas" }, ko: koNoun("엷은 안개", "엷은 안개들") },
    { en: { s: "Fog", p: "Fogs" }, es: { gender: "f", s: "niebla", p: "nieblas" }, ko: koNoun("짙은 안개", "짙은 안개들") },
    { en: { s: "Shower", p: "Showers" }, es: { gender: "m", s: "chubasco", p: "chubascos" }, ko: koNoun("소나기", "소나기들") },
    { en: { s: "Hurricane", p: "Hurricanes" }, es: { gender: "m", s: "huracán", p: "huracanes" }, ko: koNoun("허리케인", "허리케인들") },
    { en: { s: "Tornado", p: "Tornadoes" }, es: { gender: "m", s: "tornado", p: "tornados" }, ko: koNoun("토네이도", "토네이도들") },
    { en: { s: "Blizzard", p: "Blizzards" }, es: { gender: "f", s: "ventisca", p: "ventiscas" }, ko: koNoun("눈보라", "눈보라들") },
    { en: { s: "Frost", p: "Frosts" }, es: { gender: "f", s: "escarcha", p: "escarchas" }, ko: koNoun("서리", "서리들") },
    { en: { s: "Dewdrop", p: "Dewdrops" }, es: { gender: "f", s: "gota de rocío", p: "gotas de rocío" }, ko: koNoun("이슬방울", "이슬방울들") },
    { en: { s: "River", p: "Rivers" }, es: { gender: "m", s: "río", p: "ríos" }, ko: koNoun("강", "강들") },
    { en: { s: "Ocean", p: "Oceans" }, es: { gender: "m", s: "océano", p: "océanos" }, ko: koNoun("바다", "바다들") }
  ],
  geography_places: [
    { en: { s: "Island", p: "Islands" }, es: { gender: "f", s: "isla", p: "islas" }, ko: koNoun("섬", "섬들") },
    { en: { s: "Mountain", p: "Mountains" }, es: { gender: "f", s: "montaña", p: "montañas" }, ko: koNoun("산", "산들") },
    { en: { s: "Valley", p: "Valleys" }, es: { gender: "m", s: "valle", p: "valles" }, ko: koNoun("계곡", "계곡들") },
    { en: { s: "Forest", p: "Forests" }, es: { gender: "m", s: "bosque", p: "bosques" }, ko: koNoun("숲", "숲들") },
    { en: { s: "Desert", p: "Deserts" }, es: { gender: "m", s: "desierto", p: "desiertos" }, ko: koNoun("사막", "사막들") },
    { en: { s: "Beach", p: "Beaches" }, es: { gender: "f", s: "playa", p: "playas" }, ko: koNoun("해변", "해변들") },
    { en: { s: "River", p: "Rivers" }, es: { gender: "m", s: "río", p: "ríos" }, ko: koNoun("강", "강들") },
    { en: { s: "Lake", p: "Lakes" }, es: { gender: "m", s: "lago", p: "lagos" }, ko: koNoun("호수", "호수들") },
    { en: { s: "Ocean", p: "Oceans" }, es: { gender: "m", s: "océano", p: "océanos" }, ko: koNoun("바다", "바다들") },
    { en: { s: "Canyon", p: "Canyons" }, es: { gender: "m", s: "cañón", p: "cañones" }, ko: koNoun("협곡", "협곡들") },
    { en: { s: "Cliff", p: "Cliffs" }, es: { gender: "m", s: "acantilado", p: "acantilados" }, ko: koNoun("절벽", "절벽들") },
    { en: { s: "Plain", p: "Plains" }, es: { gender: "f", s: "llanura", p: "llanuras" }, ko: koNoun("평야", "평야들") },
    { en: { s: "Meadow", p: "Meadows" }, es: { gender: "f", s: "pradera", p: "praderas" }, ko: koNoun("초원", "초원들") },
    { en: { s: "Garden", p: "Gardens" }, es: { gender: "m", s: "jardín", p: "jardines" }, ko: koNoun("정원", "정원들") },
    { en: { s: "Harbor", p: "Harbors" }, es: { gender: "m", s: "puerto", p: "puertos" }, ko: koNoun("항구", "항구들") },
    { en: { s: "Bridge", p: "Bridges" }, es: { gender: "m", s: "puente", p: "puentes" }, ko: koNoun("다리", "다리들") },
    { en: { s: "Road", p: "Roads" }, es: { gender: "m", s: "camino", p: "caminos" }, ko: koNoun("길", "길들") },
    { en: { s: "City", p: "Cities" }, es: { gender: "f", s: "ciudad", p: "ciudades" }, ko: koNoun("도시", "도시들") },
    { en: { s: "Village", p: "Villages" }, es: { gender: "m", s: "pueblo", p: "pueblos" }, ko: koNoun("마을", "마을들") },
    { en: { s: "District", p: "Districts" }, es: { gender: "m", s: "distrito", p: "distritos" }, ko: koNoun("구역", "구역들") }
  ],
  groups_formations: [
    { en: { s: "Team", p: "Teams" }, es: { gender: "m", s: "equipo", p: "equipos" }, ko: koNoun("팀", "팀들") },
    { en: { s: "Crew", p: "Crews" }, es: { gender: "f", s: "tripulación", p: "tripulaciones" }, ko: koNoun("크루", "크루들") },
    { en: { s: "Band", p: "Bands" }, es: { gender: "f", s: "banda", p: "bandas" }, ko: koNoun("밴드", "밴드들") },
    { en: { s: "Choir", p: "Choirs" }, es: { gender: "m", s: "coro", p: "coros" }, ko: koNoun("합창단", "합창단들") },
    { en: { s: "Guild", p: "Guilds" }, es: { gender: "m", s: "gremio", p: "gremios" }, ko: koNoun("길드", "길드들") },
    { en: { s: "Order", p: "Orders" }, es: { gender: "f", s: "orden", p: "órdenes" }, ko: koNoun("기사단", "기사단들") },
    { en: { s: "Circle", p: "Circles" }, es: { gender: "m", s: "círculo", p: "círculos" }, ko: koNoun("서클", "서클들") },
    { en: { s: "Squad", p: "Squads" }, es: { gender: "m", s: "escuadrón", p: "escuadrones" }, ko: koNoun("분대", "분대들") },
    { en: { s: "Unit", p: "Units" }, es: { gender: "f", s: "unidad", p: "unidades" }, ko: koNoun("유닛", "유닛들") },
    { en: { s: "Pack", p: "Packs" }, es: { gender: "f", s: "manada", p: "manadas" }, ko: koNoun("무리", "무리들") },
    { en: { s: "Flock", p: "Flocks" }, es: { gender: "f", s: "bandada", p: "bandadas" }, ko: koNoun("새떼", "새떼들") },
    { en: { s: "Herd", p: "Herds" }, es: { gender: "m", s: "rebaño", p: "rebaños" }, ko: koNoun("가축떼", "가축떼들") },
    { en: { s: "Swarm", p: "Swarms" }, es: { gender: "m", s: "enjambre", p: "enjambres" }, ko: koNoun("벌떼", "벌떼들") },
    { en: { s: "Army", p: "Armies" }, es: { gender: "m", s: "ejército", p: "ejércitos" }, ko: koNoun("군대", "군대들") },
    { en: { s: "Legion", p: "Legions" }, es: { gender: "f", s: "legión", p: "legiones" }, ko: koNoun("군단", "군단들") },
    { en: { s: "Alliance", p: "Alliances" }, es: { gender: "f", s: "alianza", p: "alianzas" }, ko: koNoun("연합", "연합들") },
    { en: { s: "Council", p: "Councils" }, es: { gender: "m", s: "consejo", p: "consejos" }, ko: koNoun("의회", "의회들") },
    { en: { s: "Club", p: "Clubs" }, es: { gender: "m", s: "club", p: "clubes" }, ko: koNoun("동아리", "동아리들") },
    { en: { s: "Network", p: "Networks" }, es: { gender: "f", s: "red", p: "redes" }, ko: koNoun("네트워크", "네트워크들") },
    { en: { s: "Collective", p: "Collectives" }, es: { gender: "m", s: "colectivo", p: "colectivos" }, ko: koNoun("집단", "집단들") }
  ]
};

const adjectives: Record<string, ActNameAdjective> = {};
const adjectiveCategories: Record<string, string[]> = {};

Object.entries(ADJECTIVE_CATEGORIES).forEach(([categoryKey, entries]) => {
  adjectiveCategories[categoryKey] = entries.map((entry, index) => {
    const id = `adj.${categoryKey}.${index}`;
    adjectives[id] = entry;
    return id;
  });
});

const nouns: Record<string, ActNameNoun> = {};
const nounCategories: Record<string, string[]> = {};

Object.entries(NOUN_CATEGORIES).forEach(([categoryKey, entries]) => {
  nounCategories[categoryKey] = entries.map((entry, index) => {
    const id = `noun.${categoryKey}.${index}`;
    nouns[id] = entry;
    return id;
  });
});

export const ACT_NAME_ADJECTIVES = adjectives;
export const ACT_NAME_NOUNS = nouns;
export const ACT_NAME_CATEGORIES = { adjectiveCategories, nounCategories };
export const ACT_NAME_ADJECTIVE_CATEGORY_IDS = Object.keys(adjectiveCategories);
export const ACT_NAME_NOUN_CATEGORY_IDS = Object.keys(nounCategories);
export const ACT_NAME_TOTALS = {
  adjectives: Object.keys(adjectives).length,
  nouns: Object.keys(nouns).length
};
