/* Global data declarations provided by assets/js/data/*.js */
declare const THEMES: string[];
declare const MOODS: string[];
declare const ALIGNMENTS: string[];
declare const ACT_TYPES: string[];
declare const HOUR_MS: number;
declare const QUARTERS_PER_HOUR: number;
declare const QUARTER_HOUR_MS: number;
declare const WEEK_HOURS: number;
declare const BASE_EPOCH: number;
declare const BROADCAST_SLOT_SCHEDULE: number[];
declare const FILMING_STUDIO_SLOTS: number;
declare const BROADCAST_PROGRAMS: {
  id: string;
  label: string;
  tier: string;
  minQuality: number;
  requiresCharting: boolean;
  allowsActOnly: boolean;
}[];
declare const BROADCAST_STUDIOS: {
  id: string;
  label: string;
  owner: string;
  scope: { type: string; id: string; regions?: string[] };
  slotSchedule: number[];
  audience: { ages: string[]; alignment: string[]; themes: string[]; moods: string[] };
}[];
declare const STAGES: { name: string; role: string; hours: number; cost: number; stamina: number; progress: number }[];
declare const TRACK_ROLE_LIMITS: Record<string, number>;
declare const STAMINA_MAX: number;
declare const SKILL_MIN: number;
declare const SKILL_MAX: number;
declare const QUALITY_MIN: number;
declare const QUALITY_MAX: number;
declare const ERA_STAGES: string[];
declare const ROLLOUT_PRESETS: { id: string; label: string; weeks: number[] }[];
declare const CHART_SIZES: { global: number; nation: number; region: number };
declare const CHART_WEIGHTS: { sales: number; streaming: number; airplay: number; social: number };
declare const REGION_CONSUMPTION_WEIGHTS: Record<string, { sales: number; streaming: number; airplay: number; social: number }>;
declare const NATIONS: string[];
declare const REGION_DEFS: { id: string; nation: string; label: string }[];
declare const NATION_PROFILES: Record<string, { alignment: string; theme: string; moods: string[] }>;
declare const REGION_PROFILES: Record<string, { alignment: string; theme: string; moods: string[] }>;
declare const POPULATION_START_YEAR: number;
declare const POPULATION_START: number;
declare const POPULATION_TIER_1: number;
declare const POPULATION_TIER_2: number;
declare const POPULATION_CAP: number;
declare const POPULATION_POST3000_BAND: number;
declare const POPULATION_STAGES: { id: string; startYear: number; endYear: number; splits: Record<string, number>; variancePoints?: number }[];
declare const REGION_CAPITAL_SHARE: number;
declare const MONOPOLY_SHARE: number;
declare const ECONOMY_BASELINES: {
  digitalSingle: number;
  physicalSingle: number;
  physicalReleaseFee: number;
  physicalUnitCostRatio: number;
  physicalRunMin: number;
  physicalRunMax: number;
  physicalRunRound: number;
  studioLease4y: number;
  studioBuildCost: number;
  tuitionPerMember: number;
  subscription: number;
  governmentFunds: number;
};
declare const PRICE_PATTERN: number[];
declare const MODIFIERS: { id: string; label: string; qualityDelta: number; hoursDelta: number; costDelta: number; desc: string }[];
declare const DAYS: string[];
declare const MONTHS: string[];
declare const SLOT_COUNT: number;
declare const SLOT_PREFIX: string;
declare const THEME_COLORS: Record<string, string>;
declare const COUNTRY_COLORS: Record<string, string>;
declare const COUNTRY_DEMONYMS: Record<string, string>;
declare const COUNTRY_LANGUAGE_WEIGHTS: Record<string, { lang: string; weight: number }[]>;
declare const AI_LABELS: { id: string; name: string; alignment: string; country: string; focusThemes: string[]; focusMoods: string[] }[];
declare const TRACKLIST: { title: string; act: string; theme: string; mood: string }[];
declare const TRACK_TITLES_EN: string[];
declare const TRACK_TITLES_KR: string[];
declare const TRACK_TITLES_ES: string[];
declare const SOCIAL_TEMPLATES: Record<string, unknown>;
declare function postFromTemplate(id: string, vars?: Record<string, unknown>): void;
declare const RLS_RELEASE: { patchId: string; timestamp: string; channel: string };
